### ISSUE TITLE
Inconsistent output when projection fails

### ISSUE THREAD

**Issue by mbloch** [proj4js/proj4js#121]
When the original Proj.4 can't transform a coordinate pair, it sets the output coordinates to a single value, HUGE_VAL (defined in math.h)

It would be nice if proj4js did something similar. Currently it gives inconsistent results.
Here are some examples of unprojectable coordinates:

```
var merc = require('proj4')('EPSG:3857');
console.log(merc.forward([0, -90])); // [ 0, -1.5707963267948966 ]
console.log(merc.forward([0, 90]));  // [ 0, 1.5707963267948966 ]
console.log(merc.forward([0, 91]));  // [ 0, NaN ]
```

It would be easier to test for errors if  x and y (or lat and lng) were both set to a single value, like Infinity, or if the forward() and inverse() methods returned null instead of a point.

**Comment by calvinmetcalf** [comment]
I think we fixed this in more recent versions
