### ISSUE TITLE
Uncaught exception when parsing ESRI WKT

### ISSUE THREAD

**Issue by SanderSchaminee** [proj4js/proj4js#143]
Hi there,

I have this ESRI WKT projections string, which I took from ESRI's website (so I would think it is ok):

'PROJCS["DHDN_3_Degree_Gauss_Zone_3",GEOGCS["GCS_Deutsches_Hauptdreiecksnetz",DATUM["D_Deutsches_Hauptdreiecksnetz",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Gauss_Kruger"],PARAMETER["False_Easting",3500000.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",9.0],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",0.0],UNIT["Meter",1.0]]'

When I pass it to proj4js, there is an uncaught exception:

Uncaught   proj4.js:1
b                proj4.js:1
Projection  proj4.js:1
Projection  proj4.js:1
d                proj4.js:1
proj4          proj4.js:1

(Obviously, it's all in line 1, because the library is minified, but I just thought I post it anyway...)

It doesn't happen with some other ESRI WKT's I've tried so far, so there is nothing wrong in the way I am calling it.
Also, if I pass in the proj4 definition of the exact same projection, the exception doesn't occur.
This leads me to believe there is something wrong in the WKT parser?

I will think of a workaround for now, but maybe someone can look into this. 
I lack the skills to look at it myself...

**Comment by calvinmetcalf** [comment]
I don't believe we have support for ' D_Deutsches_Hauptdreiecksnetz'  as a
datum yet

**Comment by SanderSchaminee** [comment]
Thanks for the response!
So that makes sense then :)

Maybe it might be nice to have some kind of error message ("Unsupported datum" or whatever)?
