### ISSUE TITLE
Problem with some zone convertion

### ISSUE THREAD

**Issue by federicolucca** [proj4js/proj4js#148]
var degrees2meters = function(lon, lat) {

        return proj4(proj4.defs('WGS84'), proj4.defs('EPSG:3857')).forward([lat, lon]);
    }

    var meters2degrees = function(lon, lat) {

        return proj4(proj4.defs('EPSG:3857'),proj4.defs('WGS84')).inverse([lat, lon]);
    }

i wrote this code ,that takes the lat long from a google map plugin(wgs84) and converts to EPSG:3857,and the inverse.

Works fine,but there are some problems on some zone.

Europe,US,Australia works fine,but i find errors in China and Tibet. I am not a Gis expert someone can help me? 

Example:Nagqu, Tibet, Cina
From google(WGS84): [long: 31.476202,lat: 92.05123900000001]
EPSG:3857 after convertion [3503914.7787462194, NaN]

**Comment by ahocevar** [comment]
The latitude you are trying to convert cannot be expressed in EPSG:3857. It exceeds the projection bounds. EPSG:3857 is not suitable for polar regions.

**Comment by ahocevar** [comment]
Also, a latitude of 92 degrees does not look right. For Tibet, this would make sense as longitude. So pass your coordinates in reverse order, and you'll be fine.

**Comment by federicolucca** [comment]
ok,with the right parameters, i have the same problem,but if i stop the debugger after the first call,i receive the correct result after some time, but the binding is on the first 

this is without debugger
degrees2meters Long:14.268124400000033 -> 1604995.8312923796,Lat:40.8517746 ->4547598.746473587
 [4547598.746473587, 1604995.8312923796]
degrees2meters Long:91.117212 -> NaN,Lat:29.646923 ->3300280.3719473905
[3300280.3719473905, NaN]


this with debugger for 5 sec
degrees2meters Long:91.117212 -> NaN,Lat:29.646923 ->3300280.3719473905
degrees2meters Long:29.646923 -> 3458245.3461042424,Lat:91.117212 ->10143121.642342756
[3300280.3719473905, NaN]
