### ISSUE TITLE
MGRS inconsistent behavior.

### ISSUE THREAD

**Issue by hobiedude** [proj4js/proj4js#151]
If I pass in latitude (89.95337) longitude (-64.58372) and call:

                    point = proj4.Point(latLong.lon, latLong.lat);
                    retStr = point.toMGRS(5);
retStr has a value of 20ZME9985692761.

If I then call:

point = proj4.mgrs.toPoint('20ZME9985692761');

an exception is thrown:
MGRSPoint zone letter Z not handled: 20ZME9985692761

Seems like if a mgrs string can be obtained from a latitude longitude, that the mgrs string should result in roughly the same latitude, longitude.

**Comment by ahocevar** [comment]
Copied to proj4js/mgrs#11, closing here.
