### ISSUE TITLE
Licensing enquiry

### ISSUE THREAD

**Issue by PetrusvanderMewre** [proj4js/proj4js#152]
Love using proj4js, it improves our performance a lot.

Due to an internal open source audit we found some parts of the proj4js code for which the licensing was a unclear to us.

Just to confirm, does the License.MD file extend to all the files in this GITHUB project?

In particular, in Proj4-src.js line 911 there is a section of code with comments:
    /* --------------------------------------------------------------
     * Following iterative algorithm was developped by
     * "Institut for Erdmessung", University of Hannover, July 1988.
     * Internet: www.ife.uni-hannover.de
     * Iterative computation of CPHI,SPHI and Height.
     * Iteration of CPHI and SPHI to 10**-12 radian resp.
     * 2*10**-7 arcsec.
     * --------------------------------------------------------------
     */

Is this code also covered by the license? I hope the answers is yes :)

**Comment by ahocevar** [comment]
Disclaimer: I am not a lawyer or legal expert. In general, the license.md file covers all files in the project. Comments like the one you found give credit to the creator of the algorithm, not the code.

**Comment by PetrusvanderMewre** [comment]
Thank you for the quick response, really appreciate it
