### ISSUE TITLE
Hotine_Oblique_Mercator_Azimuth_Natural_Origin

### ISSUE THREAD

**Issue by sainsb** [proj4js/proj4js#153]
Proj4js doesn't like this .prj string:

`PROJCS["NAD_1983_Michigan_GeoRef_Meters",GEOGCS["GCS_North_American_1983",DATUM["D_North_American_1983",SPHEROID["GRS_1980",6378137.0,298.257222101]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Hotine_Oblique_Mercator_Azimuth_Natural_Origin"],PARAMETER["False_Easting",2546731.496],PARAMETER["False_Northing",-4354009.816],PARAMETER["Scale_Factor",0.9996],PARAMETER["Azimuth",337.25556],PARAMETER["Longitude_Of_Center",-86.0],PARAMETER["Latitude_Of_Center",45.30916666666666],UNIT["Meter",1.0]]`

Any pointers on how to go about fixing this in the source? thank you.

**Comment by calvinmetcalf** [comment]
it what way does it not like it?

**Comment by sainsb** [comment]
Doesn't appear to be able to convert the coords:
https://gist.github.com/sainsb/f0f3a58af79d7803a1f5

Looks to be a notoriously troublesome projection for proj4:
http://osdir.com/ml/gis.proj-4.devel/2004-12/msg00027.html

Got it working with a proj4 string in the above thread but not the spatial reference proj4 string for 102123.
http://spatialreference.org/ref/esri/nad-1983-michigan-georef-meters/

weird.

**Comment by calvinmetcalf** [comment]
so the Hotine code is located in this file https://github.com/proj4js/proj4js/blob/master/lib/projections/omerc.js I'd suspect the issue would be a parameter name getting missed, though in the example you posted the only difference seems to be `+no_defs` being present in the broken one, does it work if you omit that ?

**Comment by sainsb** [comment]
thanks for the link to the source file.
`+no defs` : not the only difference. different x_0 val and y_0 val.
seems like a bit of a black hole here.  going to avoid for now.
