### ISSUE TITLE
Bug on fitBounds()?

### ISSUE THREAD

**Issue by leoss** [proj4js/proj4js#154]
Hi,

first let me thank you for this very nice library. It makes really fun to use it.
I recognized a strange behaviour and now I want to know whether this problem is known or not.

When I use mollweide projection I set some markers and focus the view on it:

```
var crs = new L.Proj.CRS('ESRI:53009', '+proj=moll +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs', {
    resolutions: [32768, 22000, 20000, 18000, 16384, 12000, 10000, 8192, 4096, 2048] 
});

var map = L.map('map', {
    crs: crs,
    maxZoom: 10
});

var latlngs = [[32.642232,-16.907967],[65.241007,-12.577565],[44.45852,-62.767383],[32.7502856,129.87766699]];
var polyline = L.polyline(latlngs);
map.fitBounds(polyline.getBounds());
```

You can see a running example at http://leo.running-sheep.de/tmp/proj4js-bug/infoboard-tmp.html

The problem is that the map is not focused on the four markers. Somehow it is shifted to west and therefore the marker in the east is not visible.

Do you know whether this is a known bug? Is it proj4js related or leaflet related?

**Comment by calvinmetcalf** [comment]
try adding `L.rectangle(polyline.getBounds()).addTo(map)` which shows you the bounding box which you're working off of. Looks like it could be a proj4leaflet issue or more likely an unintented consequence of leaflet assuming web Mercator for some of it's operations

**Comment by leoss** [comment]
I added the rectangle. Maybe you are right with your assumption. 
Any idea what to do as workaround?

**Comment by leoss** [comment]
The following final workaround is implemented by me:

```
		//implement workaround for bug https://github.com/proj4js/proj4js/issues/154
		var conLine = L.polyline(latlngs); //all items connecting line
		var southLine = [conLine.getBounds().getSouthWest(), conLine.getBounds().getSouthEast()];

		var centerLine = L.polyline(southLine); //line to zoom on
		//center and zoom on markers and reserve space on top for popups
		map.fitBounds(centerLine.getBounds(), {paddingTopLeft: [0,80], paddingBottomRight: [0,0]}); 

		//get edge (in pixel position) in north and south of bounding box
		var edgeSouthWest = map.project(conLine.getBounds().getSouthWest());
		var edgeNorthWest = map.project(conLine.getBounds().getNorthWest());
		//pixel to pan (half of pixel height)
		var panPixels = (edgeNorthWest.y - edgeSouthWest.y) / 2;
		map.panBy([0,panPixels]);
```
see http://leo.running-sheep.de/tmp/proj4js-bug/infoboard-tmp-workaround.html as example

It has to be noted that this workaround assumes you have only markers on the northern hemisphere because is zooms on the southern edges of the bound box.

**Comment by calvinmetcalf** [comment]
this is more of a leaflet issue
