### ISSUE TITLE
to_meter conversion factor wrong for GEOGCS WKT

### ISSUE THREAD

**Issue by tbarsballe** [proj4js/proj4js#156]
In lib/wkt.js, the `to_meter` conversion factor is set directly from the WKT UNIT (see https://github.com/proj4js/proj4js/blob/master/lib/wkt.js#L114), regardless of the context.

From http://www.geoapi.org/3.0/javadoc/org/opengis/referencing/doc-files/WKT.html#UNIT (emphasis mine):

> UNIT

> This describes units used for values elsewhere within the parent WKT clause (sometimes including descendants of the parent clause). The physical dimension (i.e. type) of the units is determined by context. For example, in a **GEOGCS the type of the units is angular**. In a VERT_CS the type of the units is linear. Within a UNIT clause, the units are described by relating them to a fundamental unit of that type with a conversion factor. For linear units, the conversion factor is the scalar value that converts the described units into meters. **For angular units, the conversion factor is the scalar value that converts the described units into radians**.

`wkt.js` should be updated to take into account the context, using the correct conversion factor of `wkt.UNIT.convert * a` for GEOGCS (Where a is the earth radius as obtained from the DATUM).

**Comment by calvinmetcalf** [comment]
wouldn't this depend on the datum ?

**Comment by tbarsballe** [comment]
Yes, it would, thanks. I have updated the issue description and the PR accordingly.

**Comment by ahocevar** [comment]
Ok, this will give an approximation which is only accurate when measuring east <-> west at the equator, because a is the semi-major axis. But that's fine I think.
