### ISSUE TITLE
Projection anomaly between function vs string projection definition

### ISSUE THREAD

**Issue by JWGmeligMeyling** [proj4js/proj4js#158]
We recently switched our definitions from the first to the second format, because OpenLayers threw exceptions on the first one.

The used definitions:
Old:
```js
proj4.defs["EPSG:28992"] = "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs";
```

New:
```js
proj4.defs("EPSG:28992", "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000  +ellps=bessel  +towgs84=565.040,49.910,465.840,-0.40939,0.35971,-1.86849,4.0772 +units=m +no_defs")
```

Strange enough, the latter one does correctly transform points. Our points seem to be misaligned, and not by a specific offset, they seem to be just wrong positioned at all. We think this is due to the `towgs84` property. Question now is,  how is the first format parsed/ handled differently than the second one? What are the differences? (I am using the same code and newest version of proj4js in both occasions).

Is this maybe related to https://github.com/proj4js/proj4js/pull/119 ?

**Comment by ahocevar** [comment]
Can you please provide a test case, or post a coordinate with its expected transformed result so I can reproduce the issue? Thanks.

**Comment by JWGmeligMeyling** [comment]
Working on it, might take a while as I will put some effort to isolate the problem.

**Comment by JWGmeligMeyling** [comment]
Example output:
```js

```js
// Definition using string
proj4.defs["EPSG:28992_3D"] = "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs";
// Definition using function
proj4.defs("EPSG:28992", "+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.417,50.3319,465.552,-0.398957,0.343988,-1.8774,4.0725 +units=m +no_defs");
```

Then running the first point returns equal output:
```js
// First point
var point = [499707.37328475673, 6783388.5897289775];
proj4(proj4.defs('EPSG:3857'), proj4.defs("EPSG:28992_3D"), point);
// returns  [93188.67269723299, 435808.44090788555]
proj4(proj4.defs('EPSG:3857'), proj4.defs("EPSG:28992"), point);
// returns [93161.63016413446, 435797.167192463]   <-- not equal
```

**Comment by ahocevar** [comment]
I just tried your code with the latest version (2.3.12), and both flavours return exactly the same result:
```js
// [93188.67269723299, 435808.4409078859]
```
Are you sure you are using the latest version?

**Comment by JWGmeligMeyling** [comment]
Ah I see now. It literally took me and my college hours to find this out... But I am a bit ashamed now. `proj4.version` correctly returned `2.3.12`. And we we're assuming we correctly loaded `2.3.12`. Turns out we still had some old code importing the `2.2.1` shipped with Potree...
