### ISSUE TITLE
Question - Convert projection?

### ISSUE THREAD

**Issue by dud3** [proj4js/proj4js#160]
Hi Guys, hopefully asking a question on github issues is OK with you. :)
## Problem space

I have the following data:

``` js
    Name: "Bowen Island Marina"
    Location: "Bowen Island"
  ["geometry"]=>
    ["coordinates"]=>
    array(2) {
      [0]=>
      float(1193901.8186779)
      [1]=>
      float(488507.3330893)
    }
}
```

I wanted to convert the following 1193901.8186779, 488507.3330893 into `lat/lng`, but unfortenatelly I don't know which projection? does the numbers above belong to ?
## My Approach

Since I don't know which projection it was, I've tried the following:

``` js
var firstProjection = 'PROJCS["NAD83 / Massachusetts Mainland",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",42.68333333333333],PARAMETER["standard_parallel_2",41.71666666666667],PARAMETER["latitude_of_origin",41],PARAMETER["central_meridian",-71.5],PARAMETER["false_easting",200000],PARAMETER["false_northing",750000],AUTHORITY["EPSG","26986"],AXIS["X",EAST],AXIS["Y",NORTH]]';

proj4(secondProjection,firstProjection).inverse([2,5]);
// Got: -60.171248261374096, 38.05275335652267
```

The result was close to Antartica, but `Bowen Island Marina` belongs to Canada.
## Question

Can someone please guide guide me or give me an example of this library solving this problem ?

I've imported this from a: <a href='https://drive.google.com/file/d/0B_L84YHKHxXKamcxRnVNM1BQLUE/view?usp=sharing'>GIS file</a>

Thanks.

**Comment by dud3** [comment]
Found the following as well, if that helps:
```js
PROJCS[
  "NAD_1983_BC_Environment_Albers",
  GEOGCS["GCS_North_American_1983",
  DATUM[
    "D_North_American_1983",
    SPHEROID["GRS_1980",6378137.0,298.257222101]
  ],
  PRIMEM["Greenwich",0.0],
    UNIT["Degree",0.0174532925199433]
  ],
  PROJECTION["Albers"],
  PARAMETER["False_Easting",1000000.0],
  PARAMETER["False_Northing",0.0],
  PARAMETER["Central_Meridian",-126.0],
  PARAMETER["Standard_Parallel_1",50.0],
  PARAMETER["Standard_Parallel_2",58.5],
  PARAMETER["Latitude_Of_Origin",45.0],
  UNIT["Meter",1.0]
]
```

**Comment by dud3** [comment]
I think the my last comment explains the projection, I got: `[-123.33109763659209, 49.380000384396745]` which is the right location.

Can someone than tell me the formula of conversion, so I could apply on other programming languages ?

Thanks a lot.

**Comment by calvinmetcalf** [comment]
[wikipedia article about the albers projection](https://en.wikipedia.org/wiki/Albers_projection)
