### ISSUE TITLE
Error thrown for Robinson projection (ESRI:54030)

### ISSUE THREAD

**Issue by patrickarlt** [proj4js/proj4js#161]
I've been attempting to use this [tiled map service)[http://tiles.arcgis.com/tiles/BG6nSlhZSAWtExvp/arcgis/rest/services/coordsys_robinson/MapServer?f=pjson] with Proj4Leaflet and Esri Leaflet but proj4js is throwing an error when it tries to initialize the projection.

I've tried defining the projection a few ways from proj4 codes spatialreference.org, using `gdalsrsinfo` and even trying the WKT directly but they all result in proj4js throwing an error.

```js
// proj4js def from http://spatialreference.org/ref/esri/54030/proj4js/
proj4.defs('ESRI:54030', '+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +datum=WGS84 +units=m +no_defs');

proj4('WGS84', 'ESRI:54030', [0,0]);

// Uncaught ESRI:54030
```

```js
// proj4js def from running `gdalsrsinfo PROJCS["World_Robinson",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Robinson"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],UNIT["Meter",1.0],AUTHORITY["ESRI",54030]]`
// which is the projection defined in the tile serivce
proj4.defs('ESRI:54030', '+proj=robin +lon_0=0 +x_0=0 +y_0=0 +ellps=WGS84 +units=m +no_defs');

proj4('WGS84', 'ESRI:54030', [0,0]);

// Uncaught ESRI:54030
```

```js
// just trying the WKT definition directly.
proj4.defs('ESRI:54030', 'PROJCS["World_Robinson",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984",SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Robinson"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],UNIT["Meter",1.0],AUTHORITY["ESRI",54030]]');

proj4('WGS84', 'ESRI:54030', [0,0]);

// Uncaught ESRI:54030
```

**Comment by calvinmetcalf** [comment]
robinson is not a supported projection (unless it has a weird other name).  It probably wouldn't be *that* hard to add it,

**Comment by patrickarlt** [comment]
@calvinmetcalf Cool that is kinda what I expected. Is there a list of supported projections anywhere that I have missed? Or is it just what is in https://github.com/proj4js/proj4js/tree/master/lib/projections?

**Comment by calvinmetcalf** [comment]
it's what's in there

**Comment by patrickarlt** [comment]
Ok thanks for clarifying this so quick.

**Comment by PBrockmann** [comment]
I would like to reopen this issue for adding Robinson or Natural Earth projections to proj4js.
That would be really useful for all the climate studies where those projections are promoted as the standard ways to represent global maps.

 As read from http://www.shadedrelief.com/NE_proj/code.html	
"The Natural Earth projection is now included in the PROJ.4 cartographic projections library."
It can be found indeed  from proj.4/src/PJ_natearth.c

Proj4js is said as a port of PROJ.4
However, I don't understand how linked are the 2 codes PROJ.4 and Proj4js ?
Any help welcome on this issue.
