### ISSUE TITLE
Error when running npm install

### ISSUE THREAD

**Issue by cedrikv** [proj4js/proj4js#163]
There is a problem with a dependency:
npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six

**Comment by calvinmetcalf** [comment]
confirmed, looks like esprima-six was unplublished, now just to figure out
what required it...

**Comment by cedrikv** [comment]
if think browserify, the dependency refers to an old version.

**Comment by ahocevar** [comment]
I cannot reproduce this issue. Are you guys still running into this? If not, then please close.

**Comment by cedrikv** [comment]
I still have the error, I just tried with a clean install. 
I do git clone into an empty dir and run npm install in that dir. This is the error:
```
npm ERR! Linux 4.2.0-27-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v0.12.9
npm ERR! npm  v2.14.9
npm ERR! code E404

npm ERR! 404 Registry returned 404 for GET on https://registry.npmjs.org/esprima-six
npm ERR! 404 
npm ERR! 404 'esprima-six' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 It was specified as a dependency of 'syntax-error'
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/cedrik/tests/proj4/proj4js/npm-debug.log
```
I'm working on ubuntu 15.10

**Comment by ahocevar** [comment]
@cedrikv Can you try if you still run into the issue after applying #171?

**Comment by cedrikv** [comment]
Ok, #171 fixes this

**Comment by cedrikv** [comment]
probably the update of browserify
