### ISSUE TITLE
proj4js return [NaN, NaN]

### ISSUE THREAD

**Issue by dzNavitski** [proj4js/proj4js#164]
Is it mistake in projection or proj4js does something wrong?

proj4('+proj=stere +lat_0=90 +lat_ts=90 +lon_0=5 +datum=WGS84 +units=m +no_defs', [108.80, 32.08])

return [NaN, NaN]

**Comment by calvinmetcalf** [comment]
what projection are you attempting to use ?

**Comment by dzNavitski** [comment]
I want to use Polar Stereographic

**Comment by calvinmetcalf** [comment]
Can you be more specific about the proj string you are using?

**Comment by dzNavitski** [comment]
Hi. I use openlayers with projection EPSG:4326. 
In old application (flash) was used map with following parameters:
Map fixpoint (geog.): 47 ; 2.5
Projection type: Polar Stereographic
Projection parameter: 5 60
Proj4: +proj=stere +lat_0=90 +lat_ts=90 +lon_0=5 +datum=WGS84 +units=m +no_defs
Corner Coordinates: 
+52.752897 -9.518992 (upper left)
+53.467973 +13.734322 (upper right)
+39.792072 -5.388603 (lower left)
+40.259283 +11.207076 (lower right)

I tried to transform coordinates with this projection and in return i got [NaN, NaN].

**Comment by calvinmetcalf** [comment]
I'm pretty sure +lat_ts=90 should be +lat_ts=75

**Comment by dzNavitski** [comment]
Thank you!
