### ISSUE TITLE
Projection translation is off

### ISSUE THREAD

**Issue by PhiRub** [proj4js/proj4js#166]
On version 2.3.12, I'm getting the following using the defs from epsg.io:

``` javascript
proj4.defs("EPSG:32038","+proj=lcc +lat_1=32.13333333333333 +lat_2=33.96666666666667 +lat_0=31.66666666666667 +lon_0=-97.5 +x_0=609601.2192024384 +y_0=0 +datum=NAD27 +units=us-ft +no_defs");
proj4('EPSG:32038', 'EPSG:4326', [2674439.6, 200323.14]);
// got [-95.31965540972162, 32.19612335846809]
```

When using cs2cs, I'm getting the correct lat/long as verified [from ArcGisOnline](http://tasks.arcgisonline.com/ArcGIS/rest/services/Geometry/GeometryServer/project?inSR=32038&outSR=4326&geometries={%0D%0A%22geometryType%22+%3A+%22esriGeometryPoint%22%2C%0D%0A%22geometries%22+%3A+[%0D%0A+{%22x%22+%3A+2674439.6%2C+%22y%22+%3A+200323.14}%0D%0A]%0D%0A}&f=HTML)

``` javascript
cs2cs +init=epsg:32038 -f "%.6f"
+to +proj=WGS84
2674439.6 200323.14
// got [-95.319655, 32.198055]
```

If this helps track down the issue, replacing `nadgrids:"@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat"` with `towgs84: "-3, 142, 183"` in proj4.js in the definition for nad27 seems to fix the issue (but may cause problems elsewhere).

**Comment by calvinmetcalf** [comment]
I'm not sure this applies anymore
