### ISSUE TITLE
Projection "somerc" returns wrong values

### ISSUE THREAD

**Issue by sebasbaumh** [proj4js/proj4js#168]
I compared the output of proj4js to the one of proj4 because of a slightly wrong coordinate.
Finally I ended up creating this example using a test case from proj4.

* Base coordinate system is WGS84 (`EPSG:4326`).
* Target coordinate system is Switzerland (`EPSG:21781`).
* The definition for `EPSG:21781` was taken from https://github.com/Proj4J/proj4j/blob/master/trunk/src/main/resources/nad/epsg#L5825 .
* The example was taken from https://github.com/Proj4J/proj4j/blob/59ffb9b661b4ec7106b82f57b4861447a0cd1d30/trunk/src/test/java/org/osgeo/proj4j/CoordinateTransformTest.java#L208 .

Example (run it on https://jsfiddle.net/jsz8s4yh/1/ if you like):
```
//definition taken from https://github.com/Proj4J/proj4j/blob/master/trunk/src/main/resources/nad/epsg#L5825
proj4.defs("EPSG:21781","+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 +k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel +towgs84=674.4,15.1,405.3,0,0,0,0 +units=m +no_defs");

//test accoring to https://github.com/Proj4J/proj4j/blob/59ffb9b661b4ec7106b82f57b4861447a0cd1d30/trunk/src/test/java/org/osgeo/proj4j/CoordinateTransformTest.java#L208
var c=proj4("EPSG:4326","EPSG:21781",[8.23,46.82]);
//should be: 660309.34,         185586.30
//is:        660389.4751110513, 185731.6848264886
alert(c);
```

**Comment by ahocevar** [comment]
Using the [official transform functions from swisstopo](http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/software/products/skripts.html), I get `[660389.4914152742, 185731.59031755885]`. So I tend to think that proj4js returns a better result.

Are you sure that the proj4 definition you pasted above is the one that was used for the test case you linked? I noticed that the tests use a very old version of the EPSG database from 2003.

**Comment by sebasbaumh** [comment]
Thank you for the feedback.

I think you are right. When I evaluated the transformation using another one of our software products, it showed the same results as proj4js. And that product is using ProjNet4GeoAPI, which is a .NET-port and has basically nothing to do with proj4js.
So finally it seems the test case of proj4is wrong and I close this issue as it is no defect.
