### ISSUE TITLE
Allow parsing of DMS format projection definition

### ISSUE THREAD

**Issue by sebasbaumh** [proj4js/proj4js#169]
proj4js was unable to parse the following [definition](https://github.com/OSGeo/proj.4/blob/master/nad/world#L4) correctly:
```
<CH1903> # Swiss Coordinate System
	+proj=somerc +lat_0=46d57'8.660"N +lon_0=7d26'22.500"E
	+ellps=bessel +x_0=600000 +y_0=200000
	+k_0=1.  no_defs <>
```

The main reason is that the lat and lon coordinates are written in DMS (Degree Minute Seconds) format instead of fully decimal degrees.

As the above definition is a projection included in the original proj.4 in the [world](https://github.com/OSGeo/proj.4/blob/master/nad/world) file, proj4js should be able to interpret it correctly by parsing the value not as a float, but checking if it is in DMS format and [converting](https://en.wikipedia.org/wiki/Geographic_coordinate_conversion#Coordinate_format_conversion) it if necessary.

**Comment by ahocevar** [comment]
proj4.js does not support projection definitions in world file format. Instead, it supports the definitions in the [epsg](https://github.com/OSGeo/proj.4/blob/master/nad/epsg) file.

**Comment by sebasbaumh** [comment]
Thanks for clarification!
