### ISSUE TITLE
ortho projection not built into dist; not able to build specific projection

### ISSUE THREAD

**Issue by briantjacobs** [proj4js/proj4js#170]
Hi, I tried using this string using the dist/proj4.js
+proj=ortho +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs
and got an "uncaught" error when using in conjunction with proj4leaflet

Looking in dist/proj4-src.js, there's no reference at all to ortho in there, even though its definitely in here
https://github.com/proj4js/proj4js/tree/master/lib/projections

Then i tried to do a grunt build:ortho and got this error
https://github.com/proj4js/proj4js/issues/163

I was able to manually hack in ortho into dist/proj4-src.js, which worked great, but currently there's no way to get the ortho projection given that the project doesnt install.

**Comment by ahocevar** [comment]
With #171 applied, I am able to run `grunt build:ortho`. Can you confirm @briantjacobs?

**Comment by briantjacobs** [comment]
#171 alone didn't work for me, but upgrading browserify and grunt-browserify did do the trick

package.json:
```
    "browserify": "~12.0.1",
    "grunt-browserify": "~4.0.1",
```

thanks for looking into this

**Comment by ahocevar** [comment]
Were you using a standalone grunt-cli, or `node_modules/.bin/grunt`?

**Comment by briantjacobs** [comment]
I think standalone. As in `npm install grunt-cli -g`

**Comment by ahocevar** [comment]
Ok, I'll update the readme then. Thanks for the feedback.

**Comment by briantjacobs** [comment]
Update: when doing `grunt build:ortho` while using those updated versions, it creates files in dist/ that don't expose `proj4` to the browser, unless i'm missing something. So further testing probably needed.

**Comment by ahocevar** [comment]
I just tested with #171 applied on a fresh clone, using `node_modules/.bin/grunt`, and I get `proj4` exposed with both `proj4.js` and `proj4-src.js`.

**Comment by briantjacobs** [comment]
I tried it again with a fresh clone. It wouldn't install without the package.json modification above. Then I ran `node_modules/.bin/grunt build ortho`, which builds the file. I drop that file into a project that previously works with proj4js, then in the browser I get `Uncaught ReferenceError: proj4 is not defined`. Maybe using the newer browserify changed something?

**Comment by ahocevar** [comment]
I can confirm this now after deleting the npm registry. Investigating.

**Comment by ahocevar** [comment]
I updated #171 with your suggested changes, and now everything works as expected. Regarding your finding, I could verify that the build works by creating a minimal html in the `dist/` directory:
```html
<html>
<body>
  <div id="proj4"></div>
  <script src="proj4.js"></script>
  <script>
  document.getElementById('proj4').innerHTML =
      proj4('EPSG:4326', 'EPSG:3857', [16, 48]);
  </script>
</body>
</html>
```
This gives me a web page with the expected result:
```
1781111.852692377,6106854.834885075
```

**Comment by ahocevar** [comment]
@briantjacobs An important hint maybe: If you got the `Uncaught ReferenceError: proj4 is not defined` when running the OpenLayers 3 test suite with your custom build: This comes from `somerc` not being included in the proj4.js build, and from this failing test which removes `proj4` from the global namespace and does not add it back when it fails:
```js
    it('can use an alternative namespace for proj4', function() {
      var proj4 = window.proj4;
      var proj4new = proj4;
      delete window.proj4;
      ol.proj.setProj4(proj4new);
      proj4new.defs('EPSG:21781',
          '+proj=somerc +lat_0=46.95240555555556 +lon_0=7.439583333333333 ' +
          '+k_0=1 +x_0=600000 +y_0=200000 +ellps=bessel ' +
          '+towgs84=674.374,15.056,405.346,0,0,0,0 +units=m +no_defs');
      var proj = ol.proj.get('EPSG:21781');
      expect(proj.getCode()).to.eql('EPSG:21781');
      expect(proj.getUnits()).to.eql('m');
      expect(proj.getMetersPerUnit()).to.eql(1);

      delete proj4new.defs['EPSG:21781'];
      window.proj4 = proj4;
      ol.proj.setProj4(window.proj4);
    });
```
I'm mentioning this because I spent 2 hours investigating what's wrong with the proj4.js build, only to find out that the OpenLayers test suite caused this error.
