### ISSUE TITLE
Wrong projection between WGS84 and GDM2000/Peninsular RSO

### ISSUE THREAD

**Issue by bladegun** [proj4js/proj4js#173]
When converting between WGS84 and GDM2000/Peninsular RSO (EPSG:3375), result from proj4js are very different from the one produced by cs2cs or PostGIS.

Here is my code:

``` javascript
proj4.defs('EPSG:3375', '+proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257964666666 +k=0.99984 +x_0=804671 +y_0=0 +no_uoff +gamma=323.1301023611111 +ellps=GRS80 +units=m +no_defs');

var c = proj4('EPSG:3375', 'EPSG:4326').forward([410042.053264524, 340750.457263734]);
// c is [98.6785691176469, 7.071110215716101]
```

With cs2cs:

```
cs2cs +proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257964666666 +k=0.99984 +x_0=804671 +y_0=0 +no_uoff +gamma=323.1301023611111 +ellps=GRS80 +units=m +no_defs +to +proj=longlat +datum=WGS84 +no_defs
410042.053264524 340750.457263734
101d41'12.348"E 3d4'44.25"N 0.000
```

With PostGIS 2.2:

``` SQL
SELECT ST_AsText(ST_Transform(ST_SetSRID(ST_MakePoint(410042.053264524, 340750.457263734), 3375), 4326))
```

I get `POINT(101.6867634 3.07895829999971)`. This matches the result from cs2cs.

It seems proj4js is having problem converting omerc projection. Is this a bug or something is wrong in the proj4 definition string?

**Comment by calvinmetcalf** [comment]
did you intend to close this ?

**Comment by bladegun** [comment]
Yes.

**Comment by jratike80** [comment]
Why did you close the issue? Did you find that you did something wrong, does the issue not happen any  more or what? Other users have similar problems.

**Comment by bladegun** [comment]
Initially I thought that the wrong conversion was caused by a bug. Then, I found out that it was not possible to implement such a conversion in a JavaScript library. So, I closed this issue.
