### ISSUE TITLE
repeated projection useage mutates datum def

### ISSUE THREAD

**Issue by krzbor** [proj4js/proj4js#175]
If you call several times "proj4()":

proj4('EPSG:3857','EPSG:2175');
proj4('EPSG:102113','EPSG:2175');
proj4('EPSG:900913','EPSG:2175');

will be repeatedly invoked the code:

proj.datum_params[3] *= SEC_TO_RAD;
proj.datum_params[4] *= SEC_TO_RAD;
proj.datum_params[5] *= SEC_TO_RAD;
proj.datum_params[6] = (proj.datum_params[6] / 1000000.0) + 1.0;

This will destroy the parameters towgs84 [3,4,5,6]

I solved the problem by adding:

if (typeof proj.was_convert == 'undefined'){
  proj.datum_params[3] *= SEC_TO_RAD;
  proj.datum_params[4] *= SEC_TO_RAD;
  proj.datum_params[5] *= SEC_TO_RAD;
  proj.datum_params[6] = (proj.datum_params[6] / 1000000.0) + 1.0;
  proj.was_convert=true;
}

However, this is not very elegant solution.

**Comment by ahocevar** [comment]
@krzbor Are you sure you are using the latest version? This should have been fixed with #155 in v2.3.12.

**Comment by krzbor** [comment]
I downloaded the zip file from the https://github.com/proj4js/proj4js (Download ZIP button). I use proj4.js from the folder dist.

**Comment by ahocevar** [comment]
You should be downloading from the [releases page](https://github.com/proj4js/proj4js/releases).

**Comment by krzbor** [comment]
Thank you very much. But I think you should publish the latest version on the main page of the project.

**Comment by ahocevar** [comment]
It is not really good to have dist files in the source repo. So I created #176 and #177 to remove the dist files from master and remove the download buttons.

**Comment by ahocevar** [comment]
@calvinmetcalf, do you think #176 and #177 make sense?

**Comment by calvinmetcalf** [comment]
yes that makes sense

**Comment by ahocevar** [comment]
Thanks @calvinmetcalf.
