### ISSUE TITLE
Discrepancies between Proj4 and Proj4Js - ED50 -> WGS84

### ISSUE THREAD

**Issue by ClemRz** [proj4js/proj4js#181]
Hi,

I'm having an issue with the Proj4Js library, I'm seeing some discrepancies for the transformation between ED50 and WGS84:

Proj4 `4.9.2` (OSX command line):
```zsh
➜  bin ./cs2cs -f '%.7f' +proj=longlat +ellps=intl +no_defs +to +proj=longlat +ellps=WGS84 +datum=WGS84
21 18
21.0000000	18.0000000 0.0000000
```

Proj4Js `2.2.1` & `2.3.13-alpha` (Chrome console):
```JavaScript
proj4(new proj4.Proj('+proj=longlat +ellps=intl +no_defs'), new proj4.Proj('+proj=longlat +ellps=WGS84 +datum=WGS84'), [21, 18]);
[21, 17.99951610821285]
```

There is a difference between the resulting latitudes: `18.0000000` in one hand and `17.99951610821285` in the other.
Does anyone experience the same issue please?

Thanks.

**Comment by calvinmetcalf** [comment]
issue with floating point arithmetic ?

**Comment by ClemRz** [comment]
Yea, as @calvinmetcalf mentioned, this is due to floating point arithmetic (HALF_PI, D2R, R2D, the sines and cosines storage etc.). JavaScript is definitely not a good option for arithmetics... I'm looking into migrating to another language.

Thanks!

**Comment by Harelebel** [comment]
Hi, how to convert from ED50 to WSG84 ? 
The bellow give me bad result ([79.34262031843741, 0]) , my desired result is [34.793890 , 32.130109], 

proj4(new proj4.Proj('+proj=longlat +ellps=intl +no_defs'), new proj4.Proj('+proj=longlat +ellps=WGS84 +datum=WGS84'), [669257.722015602, 3556445.24116905]);

**Comment by calvinmetcalf** [comment]
@Harelebel you are converting between 2 different types of lat longs but your input data  `669257.722015602, 3556445.24116905`  is not a lat lon

**Comment by Harelebel** [comment]
@calvinmetcalf ok so how I should convert ? can u plz give an example ?

**Comment by calvinmetcalf** [comment]
this def `'+proj=longlat +ellps=intl +no_defs'` is not what you want you need to find the correct one that goes with your data and thats something I can't really help you with
