### ISSUE TITLE
Latitude Longitude pair convert to GeoJSON

### ISSUE THREAD

**Issue by m-menon** [proj4js/proj4js#182]
hi, is there an example as to how to convert a latitude and longitude pair to GeoJSON? Thanks

**Comment by calvinmetcalf** [comment]
you mean how to turn a latlng pair into something like this?

```json
{
  "type": "Feature",
  "geometry": {
    "type": "Point",
    "coordinates": [125.6, 10.1]
  },
  "properties": {
    "name": "Dinagat Islands"
  }
```

**Comment by m-menon** [comment]
yup, exactly

**Comment by calvinmetcalf** [comment]
yes JSON.Stringify should do the trick

**Comment by m-menon** [comment]
Alrighty....thanks a lot for the clarification :+1:
