### ISSUE TITLE
NAD 1983 Michigan GeoRef Meters incorrect projection (?)

### ISSUE THREAD

**Issue by rozap** [proj4js/proj4js#183]
Hi, 

I've been using proj4 and it has been great, but I ran into this issue and I don't know if I'm doing something stupid or if this is a bug. 

I have the following projection, which is a Michigan projection
`+proj=omerc +lat_0=45.30916666666666 +lonc=-86 +alpha=337.255555555556 +k=0.9996 +x_0=2546731.496 +y_0=-4354009.816 +no_uoff +datum=NAD83 +units=m +no_defs`

And a sample point, which comes from a shapefile
`[537293.9851999991, 560334.9651999995]`

When I project to WGS84, I'd expect it to be in Michigan somewhere, but it ends up in the arctic ocean. I see in the readme some examples where `+units=m` so I would expect this to work. 

Here's a bit of js which can replicate it

``` javascript
var proj = require('proj4');
var from = '+proj=omerc +lat_0=45.30916666666666 +lonc=-86 +alpha=337.255555555556 +k=0.9996 +x_0=2546731.496 +y_0=-4354009.816 +no_uoff +datum=NAD83 +units=m +no_defs';
var to = '+proj=longlat +datum=WGS84 +no_defs';
var result = proj(from, to, [537293.9851999991, 560334.9651999995]);
// result is [ -178.58814648047502, 73.79986685191143 ]
```

And here's the correction projection on epsg.io
https://epsg.io/transform#s_srs=102123&t_srs=4326&x=537293.9771936&y=560334.9539703

Maybe I'm doing something stupid? But the library has worked well so far :confused:

**Comment by calvinmetcalf** [comment]
Is this Michigan state plane? If so shouldn't it be tmerc not omerc

**Comment by rozap** [comment]
No it looks like it's an alternative to state plane which is oblique mercator.

```What is the Michigan GeoRef Coordinate System?
Michigan GeoRef is an alternative to the State Plane Coordinate System. But, unlike Michigan State Plane,
GeoRef was designed to project the State using a single zone rather than three zones.
```
Taken from [here](http://www.michigan.gov/documents/DNR_Map_Proj_and_MI_Georef_Info_20889_7.pdf)

**Comment by calvinmetcalf** [comment]
what happens if you use the proj string from espt.io? `+proj=omerc +lat_0=45.30916666666666 +lonc=-86 +alpha=337.255555555556 +k=0.9996 +x_0=2546731.496 +y_0=-4354009.816 +ellps=GRS80 +datum=NAD83 +units=m no_defs`

**Comment by rozap** [comment]
That looks like it's the same projection I had in the example. Just tried it again and I still end up in the arctic ocean.

**Comment by rozap** [comment]
Just saw that there's a special build step for `omerc`. If installed through `npm` will the `omerc` projections be included?

**Comment by calvinmetcalf** [comment]
Yes it should be installed by default and throw an error if it were not
