### ISSUE TITLE
ortho not in default build

### ISSUE THREAD

**Issue by nebain** [proj4js/proj4js#185]
Hi, when I attempt to use the ortho projection in 2.3.14, I get an "uncaught" error. I'm attempting to use the same projection as what is mentioned in #170 - that is +proj=ortho +lat_0=90 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs .

I see that ortho was not added to the projs array in Gruntfile.js following the resolution of #170 - is this the reason? If I add 'ortho' to the projs array, then I can generate a custom build without errors. However, I'm apparently missing a step, because any custom build that I create (even using the defaults) results in a proj4-src.js file that, when loaded in a browser, doesn't actually define proj4 (I'm new to building my own js-related stuff).

**Comment by ahocevar** [comment]
I can confirm this issue on a fresh clone. The full build also fails. Maybe a new incompatibility of npm packages. Maybe we should use fixed versions for `devDependencies` in our `package.json`, and maybe use Greenkeeper to stay up to date and see when something breaks.
