### ISSUE TITLE
Math.tan may return "Infinity", failing to project in older browsers (Chrome 37, OSX 10.6.8)

### ISSUE THREAD

**Issue by tmfrnz** [proj4js/proj4js#189]
While testing a leaflet application with a polar stereographic projection (EPSG:5937) on Chrome 37/iOSX 10.6.8, the Gauss.js function would fail to project.

`this.K` was assigned `NaN` as both `Math.tan(0.5 * this.phic0 + FORTPI)` as `Math.tan(0.5 * this.lat0 + FORTPI)` returned `Infinity`
https://github.com/proj4js/proj4js/blob/93a3376307ddd81ed3fd26161bcbe6749cce3d8c/lib/projections/gauss.js#L13

Working workaround for now is checking for `Infinity` and replacing it with `Number.MAX_VALUE`, eg

```
  var mtan1 = Math.tan(0.5 * this.phic0 + FORTPI)
  var mtan2 = Math.tan(0.5 * this.lat0 + FORTPI)
  mtan1 = mtan1 !== Number.POSITIVE_INFINITY ? mtan1 : Number.MAX_VALUE
  mtan2 = mtan2 !== Number.POSITIVE_INFINITY ? mtan2 : Number.MAX_VALUE
  this.K = mtan1 / (Math.pow(mtan2, this.C) * srat(this.e * sphi, this.ratexp));
```

Related to
https://github.com/proj4js/proj4js/issues/121

**Comment by calvinmetcalf** [comment]
pull requests accepted
