### ISSUE TITLE
Adding projections (Robinson, Natural Earth) available from PROJ.4

### ISSUE THREAD

**Issue by PBrockmann** [proj4js/proj4js#191]
I would like to open this issue for adding Robinson or Natural Earth projections to proj4js.
That would be really useful for all the climate studies (IPCC reports) where those projections are promoted as the standard ways to represent global maps.

As read from http://www.shadedrelief.com/NE_proj/code.html
"The Natural Earth projection is now included in the PROJ.4 cartographic projections library."
It can be found indeed from https://github.com/OSGeo/proj.4/blob/master/src/PJ_natearth.c and commented from https://github.com/OSGeo/proj.4/wiki/NaturalEarth

Proj4js is described as a port of PROJ.4
However, I don't understand how linked are the 2 codes ?
Any help welcome on this issue.

**Comment by calvinmetcalf** [comment]
it was forked (past tense) and painstakingly converted to JS, Natural Earth is a possibility to be added, though we'd not just need to add the projection function, we'd also need to know how it was specified with wkt files and proj strings.  

Robinson on the other hand from a quick peruse through the internet isn't actually rigorously defined for all points so that one is probably a no go.

**Comment by PBrockmann** [comment]
I would have say the reverse.
Coordinate reference systems for Robinson projection are well defined from:
http://spatialreference.org/ref/esri/54030/prettywkt/ or http://epsg.io/54030
Not for the Natural Earth projection but however already implemented in proj.4

**Comment by calvinmetcalf** [comment]
If I was to impliment I'd probably do so as a seperate module that if
needed could be pulled into this one.

Is there a spec you know of?

**Comment by mbloch** [comment]
What about porting the Robinson implementation from Proj.4 (https://github.com/OSGeo/proj.4/blob/master/src/PJ_robin.c), is there a reason not to do that?

**Comment by bhaskarvk** [comment]
+1 for Robinson and Natural Earth and Winkel Triple projections support.

**Comment by calvinmetcalf** [comment]
pull requests accepted on these checkout #244 for examples of how
