### ISSUE TITLE
Problems with converting height?

### ISSUE THREAD

**Issue by mramato** [proj4js/proj4js#192]
I apologize if this is a noob question or not the best place to ask, but I'm still wet behind the ears when it comes to projections in general.

I have the below code snippet:

``` javascript
proj4.defs([
    [
        'EPSG:2263',
        '+proj=lcc +lat_1=41.03333333333333 +lat_2=40.66666666666666 +lat_0=40.16666666666666 +lon_0=-74 +x_0=300000.0000000001 +y_0=0 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs'
    ]
]);

var input = [ 1052812.80151057, 157368.752569735, 133.714600000007 ];
var output = proj4('EPSG:2263', 'EPSG:4326', input);
```

I expect output to be `[ -73.75310765297571, 40.59835188701021, 40.75621008000214 ]`, but z is `133.714600000007` instead (same as input, unmodified).  It looks like `+to_meter=0.3048006096012192` in the projection is not being applied.  The projection came straight from http://spatialreference.org/ref/epsg/nad83-new-york-long-island-ftus/proj4js/, so I assume it's correct.

What am I doing wrong?  Any help would be greatly appreciated.

**Comment by calvinmetcalf** [comment]
height is not supported

**Comment by mramato** [comment]
That is unfortunate.  Are there any long term plans to support height?  If not would you be willing to look at a PR that adds it? (Not signing up to do it just yet, but wanted to gauge interest).

**Comment by calvinmetcalf** [comment]
I'm not sure anyone would necessarily be against it

**Comment by ahocevar** [comment]
Not against it, if height conversion is opt-in. Because the 3rd coordinate may mean different things than height.
