### ISSUE TITLE
Lambert 2 étendu (extendu) to latitude/longitude (WGS84)?

### ISSUE THREAD

**Issue by bzg** [proj4js/proj4js#194]
HI @ahocevar,

thank you for this tool -- this is more a call for help from a newbie rather than a proper issue, so thanks in advance for your time.

I have several "Lambert 2 étendu" (extended Lambert 2) X,Y coordinates that I need to convert to WGS84 (latitude/longitude).  I'm new to this and I cannot grok many of the notions that I read in the various documentations, starting from the official french geographical documentation about Lambert 2 (see [this PDF](http://geodesie.ign.fr/contenu/fichiers/documentation/pedagogiques/TransformationsCoordonneesGeodesiques.pdf)).

How would you achieve this woth proj4js?

I tried this:

```
<script src="proj4.js"></script>
<script>
proj4("Lambert_Conformal_Conic_2SP","WGS84",[1007135.180,2422176.950]);
</script>
```

expecting "Lambert_Conformal_Conic_2SP" to refer to "Lambert 2 étendu" (half shooting in the darkness).

My JS console stays mute.

What should I change to get the correct result, preferrably as a string?

Thanks!

**Comment by ahocevar** [comment]
You'll need to supply a projection definition, either in proj.4 or WKT format. The ones I found doing a quick web search were
```
+proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742 +x_0=600000 +y_0=2200000 +a=6378249.2 +b=6356515 +towgs84=-168,-60,320,0,0,0,0 +pm=paris +units=m +no_defs
```
and
```
PROJCS["NTF_Lambert_II_etendu",GEOGCS["GCS_NTF",DATUM["D_NTF",SPHEROID["Clarke_1880_IGN",6378249.2,293.46602]],PRIMEM["Greenwich",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Lambert_Conformal_Conic"],PARAMETER["False_Easting",600000.0],PARAMETER["False_Northing",2200000.0],PARAMETER["Central_Meridian",2.3372291667],PARAMETER["Standard_Parallel_1",45.8989188889],PARAMETER["Standard_Parallel_2",47.6960144444],PARAMETER["Scale_Factor",1.0],PARAMETER["Latitude_Of_Origin",46.8],UNIT["Meter",1.0]]
```
I think the former is more accurate, because it includes parameters for a datum transform.

Now to transform from that projection to WGS84, you can register the projection definition with its EPSG code:
```js
proj4.defs("EPSG:27572","+proj=lcc +lat_1=46.8 +lat_0=46.8 +lon_0=0 +k_0=0.99987742 +x_0=600000 +y_0=2200000 +a=6378249.2 +b=6356515 +towgs84=-168,-60,320,0,0,0,0 +pm=paris +units=m +no_defs");
```
From now on, you can transform with
```js
proj4('EPSG:27572', 'WGS84', [1007135.180,2422176.950]);
```
proj4 will always return an array of two coordinates (`[longitude, latitude]`), which you can format to a string using plain javascript or a 3rd party library.

**Comment by bzg** [comment]
Thanks a lot!  It works like a charm.
