### ISSUE TITLE
Doesn't handle minutes format in lon_0 attribute

### ISSUE THREAD

**Issue by goatchurchprime** [proj4js/proj4js#197]
The following string is not being recognized

jj = "+proj=tmerc +lat_0=0 +lon_0=13d20 +k=1 +x_0=0 +y_0=-5200000 +ellps=bessel +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232"

proj4(jj, "WGS84", [36670.37, 83317.43])  ==> [Nan, Nan]

It works if I use lon_0=13.33333333 instead

I can confirm this behavior by using the equivalent library in python, like so:

import pyproj
print(pyproj.Proj(jj)(36670.37, 83317.43, inverse=True))
    ==> (13.8218485484612, 47.688028120974295)

**Comment by calvinmetcalf** [comment]
that is correctly this library doesn't support that, pull requests accepted
