### ISSUE TITLE
Using Autodesk/Mapguide Generated WKT for Counties doesn't parse

### ISSUE THREAD

**Issue by flipper44** [proj4js/proj4js#198]
This is a Coordinate System WKT that My Mapguide map has defined and that it is sending into proj4js
PROJCS["HARN/WI.FlorenceWI-F",
	GEOGCS["HARN/WI.LL",
	DATUM["HARN/WI",
	SPHEROID["GRS1980",6378137.000,298.25722210],
	TOWGS84[0.0000,0.0000,0.0000,0.000000,0.000000,0.000000,0.00000000]],
	PRIMEM["Greenwich",0],
	UNIT["Degree",0.017453292519943295]],
	PROJECTION["Transverse Mercator, Wisconsin County Variation"],
	PARAMETER["false_easting",438000.000],
	PARAMETER["false_northing",0.000],
	PARAMETER["scale_factor",0.999993500000],
	PARAMETER["central_meridian",-88.14166666670000],
	PARAMETER["latitude_of_origin",45.43888888890000],
	PARAMETER["Average Geoid Height (meters)",-32.8700],
	PARAMETER["Average Elevation (system unit)",1400.0000],
	UNIT["Foot_US",0.30480060960122]]
This Crashes when Being Parsed...I am not sure what causes the crash, if it is the Projection or what it is exactly that is causing this. 
IF I override Mapguide to Send the projection on the bottom of this message it will take it but Mapguide Doesn't really like this at all for other layers that require reprojections. The problem I have found is that this is the case for Every Minnesota and Wisconsin County Coordinate System. If someone could find out what Part of the Above System is Unreadable or un Parseable by proj4js It would go a long way into figuring out where I need to add Projection or Datum parameters in either Mapguide or in proj4js to better handle this (WKT is not my strong suit)
PROJCS["NAD_1983_HARN_Adj_WI_Florence_Feet",
GEOGCS["GCS_NAD_1983_HARN_Adj_WI_Florence",
	DATUM["D_NAD_1983_HARN_Adj_WI_FN",
		SPHEROID["GRS_1980_Adj_WI_FN",6378530.851,298.275639532334]],
	PRIMEM["Greenwich",0.0],
	UNIT["Degree",0.0174532925199433]],
	PROJECTION["Transverse_Mercator"],
	PARAMETER["False_Easting",438000.0],
	PARAMETER["False_Northing",0.0],
	PARAMETER["Central_Meridian",-88.14166666666668],
	PARAMETER["Scale_Factor",0.999993],
	PARAMETER["Latitude_Of_Origin",45.43888888888888],
	UNIT["Foot_US",0.3048006096012192]]

**Comment by flipper44** [comment]
I was able to get around this by Replacing the WKT Projection Part like so:
Wkt = Wkt.replace('Transverse Mercator, Wisconsin County Variation', 'Transverse Mercator');
Wkt = Wkt.replace('Lambert Conformal Conic, Wisconsin County Variation', 'Lambert_Conformal_Conic');
Wkt = Wkt.replace('Transverse Mercator, Minnesota DOT Variation', 'Transverse Mercator');
Wkt = Wkt.replace('Lambert Conformal Conic, Minnesota DOT Variation', 'Lambert_Conformal_Conic');
I am pretty sure this is not the appropriate solution and is probably not Projecting 100% accurate, in initial inspection if it is off it is not off by much.
Below a link  describing what Makes County Coordinate systems Different in Wisconsin, so My question is whether I am Accurately Reprojecting by my method, if so could proj4js be made to recognize the Mapguide version so code override doesn't need to Happen? If not can proj4js include these projections?

http://www.sco.wisc.edu/images/stories/publications/WisCoordRefSys_June2015.pdf
[(http://www.sco.wisc.edu/images/stories/publications/WisCoordRefSys_June2015.pdf)]

**Comment by calvinmetcalf** [comment]
so from what I can tell, Autodesk/Mapguide is spitting out a nonstandard wkt file, so for instance from that pdf there is nothing it says that suggested Wisconsin is at all tweaking the Transverse Mercator formula (specifically the page on the Wisconsin Transverse Mercator projection seems to explicitly say it's just Universal Transverse Mercator with different parameters) and is instead just using it's specific parameters, so it's unclear why the projection is listed as a 'variation', same with the datum which looks to be a non-standard name for a standard thing, it may end up being an easy enough fix of adding some aliases for some of these names, though it could be autodesk or mapguide producing an invalid projection file

**Comment by flipper44** [comment]
Something Seems to be off..I found new data for Outagamie County Wisconsin.
Sending the Mapguide wkt in with the Wkt = Wkt.replace('Transverse Mercator, Wisconsin County Variation', 'Transverse Mercator'); Causes the map to be off in Openlayers (aligned with Bing). If I use:
Model.RuntimeMap[0].CoordinateSystem.Wkt = 'PROJCS["NAD_1983_HARN_Adj_WI_Outagamie_Feet", GEOGCS["GCS_NAD_1983_HARN_Adj_WI_Outagamie", DATUM["D_NAD_1983_HARN_Adj_WI_CL_FL_OG_WN", SPHEROID["GRS_1980_Adj_WI_CL_FL_OG_WN", 6378345.09, 298.266952895494]], PRIMEM["Greenwich", 0.0], UNIT["Degree", 0.0174532925199433]], PROJECTION["Transverse_Mercator"], PARAMETER["False_Easting", 803000.0], PARAMETER["False_Northing", 0.0], PARAMETER["Central_Meridian", -88.5], PARAMETER["Scale_Factor", 0.999996], PARAMETER["Latitude_Of_Origin", 42.71944444444445], UNIT["Foot_US", 0.3048006096012192]]';
Which I found on the internet Everything aligns perfectly with BING.
If I leave my Mapguide layers using the Mapguide County Coordinate system, and project them in the map to Spherical Mercator they align (so mapguide handles using its own Projection correctly just not proj4js and openlayers)...this is ODD...I am digging to see if there is a difference of some sort

**Comment by flipper44** [comment]
Looking deeper I see that the Spheroid is different by 393.851 between the 2,
The Stated Geoid Avg is -32.87 m in Mapguide
The stated AVG elevation is (426.72 M) or 1400 Ft.
If I add the 426.72 to -32.87 I get my Geoid Difference..This Doesn't help Proj4js Recognize it, but it is what is creating the issue in my best guess. I have no clue if proj4js takes these two tags into PARAMETER["Average Geoid Height (meters)",-32.8700],
PARAMETER["Average Elevation (system unit)",1400.0000],consideration at all?

**Comment by mbloch** [comment]
I think that part of the confusion here is that Wisconsin has two different sets of county-level coordinate systems, WCCS and WISCRS.

WCCS uses two additional non-standard parameters. The non-parsing WKT definition belongs to WCCS. You can see the extra parameters in the definition -- they're named "Average Geoid Height (meters)" and "Average Elevation (system unit)".

WISCRS was designed as a replacement for WCCS, and uses only standard parameters. The two systems are compatible (they're supposed to deviate horizontally by at most 5 millimeters), so you should be able to replace a WCCS definition with the corresponding WISCRS definition.

This document explains the relationship between WCCS and WISCRS:
http://www.sco.wisc.edu/images/stories/topics/coordsys/WISCRS_Final_Report_Oct06.pdf

I think that Minnesota is similar to Wisconsin -- there is a "Minnesota County Coordinate System" that uses extra parameters, and a set of drop-in replacements using only standard parameters.

**Comment by calvinmetcalf** [comment]
so proj4js doesn't actually do anything with elevation so that's not it, it's almost definitely the spheriod being different, or the latitude_of_origin being different or the Central_Meridian being different or the False_Easting being really different, basically they are different projections, the one that worked and the one that autodesk gave you

**Comment by flipper44** [comment]
Technically elevation can be seen as a part of geoid or circumstance of earth at that location..that's likely why it adds up exactly

**Comment by calvinmetcalf** [comment]
yes it could, but we don't use it in this library

**Comment by flipper44** [comment]
I get that, this can likely be closed I will use the prior link an attempt a change request vie mapguide open source

**Comment by mbloch** [comment]
I understand why @flipper44 got incorrect output by changing "Transverse Mercator, Wisconsin County Variation" to "Transverse Mercator," and got correct output when he used a definition with strange-looking spheroid parameters:

* You can't just treat "Transverse Mercator, Wisconsin County Variation" as an alias of "Transverse Mercator." The Wisconsin and Minnesota variants require that you modify the GRS80 spheroid by adding two non-standard height parameters to both semimajor and semiminor axes. 

* The second WKT included in flipper44's original comment uses a modified spheroid, and is equivalent to the first (non-parsing) WKT.

* The WKT definitions included above all belong to the deprecated "Wisconsin County Coordinate System" (WCCS). An alternative to using WCCS is to use the newer WISCRS CS definitions, which use a standard GRS80 spheroid and tweak the scale_factor, false_easting and false_northing parameters to match WCCS as closely as possible within each county.

I confirmed the above using cs2cs, proj4 definitions for Florence County and a control point from the Wisconsin State Cartographer's Office:

```bash
# WCCS transformation (modified spheroid)
echo 88d37w  45d58n | cs2cs +proj=longlat +datum=NAD83 +to \
+proj=tmerc +a=6378530.851 +b=6357146.165 +k_0=0.9999935 +x_0=133502.6670 \
+y_0=0 +lon_0=-88.1416666667 +lat_0=45.4388888889 +units=us-ft +no_defs
# 317202.43	192824.76 0.00  <- correct output

# faulty WCCS transformation with unmodified GRS80 spheroid
echo 88d37w  45d58n | cs2cs +proj=longlat +datum=NAD83 +to \
+proj=tmerc +datum=NAD83 +k_0=0.9999935 +x_0=133502.6670  +y_0=0 \
+lon_0=-88.1416666667 +lat_0=45.4388888889 +units=us-ft +no_defs
# 317209.88	192812.83 0.00  <- incorrect output

# WISCRS transformation
echo 88d37w  45d58n | cs2cs +proj=longlat +datum=NAD83 +to \
+proj=tmerc +lat_0=45.4388888889 +lon_0=-88.1416666667 +k=1.0000552095 \
+x_0=133502.6682245364 +y_0=0.006400812801625603 +ellps=GRS80 +units=us-ft +no_defs
# 317202.43	192824.75 0.00  <- correct output
```
