### ISSUE TITLE
Proj4JS and Zoo Project API to access nzgd2kgrid0005.gsb file

### ISSUE THREAD

**Issue by surf9** [proj4js/proj4js#202]
Hi there

I am using zoo project WPS to allow re-projection. Zoo project has an API with proj4js built-in. However, I haven't found yet how to pass it the following parameters:

`+proj=nzmg +lat_0=-41.0000000000 +lon_0=173.0000000000 +x_0=2510000.0000000000 +y_0=6023150.0000000000 +a=6378388 +rf=297 +no_defs +nadgrids=nzgd2kgrid0005.gsb`

I've instead added the official proj4js.js file and I am trying to re-project from NZMG to NZTM.

For source projection I used:

`+proj=nzmg +lat_0=-41.0000000000 +lon_0=173.0000000000 +x_0=2510000.0000000000 +y_0=6023150.0000000000 +a=6378388 +rf=297 +no_defs +nadgrids=nzgd2kgrid0005.gsb`

and destination projection I used:

`+proj=tmerc +lat_0=0.0000000000 +lon_0=173.0000000000 +k_0=0.9996000000 +x_0=1600000.0000000000 +y_0=10000000.0000000000 +a=6378137 +rf=298.257222101 +no_defs +towgs84=0.000,0.000,0.000`

I've added in the same directory as the proj4js.js file the nzgd2kgrid0005.gsb file.

Can proj4js.js using zoo project API use the nadgrids parameter to access the file locally without using a browser?

Does proj4js even support the nadgrids parameter?

Thanks,

**Comment by ahocevar** [comment]
Proj4js currently does not support grid transforms, so the nadgrids parameter is ignored.
