### ISSUE TITLE
npm deprecate proj4js

### ISSUE THREAD

**Issue by mbostock** [proj4js/proj4js#206]
Related #50, would you be willing to `npm deprecate proj4js` with a message telling people to `npm install proj4` instead? I acknowledge that this is user error on my part by installing the wrong package name, but I expect I am not the only one who may get confused and it would be easy to point people in the right direction. Thanks!

**Comment by calvinmetcalf** [comment]
I have no problem with that  if you don't @ahocevar

**Comment by calvinmetcalf** [comment]
done
