### ISSUE TITLE
Example Fails. Conversions are off or failing. 

### ISSUE THREAD

**Issue by neoadventist** [proj4js/proj4js#207]
Hi! I was just checking out this library to convert from CA Zone 6 to regular GPS World Geodetic System for a client and got some weird values. So I then decided to write a test to cover the example on the website and got some unexpected results: 

```
it("should run the example well",function(done){
      //Should work according to https://github.com/proj4js/proj4js
      var firstProjection = 'PROJCS["NAD83 / Massachusetts Mainland",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",42.68333333333333],PARAMETER["standard_parallel_2",41.71666666666667],PARAMETER["latitude_of_origin",41],PARAMETER["central_meridian",-71.5],PARAMETER["false_easting",200000],PARAMETER["false_northing",750000],AUTHORITY["EPSG","26986"],AXIS["X",EAST],AXIS["Y",NORTH]]';
      var secondProjection = "+proj=gnom +lat_0=90 +lon_0=0 +x_0=6300000 +y_0=6300000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs";
      //I'm not going to redefine those two in latter examples.
      var resultFromWebsite = [-2690666.2977344505, 3662659.885459918];
      var conversion = proj4(firstProjection,secondProjection,[2,5]);
      console.log(conversion,resultFromWebsite)
      expect(conversion).to.have.all.members(resultFromWebsite);

      done();
    })
```

long story short the test fails. 

`[ -2690666.297734447, 3662659.88545992 ] != [ -2690666.2977344505, 3662659.885459918 ]`

why is it not producing the same thing as the example on the site? I want to believe i'm doing something wrong. 
### Bonus

Also, why do you think the following test fails? 

```
CAzone6 = "+proj=lcc +lat_1=33.88333333333333 +lat_2=32.78333333333333 +lat_0=32.16666666666666 +lon_0=-116.25 +x_0=2000000.0001016 +y_0=500000.0001016001 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs";
 WorldGeodeticSystem= "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs";

it("should convert from CAzone6 to GPS datums",function(done){

      //GPS -- EPSG:4326
      var expectedConversionResult = [-118.07693481447, 33.856427519494];
      //CA Zone 6 -- epsg:2230
      var coordinate = [-2690666.2977344505, 3662659.885459918];
      var conversion = proj4(CAzone6,WorldGeodeticSystem,coordinate);
      console.log(conversion,expectedConversionResult)
      expect(conversion).to.have.all.members(expectedConversionResult);
      done();
    })

```

console.log outputs `[ -147.200376445327, 33.922353589154476 ] [ -118.07693481447, 33.856427519494 ]` 

I would really like _any of this to work_ thank you for looking into this! 

Running `"proj4": "^2.3.15"` on node v6.6.0

**Comment by calvinmetcalf** [comment]
so for part one about the example failing, I suspect the example might have a typo, we test against the individual projections, but I have no memory of where I grabbed the example from, we can look into that to see if it's correct.

for your second example, do you get a different result if you used the built in wgs84 def `'WGS84'`

so doing

```
var CAzone6 = "+proj=lcc +lat_1=33.88333333333333 +lat_2=32.78333333333333 +lat_0=32.16666666666666 +lon_0=-116.25 +x_0=2000000.0001016 +y_0=500000.0001016001 +ellps=GRS80 +datum=NAD83 +to_meter=0.3048006096012192 +no_defs";


it("should convert from CAzone6 to GPS datums",function(done){

      //GPS -- EPSG:4326
      var expectedConversionResult = [-118.07693481447, 33.856427519494];
      //CA Zone 6 -- epsg:2230
      var coordinate = [-2690666.2977344505, 3662659.885459918];
      var conversion = proj4(CAzone6,'WGS84',coordinate);
      console.log(conversion,expectedConversionResult)
      expect(conversion).to.have.all.members(expectedConversionResult);
      done();
    })
```

**Comment by neoadventist** [comment]
@calvinmetcalf i'm getting `[ -147.200376445327, 33.922353589154476 ]` which is not `[ -118.07693481447, 33.856427519494 ]` which doesn't seem to be any different after including the `'WGS84'` which I'm glad is an option! 

I pulled the refrence for CA zone 6 from here: [spatialreference.org/ref/epsg/2230/](url) 

Is it possible that I'm just doing this wrong?

**Comment by neoadventist** [comment]
Anyone else has any tips to solve this?

**Comment by calvinmetcalf** [comment]
according to [epsg.io](http://epsg.io/transform#s_srs=2230&t_srs=4326&x=-2690666.2977345&y=3662659.8854599) -147.2003764 is the correct result not -118.07693481447

**Comment by mbloch** [comment]
Hi @neoadventist

In your first example, the discrepancy between the coordinates that you generated and the reference coordinates that you got from the proj4js README file is only 1e-8 meter (0.00001 of a millimeter). That's not a significant difference. You are using the proj4js library correctly.

In your second example, it looks like you have a mistake in your test coordinates. The test you wrote transforms the coordinates [-2690666.2977344505, 3662659.885459918] from CA zone 6 (NAD83, feet) to WGS84. You copied the coordinates [-2690666.2977344505, 3662659.885459918] from your first example, which uses a Massachussets coordinate system in units of meters. If you apply the CA zone 6 -> WGS84 transformation to those same numbers, then the output that you got (-147.200376445327, 33.922353589154476) is correct. You shouldn't be expecting [-118.07693481447, 33.856427519494].

**Comment by neoadventist** [comment]
ok @mbloch i'm trying to see if I understand you well. 

```
geoConvet.convert = function(from,to,coordinate){
 return proj4(from,to,coordinate); 
}
    var c = null;
     it("should convert from CAzone6 to GPS datums",function(done){

      //GPS -- EPSG:4326
      var expectedConversionResult = [-147.200376445327, 33.922353589154476];
      //CA Zone 6 -- epsg:2230
      var coordinate = [-2690666.2977344505, 3662659.885459918];
      var conversion = geoConvert.convert(CAzone6,"EPSG:4326",coordinate);
      console.log(conversion,expectedConversionResult)
      expect(conversion).to.have.all.members(expectedConversionResult);
      c = conversion;
      done();
    })
    it("should convert from GPS to CAzone6 datums",function(done){

      //GPS -- EPSG:4326
      var coordinate = [-118.07693481447, 33.856427519494];
      coordinate = c;
      //CA Zone 6 -- epsg:2230
      var expectedConversionResult = [2690666.2977344505, 3662659.885459918];
      var conversion = geoConvert.convert("EPSG:4326",CAzone6,coordinate);
      console.log(conversion,expectedConversionResult)
      expect(conversion).to.have.all.members(expectedConversionResult);
      done();
    });
```

The first test passes with 
`[ -147.200376445327, 33.922353589154476 ] [ -147.200376445327, 33.922353589154476 ]`
the second test however fails with 
`[ -2690666.29773449, 3662659.885459779 ] [ 2690666.2977344505, 3662659.885459918 ]`

with the sign flipped on the result. 

replacing CAzone6 with "EPSG:2230" gives weird errors.

**Comment by neoadventist** [comment]
Thanks @calvinmetcalf ! do you have a way where I can put those coordinates in and see it compared to the google map for the lat/lng?

**Comment by mbloch** [comment]
@neoadventist,

* Using "EPSG:2230" with proj4js gives an error because proj4js only supports a few EPSG codes, not including 2230.

* Your test "should convert from GPS to CAzone6 datums" is failing because of a typo in your expected output value. It looks like you're doing a "roundtrip" test, using the input value of your first (inverse) transformation as the expected value of your second (forward) transformation, but you forgot to copy a negative sign. The actual output that you reported is close enough to your original input value to be considered correct.

**Comment by neoadventist** [comment]
wow @mbloch thank you very much! totality did not see that!
