### ISSUE TITLE
Issues with webpack

### ISSUE THREAD

**Issue by atlefren** [proj4js/proj4js#208]
Hi!

Sorry if I'm reporting a known bug, but I couldn't find any reference to the problem I'm facing

My problem is this

I've installed proj4 2.3.15 using npm and try to include it in my project using webpack:

`import proj4 from 'proj4';`

This works fine, but webpack gives me an error

```
WARNING in ./~/proj4/dist/proj4.js
Critical dependencies:
1:407-414 This seems to be a pre-built javascript file. Though this is possible, it's not recommended. Try to require the original source to get better results.
 @ ./~/proj4/dist/proj4.js 1:407-414
```

Well, I guess I'll do something about that is my first thought, but then I check the package.json file for proj4, and main is set to lib/index.js, and all seems fine. The only reference to dist/proj4.js I can find is in the "jam"-block. Stange!

I then tried to remove the yam-block, thinking that this config might be preferred over main (for some, to me, unknown reason, but it seems like @calvinmetcalf  is aware of this: https://github.com/webpack/webpack/issues/1118)

So, removing the yam-block I get progress, sort of:

```
ERROR in ./~/proj4/package.json
Module parse failed: /home/atlefren/path/to/project/node_modules/proj4/package.json Unexpected token (2:9)
You may need an appropriate loader to handle this file type.
SyntaxError: Unexpected token (2:9)
[snip]
 @ ./~/proj4/lib/index.js 10:16-42
```

lib/index.js, line 10 is this

`proj4.version = require('../package.json').version;`

Eureka!

I presume that node has no problems reading json-files, but webpack does not support reading json files out of the box. By installing json-loader and following the advice here: https://github.com/webpack/webpack/issues/965#issuecomment-97186184 I manage to import proj4 using webpack, but this is a bit of a hassle.

Unfortunately I cannot think of a way to solve the issue, so unless someone solves the problem I guess the project is better of with the jam-config beeing used, although this is not ideal.

Would be happy to test fixes if anyone has ideas!

Current env:
node: v6.4.0
npm: 3.10.3
webpack: 1.13.2

**Comment by calvinmetcalf** [comment]
so the jam thing is a bug in webpack, we could probably remove it because I don't really feel like jam is going anywhere anymore, as for the json thing, yes that is something that webpack does that hits *many* projects so you I'd recommend always having the json loader because you if your loading modules from npm everyone assumes your going to have it and it's really really unhelpful on the part of webpack not to include it by default.

we could also use the browserify verison transform which might be helpful as well, it would avoid including the whole json file when we only need that one line

**Comment by atlefren** [comment]
That was my thoughts on jam as well, as their github-page says: "this project is no longer active and not recommended for use". I should probably report this as a bug to webpack as well.. 

Submitted a pull-request removing the jam-config

When it comes to the json-parse thing, I've never encountered it before, and it took me a while to figure it out, so I guess it shuld be mentioned in the readme. Submitted a pull-request for that as well.

**Comment by simon04** [comment]
* Ad "This seems to be a pre-built javascript file.": The `package.json` should link to a non-uglified javascript file (examples: [leaflet](https://github.com/Leaflet/Leaflet/blob/1cc4660/package.json#L25), [angular](https://github.com/angular/bower-angular/blob/7526804/package.json#L5))
* Ad "ERROR in ./~/proj4/package.json": See #214 and https://github.com/proj4js/proj4js/issues/214#issuecomment-274966431
