### ISSUE TITLE
Incorrect transforming from 4236 to 3857

### ISSUE THREAD

**Issue by aleksandrmelnyk** [proj4js/proj4js#213]
For example a point in 4326: POINT (116.7641 -20.6137)

1. Transform  it in postgis
`select st_astext(st_transform(st_geomfromtext('POINT (116.7641 -20.6137)', 4326),3857))`
output: POINT(12998120.1549349 -2345875.59646825)

2. Proj4.js (version 2.3.15),  will output [12998120.154934874, -2330836.992763932]

about 15 km shifted by latitude.

**Comment by ahocevar** [comment]
Maybe you did an incorrect override of one of the involved projection definitions? Out of the box, I get
```js
proj4('EPSG:3857', [116.7641, -20.6137]);
// [12998120.154934874, -2345875.5964682475]
```

**Comment by aleksandrmelnyk** [comment]
Am using this definition
`+proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs`

seems right?

**Comment by ahocevar** [comment]
Why don't you leave the default `+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs` untouched?

**Comment by aleksandrmelnyk** [comment]
ok, yep, good note. That old definition left from previous versions of proj4js.  
Think this issue should closed, in case someone else would face it, he should NOT use definition from here http://spatialreference.org/ref/sr-org/6864/proj4/ but use built-in.
