### ISSUE TITLE
how to install and require when using webpack

### ISSUE THREAD

**Issue by barbalex** [proj4js/proj4js#214]
I am using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) in [my project](https://github.com/barbalex/apf).

I did:

    npm i --save proj4

then required it:

    import Proj4 from 'proj4'

and get this:

    index.js:10 Uncaught Error: Cannot find module "../package.json"(…)

where index.js is:

    var proj4 = __webpack_require__(1040);
    proj4.defaultDatum = 'WGS84'; //default datum
    proj4.Proj = __webpack_require__(283);
    proj4.WGS84 = new proj4.Proj('WGS84');
    proj4.Point = __webpack_require__(1030);
    proj4.toPoint = __webpack_require__(440);
    proj4.defs = __webpack_require__(441);
    proj4.transform = __webpack_require__(444);
    proj4.mgrs = __webpack_require__(438);
    proj4.version = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../package.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).version;
    __webpack_require__(1045)(proj4);
    module.exports = proj4;

    //////////////////
    // WEBPACK FOOTER
    // ./~/proj4/lib/index.js
    // module id = 1046
    // module chunks = 0

and index.js:10 is:

    proj4.version = __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module \"../package.json\""); e.code = 'MODULE_NOT_FOUND'; throw e; }())).version;

The exact same error occurs when I require proj4leaflet:

    import Proj4leaflet from 'proj4leaflet'

What am I doing wrong?

I suppose that today many - if not most - use webpack or similar tools. So It would be great if the installation and usage instructions on http://proj4js.org would include this information. I personally haven't used globals in quite a while now.

**Comment by calvinmetcalf** [comment]
Hm this was built with browserify, I'm on vacation but will check early
next week when I'm back in front of a computer

**Comment by barbalex** [comment]
enjoy!

**Comment by barbalex** [comment]
any updates on this?

**Comment by calvinmetcalf** [comment]
json loader, you need the json loader

**Comment by barbalex** [comment]
I am:

- https://github.com/barbalex/apf/blob/master/package.json#L298
- https://github.com/barbalex/apf/blob/master/internals/webpack/webpack.base.babel.js#L46-L49

**Comment by barbalex** [comment]
But yeah, seems like json-loader is missing when the webpack dll is built:

When I run `npm i`, this logs:

    Building the Webpack DLL...
    Hash: e32cb2c74b3972520c91
    Version: webpack 2.1.0-beta.15
    Time: 4515ms
                          Asset     Size  Chunks             Chunk Names
    reactBoilerplateDeps.dll.js  5.97 MB       0  [emitted]  reactBoilerplateDeps
    chunk    {0} reactBoilerplateDeps.dll.js (reactBoilerplateDeps) 5.32 MB [rendered]
     [1454] dll reactBoilerplateDeps 12 bytes {0} [built]
         + 1455 hidden modules

    ERROR in ./~/proj4/package.json
    Module parse failed: C:\Users\alex\apf\node_modules\proj4\package.json Unexpected token (2:9)
    You may need an appropriate loader to handle this file type.
    | {
    |   "_args": [
    |     [
    |       {
     @ ./~/proj4/lib/index.js 10:16-42

...as in the package.json scripts there is this here:

    "postinstall": "npm run build:dll",

I am using [react-boilerplate](https://github.com/mxstbr/react-boilerplate) so maybe I have to bring up this issue there?

**Comment by calvinmetcalf** [comment]
yeah this is likely an issue with the webpack config, so I'd bring it up there or with webpack

**Comment by barbalex** [comment]
thanks!

**Comment by simon04** [comment]
I disagree that it would be the task of the module user to use webpack's `json-loader` just because the plugin [internally `requires(../package.json")`](https://github.com/proj4js/proj4js/blob/e6b88d3/lib/version.js).

Anyhow, this issue will vanish when merging #224.
