### ISSUE TITLE
Angular2: Using Leaflet, Leaflet-draw plugin and proj4leaflet ... Drawing events

### ISSUE THREAD

**Issue by mehmobrams** [proj4js/proj4js#217]
require('proj4');
require('leaflet');
require('proj4leaflet');
require('leaflet-draw');
require('leaflet-draw/dist/leaflet.draw.css');
require('leaflet/dist/leaflet.css');

When I use a projection, it is not possible to draw and edit polygons. 
The mouse events have some trouble.

**Comment by calvinmetcalf** [comment]
This is almost certainly an issue with proj4leaflet or leaflet draw, not
this library

**Comment by mehmobrams** [comment]
Ok. Do you have any recommandation or sample to do that.
![2016-11-22 13_15_44-angular with webpack](https://cloud.githubusercontent.com/assets/809401/20523528/cbaa5d88-b0b5-11e6-8921-794e47cdf674.png)

**Comment by calvinmetcalf** [comment]
> Ok. Do you have any recommandation or sample to do that.

I don't understand, I said the issue was with [proj4leaflet](https://github.com/kartena/Proj4Leaflet) most likely
