### ISSUE TITLE
Need help to convert  EPSG:32039: NAD27 to Normal Lat / Long

### ISSUE THREAD

**Issue by udkadam** [proj4js/proj4js#219]
I have xml file which has nodes/points defined in  EPSG:32039: NAD27, I want to draw it on HTML canvas or google map. Any solution ?

<?xml version="1.0"?>
<Point>
<X>3338876.000000</X>
<Y>557789.187500</Y>
</Point>
Above is xml format.

**Comment by calvinmetcalf** [comment]
you could try [leaflet](http://leafletjs.com/) and either de-project your data into lat longs before you do so or use  [Proj4Leaflet](https://github.com/kartena/Proj4Leaflet) to project your data on the fly
