### ISSUE TITLE
Inconsistency between Proj4js and Proj.4 when using proj string without datum

### ISSUE THREAD

**Issue by theashyster** [proj4js/proj4js#227]
Using `Proj4js` library with a proj string containing `+datum=none` does the calculation perfectly:
`+proj=tmerc +a=6400000 +lat_1=0.5 +lat_2=2 +n=0.5 +datum=none`

Using `Proj4js` library with a proj string not containing `+datum` fails the calculation and returns NaN, NaN:
`+proj=tmerc +a=6400000 +lat_1=0.5 +lat_2=2 +n=0.5`

Using `Proj.4` library with a proj string containing `+datum=none` fails the calculation with projection initialization failure:
`+proj=tmerc +a=6400000 +lat_1=0.5 +lat_2=2 +n=0.5 +datum=none`

Using `Proj.4` library with a proj string not containing `+datum` does the calculation perfectly:
`+proj=tmerc +a=6400000 +lat_1=0.5 +lat_2=2 +n=0.5`

This is because here we set the `WGS84` as the default datum, but in the `Proj.4` library and also `mapshaper-proj` library if the datum is not set, then it is set to `none` by default, not `WGS84`.

Should this be fixed or is it supposed to be this way?

**Comment by calvinmetcalf** [comment]
we should probably add the default datum like proj.4, that's probably an oversight

**Comment by theashyster** [comment]
@calvinmetcalf I copied the hyperlink to the line of code where `Proj4js` adds the default datum, but forgot to paste it in, so here it is https://github.com/proj4js/proj4js/blob/master/lib/datum.js#L9

For me it looks like `proj.4` and `mapshaper-proj` both add `+datum=none` when there is no `datum` specified in the proj string, but `proj4js` actually adds `WGS84` as the default `datum` if there is no `datum` specified in the proj string.

**Comment by calvinmetcalf** [comment]
yeah so we probably then want a datum=null to just skip that whole thing

**Comment by theashyster** [comment]
For me it looked like here https://github.com/proj4js/proj4js/blob/master/lib/datum.js#L10 something like this would work perfectly fine and work the same way as `proj.4`.
`if (datumCode === undefined || (datumCode && datumCode === 'none')) {`

**Comment by theashyster** [comment]
Since the pull request is merged, I am closing this issue.
