### ISSUE TITLE
How to project to cartesian from Google Map projection?

### ISSUE THREAD

**Issue by sweetim** [proj4js/proj4js#236]
I would like to have similar conversion as shown in the link below,
http://www.apsalin.com/convert-geodetic-to-cartesian.aspx

May I know how can I achieve this conversion? What projection should I use?

```
const proj4 = require('proj4');

const POINT_1 = [35.826922, 139.686612];
const POINT_2 = [35.826841, 139.686610];

const p1 = proj4(
    'EPSG:3857', 
    '',  // what projection should be used?
    POINT_1)

const p2 = proj4(
    'EPSG:3857',
    '', // what projection should be used?
    POINT_2
)

```

I think the projection should be `ECEF` but it seems that this package doesnt support it?

**Comment by calvinmetcalf** [comment]
google earth is in a Cartesian projection known by it's number '3857' also known as Spherical Mercator   I'm assuming you want to convert between that and unprojected latitude longitude which is number '4326', but since your data looks to already be unprojected lat lons you need to swing the order so

```js
const p1 = proj4(
    'EPSG:4326', // what the data is currently in
    'EPSG:3857',  // what you want it to be
    POINT_1)
```

what you are doing is actually such a typical case, going from lat lons to a coordiante system that you can actually omit the 4326 and just do

```js
const p1 = proj4(
    'EPSG:3857',
    POINT_1)

```

**Comment by sweetim** [comment]
@calvinmetcalf , i tried that and i get 

```
[ 3988234.7137303306, NaN ]
```

**Comment by calvinmetcalf** [comment]
the coordinates should be in x,y order `[35.826922, 139.686612];` is likely backwards as longitude would be the 'x' in this case.

**Comment by calvinmetcalf** [comment]
this is all in the readme so feel free to open a new issue if there are ways we can make the readme less confusing

**Comment by mbloch** [comment]
@sweetim, from your description, it sounds like you want to convert your data to geocentric (aka ECEF) coordinates. proj4js does not support this conversion (the original Proj.4 library does). 

You could try this library: https://github.com/benelsen/orb
It has the functions ellipsoidalToCartesian() and sphericalToCartesian(). One of these conversions if probably what you're looking for.

**Comment by calvinmetcalf** [comment]
oh woops @sweetim looks like I may have misread your question

**Comment by sweetim** [comment]
@mbloch yes, that is what i am looking for! 

it also found another npm package that supports it
https://github.com/lakowske/ecef-projector

it would be great, if this information is shared at the README! ;)

**Comment by calvinmetcalf** [comment]
@sweetim fyi the coordinate reference system you were coming from wasn't EPSG:3857 but EPSG:34326, should have double checked but that threw me off sorry
