### ISSUE TITLE
UTM regression in 2.3.16/2.3.17 

### ISSUE THREAD

**Issue by MrSnyder** [proj4js/proj4js#237]
I noticed a (tiny) numerical issue when updating from 2.3.15 to 2.3.17. My use case is converting from WGS 84 to EPSG:32631 (UTM zone 31):

Input: [3, 0] (center meridian of zone 31)
Actual output: UTM, Zone 31: [500000.000000001, 0]
Expected output: [500000, 0]

I know this is a minimal difference, but AFAIK, the center meridian of each UTM zone is defined to be exactly at 500 km, right?

I prepared two fiddles to demonstrate what I believe to be a regression between 2.3.15 and 2.3.17:

* 2.3.17: https://jsfiddle.net/d52j2nkm/1/
* 2.3.15: https://jsfiddle.net/d52j2nkm/2/

What's also strange is that the regression only seems to affect odd UTM zones, for even zones, the meridian is still exactly at 500km:

* 2.3.17, odd zone: https://jsfiddle.net/d52j2nkm/3/

**Comment by calvinmetcalf** [comment]
2 things

1. thats just a floating point rounding error
2. check against alpha by doing npm install proj4@alpha it's probably already fixed

**Comment by MrSnyder** [comment]
calvinmetcalf, thanks for your super-quick reply.

1. Yes, I know. And I don't want to annoy anybody here, still cs2cs on the command line gives exactly 500km (as does 2.3.15). Plus it works for even UTM zones. So I figured it would be worth pointing this out.
2. Thanks for the hint. I did it just now, but it's still there.

**Comment by calvinmetcalf** [comment]
ok so this is almost certainly related to the UTM we put in around then so I'll take a look

**Comment by calvinmetcalf** [comment]
ok checkout #243

**Comment by MrSnyder** [comment]
Very nice. I checked with current master, and I get the exact value of [500000, 0] again. Fixed by commit 7d94169bb0fa1ab1315176446348979367a575a1.

Thank you.
