### ISSUE TITLE
Unable to derive sphere constant when projection ellps is undefined

### ISSUE THREAD

**Issue by philipforget** [proj4js/proj4js#240]
This was introduced in in [this commit](https://github.com/proj4js/proj4js/commit/9dc0fb7921fe697db2a8beb2fc7abf01f2cb1e5d) when the map lookup on `Ellipsoid` was changed to use the new [match function](https://github.com/proj4js/proj4js/blob/master/lib/match.js#L2)

[Previously the map lookup](https://github.com/proj4js/proj4js/blob/8c0c0eef0bfbf74ee82c2463e1adab65faea02a4/lib/deriveConstants.js#L32) would return `undefined` which would then cause `ellipse` to default to `Ellipsoid.WGS84`. Now if the key passed to `match` is `undefined`, it causes a TypeError to be thrown [during the call to key.toLowerCase()](https://github.com/proj4js/proj4js/blob/master/lib/match.js#L7).

I'm not sure if this new behavior is intended and is only now causing our own test cases to fail or if `match` should return `undefined` early if no key is passed.

**Comment by calvinmetcalf** [comment]
not intentional, could you give me an example wkt that is triggering this so we can add a test ?

**Comment by philipforget** [comment]
Sure thing, here's a simple case:

```javascript
// Only works in <2.4.1 due to `match` change
var proj4 = require("proj4");

proj4.defs([
  [
    "UTM18",
    "+proj=utm +zone=18 +units=m"
  ]
])

proj4('UTM18');
```

Traceback:

```
/app/node_modules/proj4/dist/proj4-src.js:68
          var lkey = key.toLowerCase().replace(ignoredChar, '');
                        ^

TypeError: Cannot read property 'toLowerCase' of undefined
    at match (/app/node_modules/proj4/dist/proj4-src.js:68:18)
    at sphere (/app/node_modules/proj4/dist/proj4-src.js:1186:20)
    at new Projection$1 (/app/node_modules/proj4/dist/proj4-src.js:1369:18)
    at Projection$1 (/app/node_modules/proj4/dist/proj4-src.js:1341:13)
    at checkProj (/app/node_modules/proj4/dist/proj4-src.js:1846:11)
    at proj4$1 (/app/node_modules/proj4/dist/proj4-src.js:1849:15)
    at Object.<anonymous> (/app/test.js:10:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
```
If you include the default system in the projection the TypeError does not get raise which makes sense.

```javascript
// Not a problem if you specify the default system
var proj4 = require("proj4");

proj4.defs([
  [
    "UTM18",
    "+proj=utm +zone=18 +units=m +ellps=WGS84"
  ]
])

proj4('UTM18');
```

**Comment by philipforget** [comment]
Thanks for the quick fix @calvinmetcalf
