### ISSUE TITLE
defs not exported in 2.4?

### ISSUE THREAD

**Issue by wulfsberg** [proj4js/proj4js#247]
I have a (TypeScript) project which uses v2.3.16 like this:

    import * as proj4 from 'proj4';
    ...
    proj4.defs('EPSG:25832', '+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs');

This works in 2.3.6, but after updating to a 2.4 version, it gives me

    WARNING in ./src/openlayers/openlayers.service.ts
    60:8-18 "export 'defs' (imported as 'proj4') was not found in 'proj4'

Do I need to do something different after the rollup build in 2.4, or has some export been mangled?

**Comment by calvinmetcalf** [comment]
`import proj4 from 'proj4'`

**Comment by wulfsberg** [comment]
Hm, that leaves me with an outdated @types definition which doesn't match that notation (giving me a `...node_modules/@types/proj4/index"' has no default export.`), but that is another matter.

**Comment by wulfsberg** [comment]
For anybody stumbling across this in the future, you also need to let your TypeScript compiler `"allowSyntheticDefaultImports": true`. (Seems relevant to @cvq's https://github.com/proj4js/proj4js/issues/254)

**Comment by youssef-aitali** [comment]
> For anybody stumbling across this in the future, you also need to let your TypeScript compiler `"allowSyntheticDefaultImports": true`. (Seems relevant to @cvq's #254)

This resolved my issue. Thanks a lot.
