### ISSUE TITLE
Problem using proj4 in an UMD library

### ISSUE THREAD

**Issue by rbrondi** [proj4js/proj4js#248]
I'm trying to transform Potree library in a JS module so that I can import it in an angular2 application bundled with webpack. 

Potree depends on proj4, so I've installed it in my Potree checkout using
`npm install --save proj4`

Then I used gulp-umd to pack Potree in an UMD module. Here is my gulp-umd configuration

```
gulp.task('umd', function(file) {
    return gulp.src('build/potree/potree.js')
        .pipe(umd({
            dependencies: function (file) {
                return [{
                    name: 'three',
                    amd: 'three',
                    cjs: 'three',
                    global: 'three',
                    param: 'THREE'
                }, {
                    name: 'jquery',
                    amd: 'jquery',
                    cjs: 'jquery',
                    global: 'jquery',
                    param: '$'
                }, {
                    name: 'jqueryui',
                    amd: 'jqueryui',
                    cjs: 'jqueryui',
                    global: 'jqueryui',
                    param: 'jqueryui'
                }, {
                    name: 'proj4',
                    amd: 'proj4',
                    cjs: 'proj4',
                    global: 'proj4',
                    param: 'proj4'
                }, {
                    name: 'openlayers',
                    amd: 'openlayers',
                    cjs: 'openlayers',
                    global: 'openlayers',
                    param: 'ol'
                }, {
                    name: 'd3',
                    amd: 'd3',
                    cjs: 'd3',
                    global: 'd3',
                    param: 'd3'
                }, {
                    name: 'tween.js',
                    amd: 'tween.js',
                    cjs: 'tween.js',
                    global: 'tween.js',
                    param: 'TWEEN'
                }, {
                    name: 'i18n',
                    amd: 'i18n',
                    cjs: 'i18n',
                    global: 'i18n',
                    param: 'i18n'
                }];
            },
            templateName: 'amdNodeWeb'
        }))
        .pipe(rename('potree.umd.js'))
        .pipe(gulp.dest('build/potree'));
});
```

and here is the result I get
```
;(function(root, factory) {oject proj4 
  if (typeof define === 'function' && define.amd) {
    define(['three', 'jquery', 'jqueryui', 'proj4', 'openlayers', 'd3', 'tween.js', 'i18n'], factory);
  } else if (typeof exports === 'object') {
    module.exports = factory(require('three'), require('jquery'), require('jqueryui'), require('proj4'), require('openlayers'), require('d3'), require('tween.js'), require('i18n'));
  } else {
    root.Potree = factory(root.three, root.jquery, root.jqueryui, root.proj4, root.openlayers, root.d3, root.tween.js, root.i18n);
  }
}(this, function(THREE, $, jqueryui, proj4, ol, d3, TWEEN, i18n) {
....
}));
```
Everything works fine except for the fact that inside the module the variable proj4 is incapsulated inside a `default` object and therefore to use it I have to write `proj4.default.defs(...)`

Am I missing something? What I'm doing wrong?
Thanks a lot

**Comment by calvinmetcalf** [comment]
I don't 100% get what you're trying to do, are you trying to build potree locally to include in a wepback app because I don't think that's going to work due to how potree has worker files and image files and whatnot that it doesn't include inline.

**Comment by calvinmetcalf** [comment]
as for your specific question, I can't speak of how that grunt plugin works, but it looks like its grabbing the ES6 version instead of the commonjs version of proj4 which is weird, why don't you just use webpack to build this stuff instead of gulp?

**Comment by rbrondi** [comment]
Hi @calvinmetcalf , thanks for your reply. I'm new to JS modules and webpack so my approach is likely full of mistakes. I've used gulp because Potree is currently based on it to build itself and it was the quickest way to get something working. 
I know about Potree workers, files and other stuff but right now I'm able to make it run inside an Angular2 application redefining `proj4 = proj4.default;`
I will refine the library but right now I just need a quick way to make it work.

**Comment by calvinmetcalf** [comment]
if `proj4 = proj4.default;` works for you then that's probably your best bet, it's likely some weird mishmash between several different module types
