### ISSUE TITLE
Inconsistency when transforming NaN, Infinity using various projections

### ISSUE THREAD

**Issue by theashyster** [proj4js/proj4js#250]
There seems to be an issue when the input point is something like `[NaN, NaN]` or `[Infinity, Infinity]` and we try to call transform using some of the projections. The returned result is quite inconsistent - some times it returns `[NaN, NaN]`, some times `[Infinity, Infinity]`, some times coordinates like `[0, 90]` or `[45, 90]`.

When we pass in such params as `NaN` or `Infinity` shouldn't there be some safe guard checks in front of the actual transformation that checks if the passed in points are valid to work with? At least check if they are not `NaN` or `Infinity` since using transformation on such values won't give any meaningful results?

I have created 2 separate JS Bin examples
https://jsbin.com/fipuxiqufe/edit?html,console,output (using proj4js 2.4.3)
https://jsbin.com/mapotalape/edit?html,console,output (using proj4js 2.3.15)

I created 2 separate examples, because I also wanted to show the issue with `tmerc` projection, that I have introduced. When using 2.3.15 and passing in `[NaN, NaN]` to the `inverse` function the returned result is also `[NaN, NaN]`. But since 2.3.16 when passing `[NaN, NaN]` to the `inverse` function the returned result is `[0, 90]` and I don't think this is correct behavior.

Also after the introduction of `etmerc` in 2.3.18-alpha, when passing in `[NaN, NaN]` to the `inverse` function of `utm` projection (which uses `etmerc`) the returned result is `[Infinity, Infinity]`, but I am not sure if that should be the case or not.

I already looked at the code of `tmerc` and `etmerc` and we set those values there when some conditions are not met for the result, but I don't think those conditions were put there to also catch such things as `NaN` or `Infinity`.

So all in all would be great to hear some advice and thoughts from you, guys.

**Comment by calvinmetcalf** [comment]
yeah we should probably have an `isNotFiniteNumber` check of some sort and throw an error

**Comment by theashyster** [comment]
Heh, yep, I think that would be the correct approach, since we cannot transform to a sane result using insane numbers.
