### ISSUE TITLE
Cartesian coordinates

### ISSUE THREAD

**Issue by kfirbene** [proj4js/proj4js#252]
Hi,

I am trying to convert Cartesian coordinates lat, long, alt in min/sec etc..
Both in WGS84.
Can anyone assist?

Thanks.

**Comment by calvinmetcalf** [comment]
I don't understand the question completely, are you trying to convert from minute/second style notation to decimal notation for lat longs ?

**Comment by kfirbene** [comment]
Not exactly.

I have Cartesian coordinates (if you are familiar with Cesium JS it is Cartesian3) and I need to convert it to lat, long alt in minutes/ seconds using proj4.

**Comment by calvinmetcalf** [comment]
So we only deel in decimal degrees and we don't deel with altitude, so
you'd need to convert to minutes/seconds some other way. As for the actual
conversation you'd need to know the specific type of Cartesian coordinates
you have as there are many different ways projecting to Cartesian
coordinations
