### ISSUE TITLE
Can not use with angular 4

### ISSUE THREAD

**Issue by cvq** [proj4js/proj4js#254]
I have a problem using proj4 with angular 4.
In Chrome console, ther is a message: ERROR ReferenceError: proj4 is not defined.
Can any body know how to fix this please.
Thank you.

**Comment by calvinmetcalf** [comment]
how did you install it? how are you trying to import it? do you have other dependencies that do work for you?

**Comment by cvq** [comment]
Hi. I do install as follow: 
npm install proj4 --save
npm install @types/proj4 --save

**Comment by cvq** [comment]
in the component, i do:
import { proj4 } from 'proj4';
P.S. i have no problem with angular 2

**Comment by cvq** [comment]
Hi Calvin Metcalf,
I have no dependencies in my app.

**Comment by calvinmetcalf** [comment]
`import proj4 from 'proj4';` is what you want to do

**Comment by cvq** [comment]
Thank you, i will try.

**Comment by cvq** [comment]
Thank you very much Calvin Metcalf.
That's exactly what you said: import prj4 from 'proj4'
There is something wrong in @types/proj4/index.d.ts: "export = proj4;" (the last line), i changed to "export default proj4;" and now it works.
Thanks again.
