### ISSUE TITLE
Infinite operation on Mollweide projection

### ISSUE THREAD

**Issue by kingfisher13** [proj4js/proj4js#256]
Apologize in advance if this is hard to replicate.

Working version: 2.3.17
Bugged version: 2.4.x

I had a bug where drawing a d3 vector of the world projected onto a Leaflet tile map was hanging with Mollweide projection. Specifically the `forward` function. Tracked it down to this [code](https://github.com/proj4js/proj4js/blob/master/lib/projections/moll.js#L19):

```
/* Iterate using the Newton-Raphson method to find theta
      -----------------------------------------------------*/
  for (var i = 0; true; i++) {
    var delta_theta = -(theta + Math.sin(theta) - con) / (1 + Math.cos(theta));
    theta += delta_theta;
    if (Math.abs(delta_theta) < EPSLN) {
      break;
    }
  }
```

The problem was that `Math.abs(delta_theta)` was never less than `EPSLN`.
I solved it by changing the for loop to end after 100 iterations `for (var i = 0; i<100; i++) {` which is obviously a hack, but seems to work well enough for my purposes. 

Logs leading up to the hang:
```
console.log(lon, lat, delta_lon, theta, con);
-3.141592653589793 -1.3981832637726574 -3.141592653589793 -1.3981832637726574 -3.094906445571509
```

```
console.log(EPSLN);
2.220446049250313e-16
```

```
if (i < 100) console.log(delta_theta);
-0.6072792942381932
-0.315141935607568
-0.1333818531884728
-0.027420655741693258
-0.0011228675542062185
-0.0000018450944152329483
-4.976677737435555e-12
-2.120442154881964e-15
2.120442154881978e-15
-2.120442154881964e-15
2.120442154881978e-15
```

I don't know the math well enough to figure out why exactly this starts alternating values, but because it does, it never drops below EPSLN.

**Comment by calvinmetcalf** [comment]
ah, that would be 2006b0a06d000308caa3625005f3d5734ef11f61 which changed EPSLN from being ` 1.0e-10` to be `Number.EPSILON` which is `2.220446049250313e-16` thanks I can add a fix

**Comment by calvinmetcalf** [comment]
what the proj code or string you used that triggered this ?

**Comment by kingfisher13** [comment]
Proj string: `'+proj=moll +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs'`

**Comment by calvinmetcalf** [comment]
and what were the coords you put in that caused the issue ?

**Comment by kingfisher13** [comment]
It was vectors for the world. The coord that crashed it was `(-180, 80.11)` but if I rounded `80.11` to `80` the crash would occur further down the line (something in the 50's range I think). So I'm not sure about the specific coords.

The vectors we use are here. 2 topojsons and a geojson:
[vectors.zip](https://github.com/proj4js/proj4js/files/1071686/vectors.zip)

**Comment by calvinmetcalf** [comment]
ok that's great thanks
