### ISSUE TITLE
EPSG:4055 TO EPSG:4326 problem

### ISSUE THREAD

**Issue by lag945** [proj4js/proj4js#260]
coordinate not be converted.
for example:
121,23  4055 to 4326 still 121,23
121,23 4326 to 4055 still 121,23
but c version is fine.
EPSG:4055 +proj=longlat +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +no_defs
EPSG:4326 +proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs

**Comment by ahocevar** [comment]
What transformed coordinates were you expecting?

According to the proj4 definition string you provide above, EPSG:4055 actually is the same as [EPSG:4055](http://epsg.io/4055). Did you mean to use a projection for the Arctic? There is an area definition [EPSG:4055](http://epsg.io/4055-area), which is used in the [EPSG:6076](http://epsg.io/6076) projection.

**Comment by lag945** [comment]
Thanks for your replay,ahocevar.
I'm sure EPSG:4055 is not the same as EPSG:4326,
EPSG:4326 +a=6378137,+b=6356752.314
EPSG:4055 +a=6378137,+b=6378137
Different datum,different coordinate.
Actually in c version proj4(http://proj4.org/)
, EPSG:4055(121,23) transformed to EPSG:4326 = (121,23.138669952).
sample code as follow:
	#include <proj_api.h>
	
	
	projPJ from=pj_init_plus("+proj=longlat +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +no_defs");
	projPJ to=pj_init_plus("+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs");
	double x=121.0;
	double y=23.0;
	double z=0.0;
	if(pj_is_latlong(from))
	{
		x*=DEG_TO_RAD;
		y*=DEG_TO_RAD;
	}
	
	int ret_transform=pj_transform(from,to,1,0,&x,&y,&z);
	if(ret_transform==0)
	{
		if(pj_is_latlong(to))
		{
			x*=RAD_TO_DEG;
			y*=RAD_TO_DEG;
		}
	}

**Comment by calvinmetcalf** [comment]
so the issue is that we use the towgs84 matrix in order to convert between datums, so while the a and b parameters are telling us that it's a sphere not an ellipse the towgs84 param is telling us that no transform is necessary, some code splunking in the c version may be necessary to figure out the c version deals with this situation.
