### ISSUE TITLE
Can I do an Orthographic + azimuth projection?

### ISSUE THREAD

**Issue by spoilsportmotors** [proj4js/proj4js#266]
I'm pretty sure the answer is "no", but I'm trying to work from WKT (ESRI sourced) that looks like:

PROJCS["Yikes",
    GEOGCS["GCS_North_American_1927",
        DATUM["D_North_American_1927",
            SPHEROID["Clarke_1866",6378206.4,294.9786982]],
        PRIMEM["Greenwich",0.0],
        UNIT["Degree",0.0174532925199433]],
    PROJECTION["Orthographic"],
    PARAMETER["False_Easting",32767],
    PARAMETER["False_Northing",24000],
    PARAMETER["Scale_Factor",0.99998],
    PARAMETER["Azimuth",-33.791325],
    PARAMETER["Longitude_Of_Center",-44.444],
    PARAMETER["Latitude_Of_Center",44.444],
    UNIT[,0.304768663224]]

Not surprisingly the proj4 definition for this drops scale and azimuth. 

Happy to (try to) make a custom projection, but is that my only hope?

**Comment by calvinmetcalf** [comment]
what is the actual problem that you are encountering, are you getting different results then esri when using this projection in proj4js ?

**Comment by spoilsportmotors** [comment]
Yeah, the features I have in this projection aren't rotated with Proj4js, but they are with the various ESRI things.

I wind up with a proj4 definition that looks like:
+proj=ortho +lat_0=44.444 +lon_0=-44.444 +x_0=9986.354787860808 +y_0=7314.447917375999 +ellps=clrk66 +to_meter=0.304768663224 +no_defs 

And that makes sense, because as near as I can tell, there's no way with Proj4 to make an Orthographic projection with a rotation about its origin. If there's a way to sneak the value of "Azimuth" in there, I'm all for it, but I don't see where it'd be used in the code.

Background: someone made this projection so that their features - which lay on a non-north up grid due to local geology - look like they're on a regular grid. Convenient, I guess? Anyway, the WKT description causes ESRI tooling to behave and rotate data, but I can't quite make it work out with Proj4js.

**Comment by calvinmetcalf** [comment]
the ortho projection doesn't actually use the azimuth value so that probobly won't help, maybe if you were to define it in terms of a to_wgs84 6 parameter transform?

**Comment by spoilsportmotors** [comment]
Thanks for the suggestion - lemme go read up on that, see if I can wrestle a solution out of it.

**Comment by spoilsportmotors** [comment]
No dice; I'm trying to use my interestingly projected data in leaflet via proj4leaflet, and I can't get it to align. If I make a custom projection variant of Orthographic which supports azimuth, can I use that? I get that I'm pretty much on my own for making / using private builds at that point, since I doubt proj4js has any need/use for such a thing.

**Comment by calvinmetcalf** [comment]
hey try reinstalling all the deps, I think it actually may have been an issue with uppercase values in the wkt

**Comment by spoilsportmotors** [comment]
OK - will try - sorry for the delay, I'd had to move on to other things. For now, I think we're going to require the data be in a known projection, because of the misery otherwise. Thanks much for your help - closing this for now.
