### ISSUE TITLE
Unsupported coordinate system EPSG:28992

### ISSUE THREAD

**Issue by PedroEGV** [proj4js/proj4js#269]
I try to use EPSG:28992 but it seems to be unsupported.

The projections are define:
* PROJCS["RD_New",GEOGCS["GCS_Amersfoort",DATUM["D_Amersfoort",SPHEROID["Bessel_1841",6377397.155,299.1528128]],PRIMEM["Greenwich",0],UNIT["Degree",0.0174532925199432955]],PROJECTION["Double_Stereographic"],PARAMETER["False_Easting",155000],PARAMETER["False_Northing",463000],PARAMETER["Central_Meridian",5.38763888888889],PARAMETER["Scale_Factor",0.9999079],PARAMETER["Latitude_Of_Origin",52.15616055555555],UNIT["Meter",1]]
* +proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs

Also I wanted to know how to add this support myself.

**Comment by calvinmetcalf** [comment]
```js
proj4('+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +no_defs')
  .inverse([-70, 40]);
> [ 3.312777056480293, 47.975602725871894 ]
```

is that incorrect ?

for the first method yes that isn't going to work becuase we don't have `Double_Stereographic` as a defined name for sterea yet, but you could add that [here](https://github.com/proj4js/proj4js/blob/acd5f738db24885a28039c680e31e7a3a4182072/lib/projections/sterea.js#L58)

**Comment by PedroEGV** [comment]
@calvinmetcalf, can you please review [this PR](https://github.com/proj4js/proj4js/pull/270).
