### ISSUE TITLE
get projection parameters/matrix/polynomial

### ISSUE THREAD

**Issue by pedroscaff** [proj4js/proj4js#277]
Hi,

I have a projection string that works fine but I can't find a way to extract the polynomial/transformation matrix that is used internally by proj4 to transform the points.
I am integrating 3D objects with different projections into a 3D scene with Threejs and my goal is to setup the transformation matrix for the object using the projection string (not directly but using proj4 to calculate the params for me).
Is that possible with proj4?

Thanks a lot!

**Comment by calvinmetcalf** [comment]
the only transformation matrix that is used here is the one to do datum transformation (e.g. between different models of the earth's shape) those should be straight forward to extract from the proj string as you'l be able to see them as 6 digits separated by comas. 

As for the projections themselves, they aren't implemented in terms of matrices, there not implimeted in any single way period as there are [30 different projections](https://github.com/proj4js/proj4js/tree/master/lib/projections) that project the earth to a verity of geometries (mainly cones and cylinders for the most used ones) so I'm not sure those matrices are even possible to create.

Take a look at [Lambert Conformal Conic](https://github.com/proj4js/proj4js/blob/master/lib/projections/lcc.js) to get an idea of the math involved, it may be possible to turn that into a matrix but I have no idea how.

**Comment by pedroscaff** [comment]
thanks for the answer, it gave me good guidance! I spent the last days dig into these topics (projections, graphics with threejs, 3D maps) and now I have a better understanding and `proj4` is a tool that I have been using a lot :)
