### ISSUE TITLE
Geoidgrids functionality

### ISSUE THREAD

**Issue by eran-pinhas** [proj4js/proj4js#284]
Such as EGM96 or EGM08 will work

Usage example: `'+title=WGS 84 (long/lat) +proj=longlat +ellps=WGS84 +datum=WGS84 +geoidgrid=egm96_15.gtx +units=degrees'`

**Comment by calvinmetcalf** [comment]
this is a dup of #62 (the tl;dr is they are not supported and while we wouldn't necessarily be against adding it to the library I don't think anyone is inclined to want to do the work)
