### ISSUE TITLE
Getting [NaN, NaN] when converting to +proj=stere

### ISSUE THREAD

**Issue by ISNIT0** [proj4js/proj4js#290]
**proj4.js version**: `2.4.3`

Repro:
```javascript
proj4('EPSG:4326', '+proj=stere +lat_0=90 +lon_0=-90 +lat_ts=70 +ellps=WGS84 +datum=WGS84 +units=m +nadgrids=@null +no_defs', [0, 0]);
```
Expected Output:
`[12330389.1844, -7.55018582346e-10]`
Actual Output:
`[NaN, NaN]`

Not sure if I'm mis-understanding something in the projections, Proj4JS itself, or it this is a bug.

Any help appreciated.

**Comment by calvinmetcalf** [comment]
a couple questions

1. how are you generating the expected output?
2. is that a particular epsg code you are projecting too (mainly wondering if it's valid at 0,0)

**Comment by ISNIT0** [comment]
I was using this tool to generate the expected output: https://mygeodata.cloud/cs2cs/
So it uses cs2cs rather than Proj4, but seems like it ought to work.

The projection is actually a rotated version of North Polar Stereographic (to be USA Centric)
I know for a fact that this is a valid bbox in the target projection `-11859062.5958848670,-10489090.3900000000,12525410.8000000000,7845100.1396310208`
Converting backwards I'm getting one NaN:
```javascript
proj4('+proj=stere +lat_0=90 +lon_0=-90 +lat_ts=70 +ellps=WGS84 +datum=WGS84 +units=m +nadgrids=@null +no_defs','EPSG:4326', [-11859062.5958848670,-10489090.3900000000]); // [NaN, -572900.4993513102]
```

**Comment by calvinmetcalf** [comment]
cs2cs is fine, I was wondering about the areas just because `-7.55018582346e-10` isn't a particularly great result, while not necessarily wrong suggest things are a bit wonky, and you didn't answer my question about it being valid at 0,0 lat long because the standard one isn't valid there.

**Comment by ISNIT0** [comment]
Agreed, I've tried with a few different coordinate pairs (grabbed from https://epsg.io/map).

All I know for sure is that the bbox above is working for generating a map and I'm trying to convert from some normalish projection to it. It may be that the projection doesn't directly map?

**Comment by fkrauthan** [comment]
I am having a similar issue for `+proj=stere +lat_0=90 +lat_ts=60`. My call is

```js
const lat = 54.0271667;
const lon = -132.125;
console.log(proj4("+proj=stere +lat_0=90 +lat_ts=60", [lat, lon]));
```

But it returns `[NaN, NaN]`

**Comment by ahocevar** [comment]
The coordinate order is `[lon, lat]`, not `[lat, lon]`.

**Comment by fkrauthan** [comment]
@ahocevar I've tried that as well but it returns the same result

**Comment by fkrauthan** [comment]
After a little bit of debugging it seems like the issue is that `this.long0` is `undefined` which in return makes the result `NaN` maybe that helps someone?

**Comment by MHBalsmeier** [comment]
Is someone still working on this? I am facing the same problem.
