### ISSUE TITLE
Add Equal Earth projection

### ISSUE THREAD

**Issue by berniejenny** [proj4js/proj4js#295]
Equal Earth is a projection inspired by the Robinson projection, but unlike the Robinson projection retains the relative size of areas. The projection is described in this publication:

Bojan Savric, Tom Patterson & Bernhard Jenny (2018).
The Equal Earth map projection.
International Journal of Geographical Information Science.
[http://doi.org/10.1080/13658816.2018.1504949](http://doi.org/10.1080/13658816.2018.1504949)

Java code is available here: [https://github.com/OSUCartography/JMapProjLib/blob/master/src/com/jhlabs/map/proj/EqualEarthProjection.java](https://github.com/OSUCartography/JMapProjLib/blob/master/src/com/jhlabs/map/proj/EqualEarthProjection.java)

**Comment by berniejenny** [comment]
A JavaScript version is available here:
[https://github.com/mbloch/mapshaper-proj/issues/8](https://github.com/mbloch/mapshaper-proj/issues/8)

**Comment by calvinmetcalf** [comment]
what are the parameters? do you have an example .prj file or proj string? do you have examples of data points that can be added as tests ?
