### ISSUE TITLE
 Unsupported Robinson projection in proj4js with Pro4Leaflet?  

### ISSUE THREAD

**Issue by jgiraldointegro** [proj4js/proj4js#297]
Hi.

i'm working with Leaflet with tiled maps and i need project my map to Robinson Projection and dont works. example:

javacript code:
//Sphere Robinson
var crsR = new L.Proj.CRS('ESRI:53030', '+proj=robin +lon_0=0 +x_0=0 +y_0=0 +a=6371000 +b=6371000 +units=m +no_defs');
//--------------- Map Initialization -------------------
var map = L.map('map',{
        crs: crsR,
...
};

javascript error in console:
proj4-src.js:1366 Uncaught ESRI:53030

with only include the Robinson codes (SR-ORG:20, SR-ORG:8511, ESRI:53030 or ESRI:54030), the javascript code dont works.

Robinson projection is support by pro4js in the last version 2.4.4 or beforest versions?

really, thanks very much to who can help me;  who are expert.

**Comment by jgiraldointegro** [comment]
adjust comment

**Comment by jgiraldointegro** [comment]
Javascript detail error, with Robinson code 53030:

proj4-src.js:1366 Uncaught ESRI:53030
Projection$1.callback @ proj4-src.js:1366
Projection$1 @ proj4-src.js:1376
Projection$1 @ proj4-src.js:1362
checkProj @ proj4-src.js:1894
proj4$1 @ proj4-src.js:1897
_projFromCodeDef @ proj4leaflet.js:56
initialize @ proj4leaflet.js:29
e @ leaflet.js:5
initialize @ proj4leaflet.js:83
e @ leaflet.js:5
(anonymous) @ leaftlet.js:367


(codes lines that generate error)

**Comment by calvinmetcalf** [comment]
ok published version 2.5.0 should include robinson

**Comment by jgiraldointegro** [comment]
Ohhh thanks very very much!

you can tell me please, when aprox shoul be release this version ?

**Comment by calvinmetcalf** [comment]
approximately 15 minutes ago

**Comment by jgiraldointegro** [comment]
uhhh Thanks very very much!

fraternal greeting from Colombia!

**Comment by jgiraldointegro** [comment]
I tested my Web App and is works with the Robinson Projection.

Again. Thanks very much
