### ISSUE TITLE
proj4 modify the input object after a transformation

### ISSUE THREAD

**Issue by alexroat** [proj4js/proj4js#306]
transforming from 
`"EPSG:25832":"+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",`
to
`"EPSG:4326":"+proj=longlat +datum=WGS84 +no_defs",`

From chrome console
```
>a={x:11,y:46}
{x: 11, y: 46}
>b=proj4(epsg["EPSG:4326"],epsg["EPSG:25832"],a)
{x: 654863.5734044344, y: 5095992.170781133}
>b
{x: 654863.5734044344, y: 5095992.170781133}
>proj4(epsg["EPSG:25832"],epsg["EPSG:4326"],b)
{x: 10.999999999999998, y: 45.99999999999999}
>b
{x: 0.1919862177193762, y: 0.8028514559173915}
```

the object pointed by b has been modified. I have not found evidence of this in the doc.
I've solved cloning the input object.
Anyway it could be source of dangerous bug, it took me several hours of debugging because it happen only in some transformations.

**Comment by oobayly** [comment]
I'm glad I'm not the only one who wasted time on this. I can see no reason why this should be still present, especially as it's undocumented behaviour.

Anyhow, I'm putting a PR together for it.
