### ISSUE TITLE
Only latitude, not longitude coordinates converted on some datum transformations

### ISSUE THREAD

**Issue by roryslatter** [proj4js/proj4js#310]
I have found that on some datum transformations, only the latitude coordinate (decimal degrees) is transformed, not the longitude one.
For example, from WGS84 > NAD27, with input 43.8 (lat) and -98.7 (lon), I get 43.802139... and -98.7
I have compared this against other tools such as GeoTrans and it doesn't seem to be correct.
Furthermore, I have tried with many different "from" datums, and they all just transform the latitude coordinate.
I'd appreciate any help that anyone can offer.

**Comment by ahocevar** [comment]
Note that the coordinate order is [longitude, latitude].

**Comment by roryslatter** [comment]
I have made sure to input them in that order. It is always the longitude (first) value that is not transformed

**Comment by roryslatter** [comment]
> I suspect [this code path](https://github.com/proj4js/proj4js/blob/a8815c4c7ed659c0218a0d82660cc26b81a52350/lib/datumUtils.js#L164-L168) might be the issue

Hi there,
Thanks for getting back to me.
Could you elaborate? I have gone through and traced the code execution to the snippet of code you referred to, the geocentric_to_geodetic() function, but I can't see what is causing the inputted longitude to stay the same.

Thanks in advance

**Comment by roryslatter** [comment]
Hi @mbloch 
That makes complete sense, thank you!
I'll work on getting the grid shifts now.

**Comment by calvinmetcalf** [comment]
grid shifts do not work with proj4js, that comment is incorrect

**Comment by calvinmetcalf** [comment]
@mbloch that isn't a terrible idea, I'm just afraid that there might be situations where people are transforming correctly but have some grid shift in there that doesn't do anything and having it error out will cause new errors to pop up

**Comment by roryslatter** [comment]
@calvinmetcalf I see, so my best bet, if I need grid shifts, is to install proj4 and call to that?

**Comment by roryslatter** [comment]
To anyone else looking at this thread who wants to do WGS84 to NAD27 in proj4js, if you add in the "towgs84" values into either the WKT or the proj.defs (whichever you use) you do not need to apply a grid shift as this approximates (very well) the values. I did find it very hard to locate the towgs84 values for a lot of datums, but for NAD27 they are (-8, 160, 176).
Therefore in WKT, directly after Spheroid you can add in ", TOWGS84[-8, 160, 176]"
Or add in "+towgs84=-8, 160, 176 " to your proj4js definition.

Tested against GeoTrans and ESRI, correct on both to 8 decimal places - hope this helps someone!

**Comment by mbloch** [comment]
These TOWGS84 parameters may be correct for one small region, but you won't have 8 decimal accuracy across the entire continent.

**Comment by roryslatter** [comment]
I've tested it across the entire continent and found no errors earlier than 6 decimal places compared to NAD27 CONUS in GeoTrans

**Comment by roryslatter** [comment]
Also, as I am implemented multiple different versions of NAD27, this is OK for me - but its a good point to let people know that it won't be perfect, as it is just an approximation of the grid shift
