### ISSUE TITLE
Invalid coordinate transform from lon/lat to utm

### ISSUE THREAD

**Issue by krojew** [proj4js/proj4js#315]
When converting longitude -12.314244/latitude -57.128912 to UTM using given strings: `proj4('+proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees', '+proj=utm +zone=21 +ellps=WGS84 +datum=WGS84 +units=m +no_defs', [ lon, lat ])`, the resulting northing is -1361305.8772874742 instead of 8638694.12.

**Comment by josueggh** [comment]
I just write a[ list with EPSG values for proj4](https://github.com/josueggh/proj4-list).
Many of the errors are provoked for a bad definition. 

```javascript
proj4.defs([
  proj4list["EPSG:4326"],
  proj4list["EPSG:32721"],
]);
proj4("EPSG:4326", "EPSG:32721", [ -57.128912 , -12.314244 ]
```
The final result is  `[ 485983.21092667704, 8638694.122712526 ]` as you we're expecting

**Comment by ahocevar** [comment]
Thanks @josueggh, so I think we can close this. The definition of EPSG:32721 in your list is the same as http://epsg.io/32721, the one in the description of this ticket is obviously not (missing `+south`).
