### ISSUE TITLE
remove reliance on es6 json import through bundler plugin

### ISSUE THREAD

**Issue by atepoorthuis** [proj4js/proj4js#325]
First of all, thanks so much for your great work on bring proj to the js realm!

The current version of `proj4js` is derived directly from `package.json`:
https://github.com/proj4js/proj4js/blob/6b33614eabbe2f1fc112bbb79d540ab25e2a650e/lib/version.js#L1

However, ES6 imports do not allow direct import from json files so this makes the project rely on bundler plugins to do so. This is perhaps defensible for direct consumers of `proj4js` but also affects consumers of other projects that have in turn `proj4js` as a dependency. In other words, everything downstream from `proj4js` will have to use a json bundler plugin, or use a prebuild version. It looks like issues related to this come up from time to time as well (#309, #261).

**Comment by ahocevar** [comment]
Fixed with #326.
