### ISSUE TITLE
Proj4js outputting x,y,z coords from x,y input

### ISSUE THREAD

**Issue by virtualarchitectures** [proj4js/proj4js#334]
I've set up a Node-Red node [node-red-contrib-proj4](https://github.com/virtualarchitectures/node-red-contrib-proj4/blob/master/proj4/proj4.js) wrapping Proj4js. On some instances proj4 unexpectedly outputs 3D coordinates from 2D inputs. For example: passing the JSON object `{"x":-0.12793738,"y":51.507747}` to the function and converting EPSG:4326 to EPSG:27700  (OGC WKT Strings) outputs the following object `{x: -6.260487456766799, y: 53.34982602497782, z: 53.59971942380071}`. Please confirm under what conditions the `proj4()` is expected to output three coordinates.

**Comment by virtualarchitectures** [comment]
Hi, this looks like it could be related to issue #327 where xyz parsing was implemented to add geocentric projections. I'm guessing this is happening because a default `0` is applied to the `z` variable in transform.js`. I might have misunderstood but it seems to imply that and input x,y values will generate a z  value as an artefact.

**Comment by virtualarchitectures** [comment]
Until this behaviour is documented can you recommend a version to rollback my dependencies to?

**Comment by ahocevar** [comment]
v2.5.0 should work for you then. But I don’t think #327 is related. If I’m right, then v2.6.0 should also work fine. If not, can you provide a test case so we can locate the issue and fix it?

**Comment by virtualarchitectures** [comment]
Thanks for looking at the query. Downgrading my dependencies to v2.5.0 does result in the behaviour I'd expected based on the documentation: Supplying X,Y values for the following `proj('EPSG:4326','EPSG:27700',{'x':-0.12793738,'y':51.507747})` outputs `{x: 530018.229301635,y: 180418.4380560558}`. Upgrading back to v2.6.0 and providing the same input results in the following output: `{x: 530018.229301635,y: 180418.4380560558,z: -46.121665578335524}`. I'll try 2.6.0 on my Node.js server to see if I can reproduce the issue outside of Node-Red and provide that test case.

**Comment by ahocevar** [comment]
Strange. I just tried your example with v2.6.0 and v2.5.0, and both return the same `z` value. Can you please double-check which version you have that does not return a z?

This is the test case I used:
```diff
diff --git a/test/test.js b/test/test.js
index e9ce3ce..8bd4785 100644
--- a/test/test.js
+++ b/test/test.js
@@ -171,6 +171,13 @@ function startTests(chai, proj4, testPoints) {
       });
     });
     describe('points', function () {
+      it('should not create a z if none was provided', function() {
+        const epsg27700 = '+proj=tmerc +lat_0=49 +lon_0=-2 +k=0.9996012717 +x_0=400000 +y_0=-100000 +ellps=airy +towgs84=446.448,-125.157,542.06,0.15,0.247,0.842,-20.489 +units=m +no_defs';
+        const result = proj4('EPSG:4326', epsg27700, {x: -0.12793738, y: 51.507747});
+        assert.closeTo(result.x, 530018.2264236036, 1e-7);
+        assert.closeTo(result.y, 180418.4372411499, 1e-7);
+        assert.equal(result.z, undefined);
+      });
       it('should ignore stuff it does not know', function () {
         var sweref99tm = '+proj=utm +zone=33 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs';
         var rt90 = '+lon_0=15.808277777799999 +lat_0=0.0 +k=1.0 +x_0=1500000.0 +y_0=0.0 +proj=tmerc +ellps=bessel +units=m +towgs84=414.1,41.3,603.1,-0.855,2.141,-7.023,0 +no_defs';
```

**Comment by virtualarchitectures** [comment]
I noticed your example uses proj strings while I'm using OGC WKT strings as I've been advised to expect increased accuracy over proj strings. Has there been a change in the handling of WKT strings?

I ran the following test code on 2.5.0 and then 2.6.0. The first output two coords as expected while the second test output xyz. The script I ran is below.

`var proj4 = require("proj4")
proj4.defs([
	[
    'EPSG:4326', 'GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]]'],
	[
    'EPSG:27700', 'PROJCS["OSGB 1936 / British National Grid",GEOGCS["OSGB 1936",DATUM["OSGB_1936",SPHEROID["Airy 1830",6377563.396,299.3249646,AUTHORITY["EPSG","7001"]],AUTHORITY["EPSG","6277"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4277"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",49],PARAMETER["central_meridian",-2],PARAMETER["scale_factor",0.9996012717],PARAMETER["false_easting",400000],PARAMETER["false_northing",-100000],AUTHORITY["EPSG","27700"],AXIS["Easting",EAST],AXIS["Northing",NORTH]]'
    ]
]);
var firstProjection = 'EPSG:4326';
var secondProjection = 'EPSG:27700';
var input_coords = {"x":-0.12793738,"y":51.507747};
var output_coords;
console.log('Converting from ' + firstProjection + ' to ' + secondProjection);
console.log('Input Coords: ' + input_coords);
output_coords = proj4(proj4.defs[firstProjection],proj4.defs[secondProjection],input_coords);
console.log(output_coords);`

For reference I attached the console log below:

![Proj4_Test](https://user-images.githubusercontent.com/10799911/69180451-362ecc00-0b05-11ea-963f-00cc35fc50ec.PNG)

**Comment by ahocevar** [comment]
@virtualarchitectures Can you please test if #335 fixes your issue?

**Comment by virtualarchitectures** [comment]
@ahocevar Thanks for sending that over. The fix seems to have it covered. Do you have a planned patch release schedule? More generally, nice to see 3D parsing available as a feature. Could be good to get an update on the Proj4js readme. I imagine its useful for frameworks like Cesium and Potree. I've mostly worked in Unity to date, but I'd be interested to start taking advantage of it Proj4js for web-based AR/VR.

**Comment by ahocevar** [comment]
A documentation (README) pull request would be much appreciated. Then I could do a patch release within a few days.

**Comment by virtualarchitectures** [comment]
Submitted a pull request to the 'only output z branch'. If there's any further functionality I'm not clear what suitable data and test cases would be so I'll have to leave that with you guys. Hope what I proposed is useful though.
