### ISSUE TITLE
Coordinate transformation results are different between Proj4JS and pyproj

### ISSUE THREAD

**Issue by originlake** [proj4js/proj4js#351]
When I'm trying to transform coordinates from epsg:26730 to epsg:3857, I noticed a big difference of the results between proj4js and pyproj. The proj4js version is 2.6.2 
```
import * as proj4 from 'proj4';

//https://epsg.io/26730
proj4.defs("EPSG:26730","+proj=tmerc +lat_0=30 +lon_0=-87.5 +k=0.999933333 +x_0=152400.3048006096 +y_0=0 +datum=NAD27 +units=us-ft +no_defsfs");

console.debug(proj4("EPSG:26730", "EPSG:3857", [711039.588, 1131639.859]))
// output: [ -9663735.534670355, 3909809.9893874573 ]
```
While in pyproj and epsg.io/transform, the result is [-9663734.18, 3909825.76]
[epsg.io/transform](http://epsg.io/transform#s_srs=26730&t_srs=3857&x=711039.5880000&y=1131639.8590000)
There is around 10 meters difference between two transformations.

**Comment by ahocevar** [comment]
proj4.js does not support grid shift transforms, which would be required to get the more accurate result you were seeing on epsg.io/transform.

**Comment by originlake** [comment]
@ahocevar Is there any way to work around? I need high accuracy for the transform

**Comment by ahocevar** [comment]
@originlake Not with a JavaScript library that I know of. Also https://npmjs.com/package/mproj does not support grid transforms.

**Comment by originlake** [comment]
@ahocevar We planned to do it from backend, thanks anyway.
