### ISSUE TITLE
Axis inversion issue

### ISSUE THREAD

**Issue by manthey** [proj4js/proj4js#352]
Prior to PR #344, you could invert a coordinate by transforming between, for instance `+proj=longlat +axis=esu` and `+proj=longlat +axis=enu`.  Although that PR made it so you can change the axis order, the coordinates are no longer inverted for `w` and `s`.  Oddly, the `d` axis still inverts.

I think the fix would be to restore the case statements that were processed in `lib/adjust_axis.js` (revert some of the changes in commit 3eda40c15d822ef674470e34b8e02aa4ab39257f).

**Comment by ahocevar** [comment]
@manthey That sounds like a reasonable fix. If you could create a pull request, that would be great. Make sure to also add tests for the `w` and `s` axis conversions, to avoid future regressions.
