### ISSUE TITLE
transform has a error : Cannot read property '0' of undefined     at adjust_axis

### ISSUE THREAD

**Issue by Luooooooo** [proj4js/proj4js#355]
mycode:
```js
proj4.defs("EPSG:2344","+proj=tmerc +axis=enu +lat_0=0 +lon_0=113.5 +k=1 +x_0=100000 +y_0=-2800000 +a=6378140 +b=6356755.288157528 +units=m +no_defs");

proj4.transform("EPPG:2344","EPSG:3857",[51607.2879886125,53711.6692186741])
```
it can't get the 'axis '
![image](https://user-images.githubusercontent.com/29565303/86872932-e04c7a00-c10f-11ea-9b14-0f67031c8d93.png)

**Comment by ahocevar** [comment]
Not only that you have a typo,

    proj4.transform("EPPG:2344","EPSG:3857",[51607.2879886125,53711.6692186741]);
                       ^

you're also using the API incorrectly. To transform with codes, simply call

    proj4("EPPG:2344","EPSG:3857",[51607.2879886125,53711.6692186741]);

**Comment by Luooooooo** [comment]
ohhh,thanks! @ahocevar
