### ISSUE TITLE
Wrong results transforming coordinates from EPSG:2054 to WGS84

### ISSUE THREAD

**Issue by shayb-datumate** [proj4js/proj4js#365]
I'm having issues transforming coordinates from EPSG:2054 to WGS84. I'm using the proj4 string published in epsg.io and I'm getting what looks like the mirror image of the expected results (around both axis).

Here's a reproduction of the issue:
https://stackblitz.com/edit/js-hkstzo
![image](https://user-images.githubusercontent.com/52623423/99499676-eede5400-2981-11eb-9415-97c849b60284.png)

And here is the correct result, via epsg.io online transformation tool:
https://epsg.io/transform#s_srs=2054&t_srs=4326&x=29484.7580000&y=2804605.8990000
![image](https://user-images.githubusercontent.com/52623423/99499659-e6861900-2981-11eb-953a-374ae9b72901.png)

**Comment by ahocevar** [comment]
Thanks for reporting this, @shayb-datumate. Apparently something wrent wrong with the package creation when v2.6.2 was published. I just published v2.6.3, and now the results are correct: https://stackblitz.com/edit/js-qk9flc?file=index.js. Please verify.

**Comment by shayb-datumate** [comment]
It's working. Thanks for the very quick response! 🙏🏻
