### ISSUE TITLE
proj4(wkid, wkid, coordinates)  How to do that? proj4(3857, 4326, [-43, 23])

### ISSUE THREAD

**Issue by hoogw** [proj4js/proj4js#369]
I need project at runtime, means I can't pre-define projection like this

                      var firstProjection = 'PROJCS["NAD83 / Massachusetts Mainland",GEOGCS["NAD83",DATUM["North_American_Datum_1983",SPHEROID["GRS 1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],AUTHORITY["EPSG","6269"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.01745329251994328,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4269"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",42.68333333333333],PARAMETER["standard_parallel_2",41.71666666666667],PARAMETER["latitude_of_origin",41],PARAMETER["central_meridian",-71.5],PARAMETER["false_easting",200000],PARAMETER["false_northing",750000],AUTHORITY["EPSG","26986"],AXIS["X",EAST],AXIS["Y",NORTH]]';
                      var secondProjection = "+proj=gnom +lat_0=90 +lon_0=0 +x_0=6300000 +y_0=6300000 +ellps=WGS84 +datum=WGS84 +units=m +no_defs";

I get 2 wkid from rest api at runtime, need project, but how without projection define?

                      proj4(wkid, wkid, coordinates)  

                     How to do that? 

                     proj4(3857, 4326, [-43, 23])

**Comment by ahocevar** [comment]
The proj string is enough for a projection definition. You can use it directly:
```js
proj4(firstProjection, secondProjection, [-43, 23]);

**Comment by hoogw** [comment]
I don't know the projection string, how to do it?
For example, from wkid(1234) to 5678,  I get 1234, 5678 from a https ajax rest api, at runtime, 
it could be 7897 to 5674 in next second, how to look up definition string at runtime? 
               
               proj4(1234, 5678, [-43, 23]);

**Comment by hoogw** [comment]
if from to is fixed, that will be easy, from 4326 to 3857, I could write down definition string. 
the problem is if from to is as input from user side,  user want to from 1234 to 5678, 
user don't give define string, only wkid 1234,  how to write a js code to look up the define string based on user input?
user input 3857, js code should automatically generate or look up its define string, but how?

**Comment by hoogw** [comment]
I know arcgis js api 'project' class can do client side project, which you input any 2 wkid (from,to), they will project for you at client browser.   [https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/introducing-the-client-side-projection-engine/](https://www.esri.com/arcgis-blog/products/js-api-arcgis/mapping/introducing-the-client-side-projection-engine/)

I had tried this one, it works just fine. 

Server side project, not recommended, because if the remote arcgis geometry server is down, then your ajax request will fail.

The need is user input any 2 wkid, and lat lng, then get result, without define projection string

            proj4(1234, 5678, [-43, 23]);

1234, 5678 are wkid input by user at runtime,  means user can input any wkid, I know some pre-defined wkid are ok, 4326, but not any wkid, I believe if some wkid you need to somehow look up find the define string, before use it.

**Comment by ahocevar** [comment]
You can use an API, e.g. https://spatialreference.org/ref/epsg/4326/proj4/ or https://epsg.io/4326.proj4

**Comment by hoogw** [comment]
Wonderful ! Perfect  that works for me. 

If somehow you could do magic to include that library into this proj4js, no more http request needed, that will be the ultimate perfect.

**Comment by ahocevar** [comment]
That magic does not belong into the library. But with async/await, you should be able to achieve what you need with less than 10 lines of code.

**Comment by hoogw** [comment]
Ok, got it. I will run a complete test of your idea, make sure the performance. 
I will post the result here in a few days. 

This library is essential tool, I use it a lot to do client side project.  
It is a MUST have tool to do browser mapping web page.
Appreciate your effort to make it happen.

**Comment by hoogw** [comment]
I try to get 3857 ( esri arcgis server prefered wkid) or ESRI's id is 1021000
I get error, 
https://spatialreference.org/ref/epsg/3857/proj4/
however, this one works
https://spatialreference.org/ref/epsg/26917/proj4/

However, in another attempt, I do get something.
https://spatialreference.org/ref/sr-org/epsg3857-wgs84-web-mercator-auxiliary-sphere/proj4js  

                  Proj4js.defs["SR-ORG:7483"] = "+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs";

attempt#3: 

all works
             https://epsg.io/3857.proj4
             https://epsg.io/26917.proj4

for proj4js only, all works
 https://epsg.io/3857.js
 https://epsg.io/26917.js

Summary:
               not usable,  some id are unavailable (above see 3857)
                    https://spatialreference.org
                         

         usable:  

          https://epsg.io/your-wkid-here.js

**Comment by hoogw** [comment]
I complete test, it works,  use ajax below , get definition string, then 

                    https://epsg.io/your-wkid-here.js 


here is my complete code:

                                          //  https://epsg.io/your-wkid-here.js      
                          //  must use latestWkid, it is EPSG:3857, Do not use _wkid, it is ESRI wkid 1021000, both are same, but https://epsg.io/ only accept EPSG wkid, not ESRI wkid
                          var wkid_definition_url = 'https://epsg.io/' + _latestWkid + '.js';  
                          var wkid_definition_string;
                         
                          console.log('_InUse_Extent .....',_InUse_Extent)
                          console.log('wkid_definition_url.....',wkid_definition_url)
                          


                         
                          wkid_definition_string = await $.ajax({
                                
                                                timeout: _timeout,
                                                type: 'GET',
                                                //dataType: 'jsonp',
                                                data: {},
                                                url: wkid_definition_url,
                                                // Type: Function( jqXHR jqXHR, String textStatus, String errorThrown )
                                                                                            error: function (jqXHR, textStatus, errorThrown) {
                                                                                                          // ajax failed
                                                                                                  var _error_status = textStatus + ' : ' + errorThrown         
                                                                                              //  console.log('ajax error  + ', _error_status)
                                                                                                console.log('ajax error  + ', textStatus,errorThrown )
                                                                                            },

                                                success: function (data) {
                                                 //   console.log('epsg wkid definition string back', data);
                                                    // note: data is already json type, you just specify dataType: jsonp
                                                    //return data;
                                                }
                                            });                          
                            
                                            
                                          
                        /*  both works
                            fetch(wkid_definition_url)
                                           .then(response => response.text())
                                           .then(
                                                   data =>  console.log('epsg wkid definition string back', data)
                                           );

                        */


                          // warn: returning string have proj4.defs(....)
                          //     proj4.defs("EPSG:3857","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs");                                      
                          console.log('wkid_definition_string  .....',  wkid_definition_string)
                          // run this string as code :   eval('proj4.defs("EPSG:3857","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs");      ')
                          eval(wkid_definition_string)

                          
                        
                          var from_epsg = 'EPSG:'+ _latestWkid  // must use latestWkid, it is EPSG:3857, Do not use _wkid, it is ESRI wkid 1021000, both are same, but https://epsg.io/ only accept EPSG wkid, not ESRI wkid
                         
                          proj4.defs([
                                          [ 'EPSG:4326',     '+title=WGS 84 (long/lat) +proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees']
                                          //[ from_epsg,        wkid_definition_string]
                                      ]);
                          

                          //Coordinates may an object of the form {x:x,y:y} or an array of the form [x,y].
                          //proj4(fromProjection[, toProjection, coordinates])
                          _reprojected_lat_lng = proj4(from_epsg, 'EPSG:4326', [_xmiddle, _ymiddle])


                          
                              /*
                                  _reprojected_lat_lng =  [x, y]  [lng, lat]
                              */
                          
                              var _c_lat = _reprojected_lat_lng[1];
                          
                              var _c_long = _reprojected_lat_lng[0];
                            
                              console.log( 'center lat: ', _c_lat,  'center long: ',_c_long)
                            
                            
                              return {"_center_lat":_c_lat, "_center_long":_c_long, "_center_zoom" : default_center_zoom};

**Comment by hoogw** [comment]
more code, get center long lat (project to 4326 ) from arcgis server rest api

                                          
               // pro4js --> ajax https://epsg.io/your-wkid-here.js  get definition string,    https://github.com/proj4js/proj4js/issues/369 
               // from custom projection to 4326
                async function proj4js_centerLatLong(_input){
                    
                    
                  var _reprojected_lat_lng;
                    
                    
                  // ============= calculate center_lat and center_long ===================
                          
                      
                  
                                      /*

                                              // also works at https://developers.arcgis.com/rest/services-reference/project.htm
                                              // var _projection_server_url = 'https://sampleserver6.arcgisonline.com/arcgis/rest/services/Utilities/Geometry/GeometryServer/project?';

                                              all 3 kind of extent works, just choose one of them  
                                        
                                                    "extent": {
                                                        "xmin": 1440000,
                                                        "ymin": 535000,
                                                        "xmax": 1455000,
                                                        "ymax": 550000,
                                                        "spatialReference": {
                                                            "wkid": 102719,
                                                            "latestWkid": 2264
                                                        }
                                                    },



                                                    "initialExtent": {
                                                        "xmin": 1440000,
                                                        "ymin": 535000,
                                                        "xmax": 1455000,
                                                        "ymax": 550000,
                                                        "spatialReference": {
                                                            "wkid": 102719,
                                                            "latestWkid": 2264
                                                        }
                                                    },



                                                    "fullExtent": {
                                                        "xmin": 1440000,
                                                        "ymin": 535000,
                                                        "xmax": 1455000,
                                                        "ymax": 550000,
                                                        "spatialReference": {
                                                            "wkid": 102719,
                                                            "latestWkid": 2264
                                                        }
                                                    },
                                                    

                                              
                                        
                                        */
                                        
                                      


                  
                  
                      // only xxx/MapServer have initialExtent, the other FeatureServer, ImageServer do NOT have it. 
                      
                      if(_input.hasOwnProperty('initialExtent') && (_input.initialExtent.spatialReference.hasOwnProperty('wkid'))){
              
                          
                          var _InUse_Extent = _input.initialExtent;
                              
                          var _spatialReference = _InUse_Extent.spatialReference;
                          
                          //  need more work, some do not have wkid, but have wkt
                          // "wkt":"PROJCS[\"NAD_1983_StatePlane_Michigan_South_FIPS_2113_IntlFeet\",GEOGCS[\"GCS_North_American_1983\",DATUM[\"D_North_American_1983\",SPHEROID[\"GRS_1980\",6378137.0,298.257222101]],PRIMEM[\"Greenwich\",0.0],UNIT[\"Degree\",0.0174532925199433]],PROJECTION[\"Lambert_Conformal_Conic\"],PARAMETER[\"False_Easting\",13123359.58005249],PARAMETER[\"False_Northing\",0.0],PARAMETER[\"Central_Meridian\",-84.36666666666666],PARAMETER[\"Standard_Parallel_1\",42.1],PARAMETER[\"Standard_Parallel_2\",43.66666666666666],PARAMETER[\"Latitude_Of_Origin\",41.5],UNIT[\"Foot\",0.3048]]"}}
                          //sample:  https://sampleserver3.arcgisonline.com/ArcGIS/rest/services/BloomfieldHillsMichigan/Parcels/MapServer?f=json
                          
                          var _wkid = _spatialReference.wkid;  // ESRI wkid 1021000
                              
                          var _latestWkid = _spatialReference.latestWkid;   // EPSG:3857
                          
                          var _xmin = _InUse_Extent.xmin;
                          var _ymin = _InUse_Extent.ymin;
                          var _xmax = _InUse_Extent.xmax;
                          var _ymax = _InUse_Extent.ymax;
                          
                          
                          var _xmiddle = (_xmax - _xmin) / 2 + _xmin;
                          var _ymiddle = (_ymax - _ymin) / 2 + _ymin;
                          
                          //  https://epsg.io/your-wkid-here.js      
                          //  must use latestWkid, it is EPSG:3857, Do not use _wkid, it is ESRI wkid 1021000, both are same, but https://epsg.io/ only accept EPSG wkid, not ESRI wkid
                          var wkid_definition_url = 'https://epsg.io/' + _latestWkid + '.js';  
                          var wkid_definition_string;
                         
                          console.log('_InUse_Extent .....',_InUse_Extent)
                          console.log('wkid_definition_url.....',wkid_definition_url)
                          


                         
                          wkid_definition_string = await $.ajax({
                                
                                                timeout: _timeout,
                                                type: 'GET',
                                                //dataType: 'jsonp',
                                                data: {},
                                                url: wkid_definition_url,
                                                // Type: Function( jqXHR jqXHR, String textStatus, String errorThrown )
                                                                                            error: function (jqXHR, textStatus, errorThrown) {
                                                                                                          // ajax failed
                                                                                                  var _error_status = textStatus + ' : ' + errorThrown         
                                                                                              //  console.log('ajax error  + ', _error_status)
                                                                                                console.log('ajax error  + ', textStatus,errorThrown )
                                                                                            },

                                                success: function (data) {
                                                 //   console.log('epsg wkid definition string back', data);
                                                    // note: data is already json type, you just specify dataType: jsonp
                                                    //return data;
                                                }
                                            });                          
                            
                                            
                                          
                        /*  both works
                            fetch(wkid_definition_url)
                                           .then(response => response.text())
                                           .then(
                                                   data =>  console.log('epsg wkid definition string back', data)
                                           );

                        */


                          // warn: returning string have proj4.defs(....)
                          //     proj4.defs("EPSG:3857","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs");                                      
                          console.log('wkid_definition_string  .....',  wkid_definition_string)
                          // run this string as code :   eval('proj4.defs("EPSG:3857","+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs");      ')
                          eval(wkid_definition_string)

                          
                        
                          var from_epsg = 'EPSG:'+ _latestWkid  // must use latestWkid, it is EPSG:3857, Do not use _wkid, it is ESRI wkid 1021000, both are same, but https://epsg.io/ only accept EPSG wkid, not ESRI wkid
                         
                          proj4.defs([
                                          [ 'EPSG:4326',     '+title=WGS 84 (long/lat) +proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees']
                                          //[ from_epsg,        wkid_definition_string]
                                      ]);
                          

                          //Coordinates may an object of the form {x:x,y:y} or an array of the form [x,y].
                          //proj4(fromProjection[, toProjection, coordinates])
                          _reprojected_lat_lng = proj4(from_epsg, 'EPSG:4326', [_xmiddle, _ymiddle])


                          
                              /*
                                  _reprojected_lat_lng =  [x, y]  [lng, lat]
                              */
                          
                              var _c_lat = _reprojected_lat_lng[1];
                          
                              var _c_long = _reprojected_lat_lng[0];
                            
                              console.log( 'center lat: ', _c_lat,  'center long: ',_c_long)
                            
                            
                              return {"_center_lat":_c_lat, "_center_long":_c_long, "_center_zoom" : default_center_zoom};
                            
                            
                          }//  input.hasOwnProperty('initialExtent')
                          
                          else {
                              // no initialExtent
                                // only xxx/MapServer have initialExtent, the other FeatureServer, ImageServer do NOT have it. 
                                //default to Los Angeles 
                                
                              


                              return {"_center_lat": default_center_lat, "_center_long": default_center_long, "_center_long": default_center_zoom};
                          }
                          
                          
                          
                          
                          // =============  End ============= calculate center_lat and center_long  =============
                  
                  
                  
                  
              } 
              
              //   *** ***** *******  server side projection  *** ***** *******
