### ISSUE TITLE
Error when converting EPSG:3168

### ISSUE THREAD

**Issue by unknowdata** [proj4js/proj4js#375]
I tried to convert with 
+proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257905 +k=0.99984 +x_0=804670.24 +y_0=0 +no_uoff +gamma=323.1301023611111 +a=6377295.664 +b=6356094.667915204 +units=m +no_defs 
but result is way off.

However, one on epsg.io is correct.

**Comment by ahocevar** [comment]
Please provide example coordinates with the expected result. Also, provide the complete url you used to test the conversion on epsg.io.

**Comment by unknowdata** [comment]
https://epsg.io/3168
proj4.defs("EPSG:3168","+proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257905 +k=0.99984 +x_0=804670.24 +y_0=0 +no_uoff +gamma=323.1301023611111 +a=6377295.664 +b=6356094.667915204 +units=m +no_defs");

https://epsg.io/transform#s_srs=4326&t_srs=3168&x=101.7108894&y=10.0060703
Long: 101.7108895
Lat: 10.0060703

via EPSG.io
X: 414290.16
Y: 1106912.8

Converting via proj4js instead returns
X: 744896.0367651524
Y: 664384.3852478617

**Comment by ahocevar** [comment]
This issue would be fixed by #350, but that pull request breaks existing tests that need to be checked first.

**Comment by unknowdata** [comment]
Thank you so much!

Btw I will also need to use it in the browser (as standalone proj4.js/proj4-src.js). If you can update it here too it would be really sweet
https://github.com/proj4js/proj4js/releases
