### ISSUE TITLE
Different results converting with proj4 string and WKT for EPSG 31370 - Belgian Lambert 1972

### ISSUE THREAD

**Issue by JackClouseau** [proj4js/proj4js#379]
I am getting different results if I convert the same point using proj4 string and WKT for EPSG 31370.

FromPoint = 4.477591, 51.015733

var proj4str = '+proj=lcc +lat_1=51.16666723333333 +lat_2=49.8333339 +lat_0=90 +lon_0=4.367486666666666 +x_0=150000.013 +y_0=5400088.438 +ellps=intl +towgs84=-106.869,52.2978,-103.724,0.3366,-0.457,1.8422,-1.2747 +units=m +no_defs'

var wkt = 'PROJCS["Belge 1972 / Belgian Lambert 72",GEOGCS["Belge 1972",DATUM["Reseau_National_Belge_1972",SPHEROID["International 1924",6378388,297,AUTHORITY["EPSG","7022"]],TOWGS84[-106.8686,52.2978,-103.7239,0.3366,-0.457,1.8422,-1.2747],AUTHORITY["EPSG","6313"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4313"]],PROJECTION["Lambert_Conformal_Conic_2SP"],PARAMETER["standard_parallel_1",51.16666723333333],PARAMETER["standard_parallel_2",49.8333339],PARAMETER["latitude_of_origin",90],PARAMETER["central_meridian",4.367486666666666],PARAMETER["false_easting",150000.013],PARAMETER["false_northing",5400088.438],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["X",EAST],AXIS["Y",NORTH],AUTHORITY["EPSG","31370"]]'

**Using proj4str:**
proj4(proj4str ,[4.477591, 51.015733]);
Result:
157637.32019580694, 189509.05456724484

**Using WKT:**
proj4(wkt,[4.477591, 51.015733]);
157815.66658331238, 189567.89219647646

So, for the same point there is a shift of about 180 metres using the 2 different conversion methods.

The proj4str conversion yields the same result if I use **Proj.NET**, so it appears that is the correct result.

**Comment by ahocevar** [comment]
Duplicate of #377, fixed with #378 in v2.7.2

**Comment by JackClouseau** [comment]
I can confirm that this is now fixed.  Thanks for your support!
