### ISSUE TITLE
Build process

### ISSUE THREAD

**Issue by prushforth** [proj4js/proj4js#381]
I'm trying to build an earlier version of proj4js, because Leaflet doesn't deal with the latest version well.  I want to patch that version with a commit for laea from last year.

I've tried checking out the tag and building, but I can never re-generate the proj4-src.js that looks like what you've built. Specifically it still has "require" in it. So I tried to "derequire" it, but can't get rid of that root require business. 

Do you have a special command or a link you can refer me to; it would be appreciated.  Thanks!

**Comment by ahocevar** [comment]
To build the library, it should be enough to run

    npm install
    npm run build

from the root directory.

I'd be curious to hear where Leaflet does not deal well with the latest version.

**Comment by prushforth** [comment]
[Here](https://maps4html.org/experiments/custom-projections/esri-53032/) is a polar map (aeqd) using proj4 2.3.14.  You can zoom out and put your cursor anywhere no problem.  zooming in is never a problem - on earth.

[Here](https://maps4html.org/experiments/custom-projections/proj-2-6-2/) is the same map using proj4 2.6.2 If you zoom out, or move your pointer towards the origin, you'll get NaN errors in the console.

Both use our custom element which uses Leaflet 1.7.1 and proj4leaflet 1.0.2 to adapt proj4 to Leaflet.  So I don't know if it's actually Leaflet or proj4leaflet that is having the problem.  It's probably proj4leaflet, because they actually distribute a fixed version of both Leaflet and proj4js with their code and haven't updated for a couple of years.  

Unfortunately, downgrading to 2.3.14 isn't a panacea, because that version doesn't work with another polar projection that we want to support (laea), and although I understand the latest proj4js has some laea specific improvements, 2.6.2 [doesn't work](https://maps4html.org/experiments/custom-projections/Arctic-SDI/index.html)* with Leaflet, per the above, so I'm left between a rock and a hard place. That's why I wanted to try back-porting the laea improvement to 2.3.14.peter, but I gave that a whirl and it didn't work, probably for other reasons but perhaps mainly for the simple reason that I can't build the 2.3.14 tag and get a functioning artifact.

\* To view that example, unfortunately you have to go to a browser that will let you use plain http, because Chrome auto secures the page but the tiles are not offered over https.  Anyway it has a similar result to the other projection - points off the earth towards the tile origin return NaN, at least partially.

Building at the 2.3.14 tag isn't as simple as that; when I try the above:

```log
$ npm install
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

removed 47 packages in 3.412s

7 packages are looking for funding
  run `npm fund` for details


prushfor@DESKTOP-8T9A8T8 MINGW64 ~/Documents/GitHub/proj4js (m4h-2.3.14)
$ npm run build
npm ERR! missing script: build

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\prushfor\AppData\Roaming\npm-cache\_logs\2021-03-29T01_58_03_022Z-debug.log
```
If you use `grunt default` you get dist/proj4-src.js, but it's full of require('...'), and even if you run that output through derequire, the header that is generated is quite different than what was built in the dist directory of that tag (and it won't run when I use it in our project).  So I gave up until my knowledge increases.

Thanks for listening!

**Comment by ahocevar** [comment]
The NaN coordinates are a consequence of attempts to transform coordinates that are outside the validity range of the projection. You'll probably need to use `setMaxBounds` on the Leaflet map to an appropriate extent to avoid tile coordinate calculations where all or some corner coordinates are outside the validity range.

**Comment by prushforth** [comment]
Agreed, but it's odd that the old version of proj4 works ok (even out of bounds) with the same stack but the newer proj4 version yields the NaN errors in leaflet/proj4leaflet. May be something about a new way of proj4 reporting those conditions?

**Comment by prushforth** [comment]
Actually we were tinkering just now and we found that proj4leaflet is doing a `L.LatLng( point[1], point[0])` on the output from `proj4.inverse(...)`, which in earlier proj4 was returned as a zero but in later proj4 is returned as `NaN`, so the `L.LatLng` throws because it's expecting you to pass it good stuff.  So I guess it's an issue of proj4leaflet after all.  Thanks for helping us out. I'll close this but if you have anything to add, please do.

**Comment by ahocevar** [comment]
The only thing I have to add is that in early versions of proj4js it was impossible to detect problems with transformed coordinates, because - as you found out - 0 was returned instead of NaN.

**Comment by prushforth** [comment]
Thanks for your help. I'll look into setting max bounds.

**Comment by prushforth** [comment]
Looks like `setMaxBounds` won't work, unless I don't understand something, which seems likely!   Max bounds takes only a `LatLngBounds`, which kind of boggles my mind when thinking about that data in a polar projection.  Is there a standard / common understanding for a bbox over a pole?  It would be easier to think about if it was settable in projected coordinates.

**Comment by prushforth** [comment]
Update: I found the[ idea you're referring to](https://leafletjs.com/reference-1.7.1.html#projection-bounds). Thanks, sorry for bugging you!
