### ISSUE TITLE
Converting data from Chang'e 2 data (moon mission) is not working unfortunately

### ISSUE THREAD

**Issue by CraigglesO** [proj4js/proj4js#382]
The dataset uses a modified mercator and polar stereographic projections

When I test points like this:

```js
proj4(
    'PROJCS["Moon_Mecator",GEOGCS["GCS_Moon_2000",DATUM["D_Moon_2000",SPHEROID["Moon_2000_IAU_IAG",1737400.0,0.0]],PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Mercator"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["Standard_Parallel_1",35.0],UNIT["Meter",1.0]]',
    '+title=WGS 84 (long/lat) +proj=longlat +ellps=WGS84 +datum=WGS84 +units=degrees',
    [x, y]
)
```

the conversions are definitely wrong.

I ran through all the `.tif` and `.prj` pulled their projection & bbox's, Converted them to WGS84 and got wonky results. When i console log proj4, it looks correct, so I can't figure out why the results are wrong.

**Comment by calvinmetcalf** [comment]
I'm not sure you're asking proj4 the question, what your doing currently is asking it to transform from Mercator (on the moon) to lat longs on earth, when what you probably want to do is turn it into lunar lat longs, maybe try converting to `GEOGCS["GCS_Moon_2000",DATUM["D_Moon_2000",SPHEROID["Moon_2000_IAU_IAG",1737400.0,0.0]],
PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]]`

**Comment by CraigglesO** [comment]
That makes more sense. However I am still getting roughly the same results:

![geo](https://user-images.githubusercontent.com/5249140/115612345-28144a80-a2b9-11eb-8be1-b571ef30f025.png)


Finally created a photo that might shed some light on the issue.

**Comment by calvinmetcalf** [comment]
it looking like the mercator stuff is too small which i'm guessing it's because the correct radius (which i believe is refereed to as `a` in the Mercator projection stuff) isn't being set correctly. I don't believe we've done much testing on non earth projections so this isn't totally surprising, I'm probably not going to be able to look into this any time soon so you might want to try the desk top version of proj if nobody else is able to look into this in the near future.

**Comment by CraigglesO** [comment]
Did some research, did the math myself ensuring the radius (a) was correct. I still got the same result. However, I noticed a variable that wasn't influencing the maths: `Standard_Parallel_1`.

According to some online resources for mercator this is equivalent to `lat_ts`. This value impacts `k` as seen [here](https://github.com/proj4js/proj4js/blob/master/lib/projections/merc.js#L19).

However, when checking on the projection after inserting the PRJ string, it had a `standard_parallel_1` variable but no `lat_ts` variable and `k` was 1 (which is wrong).

Can anyone confirm that for mercator `lat_ts` is `Standard_Parallel_1` ?

Thanks.

**Comment by CraigglesO** [comment]
From experimentation I am already getting values that make way more sense!

**Comment by calvinmetcalf** [comment]
whats the string for the polar stuff ?

**Comment by CraigglesO** [comment]
`PROJCS[" Stereographic_South_Pole",GEOGCS["GCS_Moon_2000",DATUM["D_Moon_2000",SPHEROID["Moon_2000_IAU_IAG",1737400.0,0.0]],PRIMEM["Reference_Meridian",0.0],UNIT["Degree",0.0174532925199433]],PROJECTION["Stereographic_South_Pole"],PARAMETER["False_Easting",0.0],PARAMETER["False_Northing",0.0],PARAMETER["Central_Meridian",0.0],PARAMETER["standard_parallel_1",-80.0],UNIT["Meter",1.0]]`

Was the same issue again. `standard_parallel_1` is not being pulled into `lat_ts`.

**Comment by CraigglesO** [comment]
It took time to prove everything was working as intended. I would pull in the `prj` files to parse and grab the `standard_parallel_1` and then create the projection strings as follows:

```js

if (pullProj.oProj.names.includes('stere')) {
    projString = `+proj=stere +lat_0=-90 +lat_1=0 +lat_ts=${pullProj.oProj.standard_parallel_1} +lon_0=0 +x_0=0 +y_0=0 +a=1737400 +b=1737400 +units=m +no_defs`
} else if (pullProj.oProj.names.includes('sterea')) {
    projString = `+proj=stere +lat_0=90 +lat_1=0 +lat_ts=${pullProj.oProj.standard_parallel_1} +lon_0=0 +x_0=0 +y_0=0 +a=1737400 +b=1737400 +units=m +no_defs`
} else if (pullProj.oProj.names.includes('Mercator')) {
    projString = `+proj=merc +lat_0=0 +lat_1=0 +lat_ts=${pullProj.oProj.standard_parallel_1} +lon_0=0 +x_0=0 +y_0=0 +a=1737400 +b=1737400 +units=m +no_defs`
}

```

Notice both the north and south polar projections both use `stere` with vertical offsets applied. Hopefully this saves a lot of pain for the next people who interact with either `standard_parallel_1` or the Chang'e 2 dataset.
