### ISSUE TITLE
Hermannskogel and Potsdam datums are using 3-parameter instead of 7-parameter Helmert transformation

### ISSUE THREAD

**Issue by rhuitl** [proj4js/proj4js#385]
We see a larger error of > 100 m when transforming between WGS 84 and EPSG:31256. These two datums are using the three-parameter Helmert transformation in Proj4JS. In Proj4 these have been changed many years ago to the seven parameter version.

https://github.com/OSGeo/PROJ/issues/207
https://github.com/OSGeo/PROJ/issues/115

Would you be willing to accept a pull request that changes these two?
Are there maybe more definitions that are outdated?

**Comment by ahocevar** [comment]
Proj4.js performs the transform with the data you provide. If you provide a 7-parameter transform, it will use that. Please share your code so we can verify that you are passing the correct configuration.

**Comment by rhuitl** [comment]
I'm referring to the case where I don't provide the parameters myself, but the `+datum`, like the EPSG:31256 definition from PostGIS' `spatial_ref_sys` database table:
```
+proj=tmerc +lat_0=0 +lon_0=16.33333333333333 +k=1 +x_0=0 +y_0=-5000000 +datum=hermannskogel +units=m +no_defs
```

I see that e.g. https://epsg.io/31256 has a different definition which is probably what you are referring to:
```
+proj=tmerc +lat_0=0 +lon_0=16.33333333333333 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs
```

So this would be about changing the parameters that are used when `+datum=hermannskogel` or `+datum=potsdam` is used to match the behavior of Proj4 4.8.0 onward.

**Comment by ahocevar** [comment]
Sounds good, please provide a pull request. Thanks in advance!
