### ISSUE TITLE
nadgrid not a type of @types/proj4

### ISSUE THREAD

**Issue by th30d0r** [proj4js/proj4js#388]
typescript does not recognize nadgrid as a property for proj4. The work around is to cast proj4 to any 

code:  proj4.nadgrid('key', buffer);

Property 'nadgrid' does not exist on type 'typeof proj4'.

**Comment by ahocevar** [comment]
Please submit a pull request or an issue to https://github.com/DefinitelyTyped/DefinitelyTyped.

**Comment by th30d0r** [comment]
Thanks

**Comment by th30d0r** [comment]
Yep, That is correct.
