### ISSUE TITLE
Proj4 js nadgrid transform does not take into account the nadgrid param

### ISSUE THREAD

**Issue by th30d0r** [proj4js/proj4js#389]
When using the js binding for proj4 with nadgrid param, the output coordinate transform is the same as without the nadgrid param in the proj4 string 

0. the proj4 string 
  customProj4 = +proj=tmerc +lat_0=52.3 +lon_0=-1.5 +k=1 +x_0=198873.0046 +y_0=375064.3871 +ellps=WGS84 +units=m 
  +no_defs  +nadgrids=key
1. Reading the gsb file into a buffer array
switchMap(gsbFileResp => {
  const buffer = gsbFileResp.arrayBuffer();
  return from(buffer);
 })
)
.subscribe(buffer => {
   (proj4 as any).nadgrid('key', buffer); // no errors
  }
  
transform code
proj4For3857 =  '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs',

proj4 ( proj4For3857, customProj4, coordinate)

The output transformed coordinate has a shift, and it is the same out as if I remove the nadgrid param from the custom proj4 string. So i assume that even though proj4 register the gsb file, when doing the proj transformation it does not take it into consideration

Using
 Angular 10
 proj4 2.7.4

**Comment by ahocevar** [comment]
You need to prefix the grid key with a `@`. In your def, it should be `+nadgrids=@key,null`. Also make sure you don't perform the transform before the key is registered - you're setting it asynchronously.

**Comment by th30d0r** [comment]
Even with the @ it does not work. The transform is done after the key is registered. I think i tracked it down to this area of the code in the datum_transform.js - which is where i assume the gridshift is happening. 

```
export default function(source, dest, point) {
  // Short cut if the datums are identical.
  if (compareDatums(source, dest)) {
    return point; // in this case, zero is sucess,
    // whereas cs_compare_datums returns 1 to indicate TRUE
    // confusing, should fix this
  }

  // Explicitly skip datum transform by setting 'datum=none' as parameter for either source or dest
  if (source.datum_type === PJD_NODATUM || dest.datum_type === PJD_NODATUM) {
    return point;
  }

  // If this datum requires grid shifts, then apply it to geodetic coordinates.
  var source_a = source.a;
  var source_es = source.es;
  if (source.datum_type === PJD_GRIDSHIFT) {
    var gridShiftCode = applyGridShift(source, false, point);
    if (gridShiftCode !== 0) {
      return undefined;
    }
    source_a = SRS_WGS84_SEMIMAJOR;
    source_es = SRS_WGS84_ESQUARED;
  }

  var dest_a = dest.a;
  var dest_b = dest.b;
  var dest_es = dest.es;
  if (dest.datum_type === PJD_GRIDSHIFT) {
    dest_a = SRS_WGS84_SEMIMAJOR;
    dest_b = SRS_WGS84_SEMIMINOR;
    dest_es = SRS_WGS84_ESQUARED;
  }
  
``` 

The    applyGridShift(source, false, point) function is not called because it exits the function here
 // Explicitly skip datum transform by setting 'datum=none' as parameter for either source or dest
  if (source.datum_type === PJD_NODATUM || dest.datum_type === PJD_NODATUM) {
    return point;
  }

**Comment by th30d0r** [comment]
Yep I just tested this. If i provide the from proj4 string of 27700 the transform works perfectly. However It cannot convert points from 3857

**Comment by ahocevar** [comment]
What happens if you change that snippet you cited above to
```js
  // Explicitly skip datum transform by setting 'datum=none' as parameter for either source or dest
  if (source.datum_type === PJD_NODATUM && dest.datum_type !== PJD_GRIDSHIFT || dest.datum_type === PJD_NODATUM && screen.datum_type !== PJD_GRIDSHIFT) {
    return point;
  }
```
?

**Comment by utraum** [comment]
> What happens if you change that snippet you cited above to
> 
> ```js
>   // Explicitly skip datum transform by setting 'datum=none' as parameter for either source or dest
>   if (source.datum_type === PJD_NODATUM && dest.datum_type !== PJD_GRIDSHIFT || dest.datum_type === PJD_NODATUM && source.datum_type !== PJD_GRIDSHIFT) {
>     return point;
>   }
> ```
> 
> ?

this works for us ! We had big differences due to missing gridshift. Thanks

**Comment by chvarma80** [comment]
> so to go around this problem we crated a jump. Gridshift crs -> bng-> 3857 and vice versa. The accuracy we get when comparing to ground control points is around 0.001.

Hi, How exactly you created the jump, I am having issue with this, vector layers are transforming properly but OSM is not transforming.

**Comment by ahocevar** [comment]
A possible workaround would be to define `EPSG:3857` differently:
```js
proj4.defs('EPSG:3857', '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +datum=WGS84 +wktext +no_defs');
```

**Comment by chvarma80** [comment]
Hi Mr.Hocevar

Are you saying i should define this projection 3857 and assign it to OSM?

I am trying to transform my all other data here to nadgrids (HS2TN15_NTv2),
you think the approach suggested by you will solve my problem?

Thanks
CHVARMA80

**Comment by ahocevar** [comment]
@chvarma80 Give it a try. Are you working with OpenLayers?

**Comment by chvarma80** [comment]
Hi

Yes, I am working on openlayers, I have tried and that does not work,
projection or no projection OSM is not matching the transformation, below
is my projection for the data transform.

proj4.defs(myProjectionName,'+proj=tmerc +lat_0=52.3 +lon_0=-1.5 +k=1
+x_0=198873.0046 +y_0=375064.3871 +ellps=WGS84 +units=m +no_defs
***@***.***,null'); // assigned key

As a result, I am getting all vector data from Geojson and points placed in
the openlayers ( Lat,lon) are transforming perfectly, however the OSM is
way off, refer below picture for shifting, please note that OSM vector data
layers are transforming perfectly.

Once again, thank you very much, I am facing too much difficulty on this.

[image: image.png]

**Comment by th30d0r** [comment]
Not sure what are the implication of removing that if statement, but I would think it should be consider. Tried the suggested implementation `if (source.datum_type === PJD_NODATUM && dest.datum_type !== PJD_GRIDSHIFT || dest.datum_type === PJD_NODATUM && source.datum_type !== PJD_GRIDSHIFT) {
    return point;
  }`, however that resulted in a very big error (~20 km shift ), so I am not sure that is correct.  
  
 The way to go around this bug is to just take what you want to convert and first convert it to bng, then to the what you need

**Comment by ahocevar** [comment]
@th30d0r Does the workaround work for you? Removing that if-block wouldn't be a good idea, because it would mean that we always try to apply a datum transform even if we don't know the source or destination datum.

**Comment by ahocevar** [comment]
@chvarma80 Please don't reply by e-mail, because that does not support images and also your projection string is obfuscated (`+nadgrids=@something`?).

**Comment by chvarma80** [comment]
Hi

I have tried the suggested implementation,  that doesn't do anything.
I am not sure what you are referring to when you say convert to bng i have
issue with OSM here, don't understand your suggestion.

**Comment by chvarma80** [comment]
Okay, my projection string has a key associated with arraybuffer as per the
documentation,  that part working fine.

Only issue with OSM falling somewhere else.

**Comment by th30d0r** [comment]
@ahocevar the work around works in my case. The part that is curious is that the python version works as expected. Haven't checked if they have that if statement in or not.

**Comment by chvarma80** [comment]
I am still  not sure, my map projection is HS2, I am parsing all data to
this projection and it is working fine except OSM, when you say hs2 to bng
to 3857, are you referring for OSM reprojection? When I declare OSM tiles
it is same with projection or without projection, projection is not
affecting OSM,  BTW the shifting of OSM is around 200meters.

**Comment by ahocevar** [comment]
@chvarma80 Is EPSG:3857 your destination projection? If so, there is no need to reproject an OSM tile layer, because that is in EPSG:3857 already. So I suspect you're indeed facing the same issue as @th30d0r, and I would suggest specifying EPSG:3857 in OpenLayers, like I explained in https://github.com/proj4js/proj4js/issues/389#issuecomment-1032341242.

@th30d0r I *think* the difference between proj4.js and its siblings in other languages is that not only `+datum=none` means NO DATUM, but also the case where no datum is implicitly or explicitly specified. That *may* mean WGS84 in other flavors, but I haven't had time yet to check the respective documentations throughly enough.

**Comment by chvarma80** [comment]
My destination projection is not 3857, it is HS2 with a grid shift, and I
have specified 3857 as you said, there is absolutely no change.

**Comment by th30d0r** [comment]
@ahocevar, tried with the proj4 that you are suggesting, and still the same. If i remember correctly there is somewhere in the codebase where you are searching specifically for WGS84 and 4326 and you set for those 2 the datum type as none

**Comment by chvarma80** [comment]
> @chvarma80 Is EPSG:3857 your destination projection? If so, there is no need to reproject an OSM tile layer, because that is in EPSG:3857 already. So I suspect you're indeed facing the same issue as @th30d0r, and I would suggest specifying EPSG:3857 in OpenLayers, like I explained in [#389 (comment)](https://github.com/proj4js/proj4js/issues/389#issuecomment-1032341242).
> 
> @th30d0r I _think_ the difference between proj4.js and its siblings in other languages is that not only `+datum=none` means NO DATUM, but also the case where no datum is implicitly or explicitly specified. That _may_ mean WGS84 in other flavors, but I haven't had time yet to check the respective documentations throughly enough.

Hi, I tried and results are below.

Target is -21996.086952553,6716648.661870895 should be transformed to 287489.63789701,289017.26270767

by using definition EPSG:3857 explicitly with wkt results are below, I have tried both ways

-21996.086952553,6716648.661870895 to [    287545.80280750577,    309841.7508930858]

287489.63789701,289017.26270767  to   [    -21996.121476101976,    6683170.586353322]

by using definition EPSG:3857  explicitly with proj4s/ results are below, 
I have tried both ways


-21996.086952553,6716648.661870895 to [    289239.8287468625,    290855.01380967756]

287489.63789701,289017.26270767  to   [    -24854.741233829904,    6713743.438139497]

Just FYI, have no issue in QGIS when I map my data on top of OSM.

**Comment by chvarma80** [comment]
> @chvarma80 Is EPSG:3857 your destination projection? If so, there is no need to reproject an OSM tile layer, because that is in EPSG:3857 already. So I suspect you're indeed facing the same issue as @th30d0r, and I would suggest specifying EPSG:3857 in OpenLayers, like I explained in [#389 (comment)](https://github.com/proj4js/proj4js/issues/389#issuecomment-1032341242).
> 
> @th30d0r I _think_ the difference between proj4.js and its siblings in other languages is that not only `+datum=none` means NO DATUM, but also the case where no datum is implicitly or explicitly specified. That _may_ mean WGS84 in other flavors, but I haven't had time yet to check the respective documentations throughly enough.

Also when I declare OSM instance in Openlayers like below, the 'projection: 'EPSG:firstProjection' part is not taking any effect, even if i say projection='bla bla', nothing is changing.


var raster = new ol.layer.Tile({source: new ol.source.OSM(),projection: 'EPSG:firstProjection' }); // OSM instance
