### ISSUE TITLE
proj4js version >= 2.6.1: Axis ordering "neu" and "cartesian coordinates"

### ISSUE THREAD

**Issue by DaniEll-AT** [proj4js/proj4js#391]
After upgrading proj4js from 2.6.0 to current release (2.7.4), i have to give/interpret coordinates in EPSG:31254 with [y,x] to get correct results.

We register EPSG:31254 with the following code:
`proj4.defs("EPSG:31254", "+proj=tmerc +lat_0=0 +lon_0=10.33333333333333 +k=1 +x_0=0 +y_0=-5000000 +ellps=bessel +towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232 +units=m +no_defs +axis=neu");`
Source: [epsg.io](//epsg.io/31254.js) plus `+axis=neu`

Our Test cases are:
EPSG:31254 -> EPSG:3857:
Input `proj4('EPSG:31254', 'EPSG:3857', [ 23372.0, 257544.1 ])`
Expected Result (<= 2.6.0 ): `[ 1184768, 6016861 ]`
Actual Result(>= 2.6.1): `[ 1515821, 5669327 ]`

EPSG:3857 -> EPSG:31254:
Input: `proj4('EPSG:3857', 'EPSG:31254', [ 1184760.3, 6016860.2 ])`
Expected Result (<= 2.6.0 ): `23366, 257543`
Actual Result (>= 2.6.1): `[ 257543, 23366 ]`

It seems the axis ordering convention of proj4js has changed.
According to your README
> Coordinates may [be] an object of the form {x:x,y:y} or an array of the form [x,y].

This seems not to be true anymore, at least when using the "Cartesian interpretation" (like many of us will do, using proj4js with OpenLayers)

**Comment by DaniEll-AT** [comment]
#279

**Comment by ahocevar** [comment]
Not sure if you're happy with this answer, but the solution is to simply remove the `+neu` parameter from the projection definition.

**Comment by ahocevar** [comment]
Regarding the "README", you are right. That change would probably have warranted a major version increase. I think making the new behavior an optional opt-in could make sense, but I'm not sure yet about the API for such a global option.

**Comment by DaniEll-AT** [comment]
Thanks for answering!

Removing `+axis=neu` would solve the Problem.

But in my case, removing `+axis=neu` is not an option, because there are other places in our codebase that depend on axis ordering (e.g. a generic Feature-Service-Client).

Thanks to your input according OpenLayers! We will upgrade proj4js when upgrading OpenLayers from 5.x to 6.x and then deal with proj4js's change in behaviour.

I will leave this issue open, because there were some interesting ideas in your last comment.

**Comment by ahocevar** [comment]
#392 would be one way to fix this issue, without making things complicated for users who want to enforce CRS axis order.

**Comment by DaniEll-AT** [comment]
Sounds good to me 👍
