### ISSUE TITLE
proj4 usable with jsdelivr?

### ISSUE THREAD

**Issue by nboisteault** [proj4js/proj4js#395]
Hi,
Is it possible to user proj4 with jsdelivr => https://www.jsdelivr.com/package/npm/proj4 ?
I tried : 
```javascript
import proj4 from 'https://cdn.jsdelivr.net/npm/proj4@2.7.5/lib/index.js';
```
but I had this error in console : 
`Uncaught TypeError: Failed to resolve module specifier "mgrs". Relative references must start with either "/", "./", or "../".`

Thanks.

**Comment by zarianec** [comment]
Hey, @nboisteault. Yes, it's possible to use proj4 with jsDelivr. But you have to convert it to an ESM module.

Fortunately, jsDelivr can bundle NPM packages to a [browser-compatible ESM modules](https://www.jsdelivr.com/esm) so the only thing you should do, is to change the URL for your import to use jsDelivr's ESM bundler:

```javascript
import proj4 from 'https://cdn.jsdelivr.net/npm/proj4@2.7.5/+esm';
```
