### ISSUE TITLE
Download links from http://proj4js.org/ don't contain code

### ISSUE THREAD

**Issue by IvanSanchez** [proj4js/proj4js#397]
The links from http://proj4js.org/ point to snapshots of the `gh-pages` branch, which do not include any JS code.

I suggest changing the links so that they point to https://github.com/proj4js/proj4js/releases instead.

**Comment by ahocevar** [comment]
Thanks for repoorting this, @IvanSanchez. These download buttons were never meant to be visible, and I was able to remove them again. A link to the releases page, as you suggested, is in the "Installing" section.

**Comment by IvanSanchez** [comment]
So this has been already fixed by https://github.com/proj4js/proj4js/commit/1d61a5e4c25467fc9f759e22d595aa644e75fad7 , then :-)
