### ISSUE TITLE
How to express geostationary orbit satellite coordinate data using proj4.js?

### ISSUE THREAD

**Issue by atlras** [proj4js/proj4js#398]
I am developing a grid format that uses the coordinates of satellite data in geostationary orbit to display on a web map.

Geostationary satellites use a projection called 'geos'. (https://proj.org/operations/projections/geos.html)
It seems that proj4.js does not support the 'geos' projection.

Are there any plans to support future 'geos' projections in proj4.js?
Or is there a projection that can be used for geostationary orbit satellite data among the projections supported by proj4.js?

**Comment by ahocevar** [comment]
You are right, `geos` is currently not implemented. If someone wants to implement it, we'd accept a pull request.

For showing the projected position of satellites on the surface of earth, it would be sufficient to use geograhic coordinates ('EPSG:4326').

**Comment by atlras** [comment]
Unfortunately,
I was working on rendering a rectangle of a certain size based on the coordinates, so I needed the projection used to produce the coordinates to display the rectangle correctly and without gaps.

I tried several projections, including the epsg:4326 you mentioned, but couldn't get the desired result...

Thanks for the reply, I'll try to find another way...

**Comment by djhoese** [comment]
FYI the 'geos' projection is now available as of version 2.8.0 as part of #405
