### ISSUE TITLE
Advice adding 'geos' projection

### ISSUE THREAD

**Issue by djhoese** [proj4js/proj4js#404]
I'm a developer on the GeoSphere (https://geosphere.ssec.wisc.edu/) site where we have created a modified version of proj4js that includes the geostationary projection calculations used in the PROJ C library. The developer who added the formulas is familiar with javascript but wasn't familiar with how to contribute to an open source library so the code was kept in our internal copy. I'd like to contribute this code to the library, but before I start cleaning up the code (javascript is not my primary language) I wanted to make sure this is something the maintainers are interested in or at least would accept. If so, what documentation exists for how to contribute to the project? I see the Developing section in the README [here](https://github.com/proj4js/proj4js/blob/master/README.md#developing) which will be very helpful. If there is anything else out there, let me know. If there are any gotchas you foresee I'm all ears for those tips too.

**Comment by ahocevar** [comment]
Thanks @djhoese, this countribution would be much appreciated. The README should cover the development process. You'll want to clone the repository and create a feature branch off master, where you make your changes. When done, push your changes to that branch, and create a pull request here on GitHub. If anything is missing, or if you have any questions as you work on the pull request, feel free to ask here on the ticket.

**Comment by djhoese** [comment]
I maintain a lot of python libraries so the git/github stuff should hopefully not be a problem. The javascript and making it look like the other supported projection code is another thing.
