### ISSUE TITLE
Confusion about dist size

### ISSUE THREAD

**Issue by djhoese** [proj4js/proj4js#406]
I read most of the discussion in #78 and saw the mention of building a custom version in the README, but am getting odd results. First, the `.min.js` version on the CDN is ~11KB. If I build locally I get a ~34.9kB. What minifying process is the `.min.js` version undergoing after build? Is this done automatically by the CDN?

My main confusion though is if I specify a few projections like `grunt build:merc,geos` I get a ~37.54kB file. So the output got bigger even though I'm only including two projections. Any idea what's going on?

**Comment by ahocevar** [comment]
What the cdn does to the .min.js file is not clear to me either, but the size you were looking at is the gzipped size. When downloaded locally, the size of `proj4.min.js` is 84 kB. When I create a full build (`npm run build`), the size of `dist/proj4.js` is 88 kb. So the size of 37.54 kB you get with only two projections looks plausible to me.

**Comment by djhoese** [comment]
Default:

```
$ node_modules/.bin/grunt build
Running "build" task

Running "jshint:all" (jshint) task
>> 96 files lint free.

Running "custom:default" (custom) task

Running "rollup:files" (rollup) task

Running "uglify:all" (uglify) task
>> 1 file created 88.91 kB → 34.9 kB
```

Limiting:

```
$ node_modules/.bin/grunt build:merc,geos
Running "build:merc,geos" (build) task

Running "jshint:all" (jshint) task
>> 96 files lint free.

Running "custom:merc:geos" (custom) task

Running "rollup:files" (rollup) task

Running "uglify:all" (uglify) task
>> 1 file created 100.11 kB → 37.54 kB

Done.
```

So even the pre-uglify is 20kB larger.

**Comment by djhoese** [comment]
Oh I suppose I should actually read the README instead of just searching for the part I wanted to use. Using `:all` gives more realistic results:

```
$ node_modules/.bin/grunt build:all
Running "build:all" (build) task

Running "jshint:all" (jshint) task
>> 96 files lint free.

Running "custom:all" (custom) task

Running "rollup:files" (rollup) task

Running "uglify:all" (uglify) task
>> 1 file created 224.27 kB → 89.75 kB

Done.
```

**Comment by djhoese** [comment]
And apparently the 10kb version of the file I thought I downloaded was actually the cdnjs site/page, not the actual package. The cdn is actually hosting the 86kB file when you download the right thing.
