### ISSUE TITLE
Getting wrong results for converting to EPSG: EPSG:28992

### ISSUE THREAD

**Issue by auvalice** [proj4js/proj4js#417]
*Note: I'm using probably some ancient version of proj4js that was bundled with OpenLayers 3, inside of a legacy application. If that could be the cause of what I'm running in to, there's that at least.*

I'm trying to convert between 
EPSG:4258 (https://epsg.io/4258)
and 
EPSG:28992 (https://epsg.io/28992)

(More specifically, according to the RDNAPTRANS2018 specifications). I assumed that it would be as simple as:

```js
proj4.defs("EPSG:4258","+proj=longlat +ellps=GRS80 +no_defs +type=crs");
proj4.defs("EPSG:28992","+proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,1.9342,-1.6677,9.1019,4.0725 +units=m +no_defs +type=crs");
// There are multiple other strings to be found for this EPSG, some you have to specifically request from the NSGI (https://www.nsgi.nl/rdnaptrans). 
// This is the one that can be found on the EPSG website, and is up to date according to this (Dutch) post: https://geoforum.nl/t/rdnaptrans-2018-implementatie-in-java/4636/4
// However, these strings all are different by a very small margin as far as I could tell (< 5mm)

let coords = [ 4.712120126, 51.728601274, 301.7981 ];
let results = proj4("EPSG:4258", "EPSG:28992", coords);
console.log({ results })
```

These results should be equal to `[108360.8790, 415757.2745, 258.0057]`, according to a validation document provided by the NSGI. I checked by transforming the coordinates directly on the EPSG websites, and the conversion there was valid according to the document. However, the results I get back here are `[108201.74069383202, 415691.0075817007, 257.52269405685365]`. These deviations are significant.

I've tried many different formulae for this calculation, and I'm having a lot of trouble figuring this out. I can think of three scenarios that are at play here:

1. An out of date version of proj4js has bugs related to the formula usage
2. The formula on the EPSG website is somehow invalid
3. The dataset I was given to validate my data is incorrect
4. I am not correctly using the library this way

My main questions here are:

- Am I using the library correctly like this? 
- How could I find out which of these problems is the issue I'm running in to?

**Comment by auvalice** [comment]
Update: I tried the same with the latest release of proj4js in a little sample project. 

```js
const proj4 = require("./proj4");

proj4.defs(
  "EPSG:28992",
  "+proj=sterea +lat_0=52.1561605555556 +lon_0=5.38763888888889 +k=0.9999079 +x_0=155000 +y_0=463000 +ellps=bessel +towgs84=565.4171,50.3319,465.5524,1.9342,-1.6677,9.1019,4.0725 +units=m +no_defs +type=crs"
);
proj4.defs("EPSG:4258", "+proj=longlat +ellps=GRS80 +no_defs +type=crs");

console.log(
  proj4("EPSG:4258", "EPSG:28992", [4.712120126, 51.728601274, 301.7981])
); // [ 108201.74069383202, 415691.00758170034, 301.7981 ]
```

So it's not the proj4js version, although I'm concerned that in this case, the third coordinate is not considered during the conversion...

**Comment by ahocevar** [comment]
Without knowing the specifics of your reference transform, it will be hard to help. And yes, the 3rd coordinate is just passed through untransformed in certain cases, so we'd have to look into that separately.

**Comment by Ylannl** [comment]
If you want the elevation to be transformed use EPSG:7415, this is EPSG:28992 + NAP height (national Dutch height reference).

This will not fix the issue of the shift in x and y though. I am encountering the same problem at the moment.

**Comment by auvalice** [comment]
> Without knowing the specifics of your reference transform, it will be hard to help. And yes, the 3rd coordinate is just passed through untransformed in certain cases, so we'd have to look into that separately.

Thanks for your response. I'm not sure what you mean with my reference transform. I unfortunately have very little experience when it comes to geography and coordinate systems.

In the last day, some new info popped up regarding the implementation:
- The people behind RDNAPTRANS2018 confirmed that the conversion string on EPSG.io is wrong (which is kind of strange, since it did work for converting my test coordinates). They mentioned that a lot of proj4 strings for the standard are outdated or very loose approximations.
- They also mentioned we'd be requiring the usage of a .gsb/.gtx file, but did not have any advice on how to do that implementation in JavaScript, since they weren't aware on how to use those files with JavaScript implementations of proj4.
- RDNAPTRANS2018 offers an API, which we are now using instead of proj4 for this specific conversion.

So for my usecase, this issue is no longer relevant. I'm not sure if you'd want to keep it open.

> If you want the elevation to be transformed use EPSG:7415, this is EPSG:28992 + NAP height (national Dutch height reference).
> 
> This will not fix the issue of the shift in x and y though. I am encountering the same problem at the moment (from EPSG:4326).

As mentioned above, we're now using an API. Specifically, the one NSGI provides. It's good that you mentioned the new EPSG, because as I discovered on their swagger page, EPSG:4258 _also_ seems to be incorrect:

https://editor.swagger.io/?url=https://api.transformation.nsgi.nl/v1

Instead, the conversions they offer via this API, are between EPSG:7415 and **EPSG:7931**, which is ETRF2000, which I assume is a slightly more up-to-date version of the EPSG? Either that, or it's just a 3D version. I'm not sure.

Anyway, this API can be freely requested from the NSGI website, so if your implementation is completely dependant on JS and it's okay for your users to have an online requirement, this might be a good path for you to follow.

**Comment by Ylannl** [comment]
FYI I fixed my issue by using this proj string:
`+proj=sterea +lat_0=52.15616055555555 +lon_0=5.38763888888889 +k=0.999908 +x_0=155000 +y_0=463000 +ellps=bessel +units=m +towgs84=565.2369,50.0087,465.658,-0.406857330322398,0.350732676542563,-1.8703473836068,4.0812 +no_defs +no_defs`

the epsg.io definition for EPSG:28992 and 7415 is indeed [outdated](https://geoforum.nl/t/betrouwbare-bron-voor-proj4-definitie-van-rd-new-epsg-28992/5144)
