### ISSUE TITLE
Different reprojection results between fme and proj4js

### ISSUE THREAD

**Issue by CarstenL** [proj4js/proj4js#423]
Hi,
i want to reproject my coordinate from 31466 to 3857, 4326 and 25832.
To valdidate the result, i have reprojected the coordinates with FME.
The following table shows the different transformations I tried. (Column Reprojected = Result from Proj4js / Column Target = Result from FME)

| Source EPSG      | Target EPSG      | Start X          | Start Y           | Reprojected X     | Reprojected Y     | Target X          | Target Y          | Precision | Result X | Result Y | Difference X | Difference Y |
| ---------------- | ---------------- | ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | --------- | -------- | -------- | ------------ | ------------ |
| 3857_datum       | 31466_grid_datum | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    |
| 3857_datum       | 31466_grid       | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    |
| 3857_datum       | 31466_datum      | 762634,443931574 | 6651545,680265270 | 2559260,529366960 | 5691626,640816280 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-291,470    | 20644,640    |
| 3857_datum       | 31466            | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    |
| 3857_datum       | 4326_datum       | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,3581671256307  | 6,85086177179725  | 51,1707077585789  | 7         | ok       | wrong    | 0,000        | 0,190        |
| 3857_datum       | 4326             | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,3581671256307  | 6,85086177179725  | 51,1707077585789  | 7         | ok       | wrong    | 0,000        | 0,190        |
| 3857_datum       | 25832_datum      | 762634,443931574 | 6651545,680265270 | 350367,542573823  | 5691848,031001680 | 349757,381710814  | 5671004,064991260 | 2         | wrong    | wrong    | 610,160      | 20843,970    |
| 3857_datum       | 25832            | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |
| 3857             | 31466_grid_datum | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    |
| 3857             | 31466_grid       | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    |
| 3857             | 31466_datum      | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    |
| 3857             | 31466            | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    |
| 3857             | 4326_datum       | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,17070775857890 | 6,85086177179725  | 51,1707077585789  | 7         | ok       | ok       | 0,000        | 0,000        |
| 3857             | 4326             | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,17070775857890 | 6,85086177179725  | 51,1707077585789  | 7         | ok       | ok       | 0,000        | 0,000        |
| 3857             | 25832_datum      | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        |
| 3857             | 25832            | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |
| 31466_grid_datum | 3857_datum       | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  |
| 31466_grid_datum | 3857             | 2559552          | 5670982           | 762717,700975639  | 6651773,264320600 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | 227,580      |
| 31466_grid_datum | 4326_datum       | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid_datum | 4326             | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid_datum | 25832_datum      | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid_datum | 25832            | 2559552          | 5670982           | 349813,826967806  | 5671145,065120890 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 56,450       | 141,000      |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |
| 31466_grid       | 3857_datum       | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  |
| 31466_grid       | 3857             | 2559552          | 5670982           | 762717,700975639  | 6651773,264320600 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | 227,580      |
| 31466_grid       | 4326_datum       | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid       | 4326             | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid       | 25832_datum      | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        |
| 31466_grid       | 25832            | 2559552          | 5670982           | 349813,826967806  | 5671145,065120890 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 56,450       | 141,000      |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |
| 31466_datum      | 3857_datum       | 2559552          | 5670982           | 762717,700975639  | 6618542,555774130 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | \-33003,120  |
| 31466_datum      | 3857             | 2559552          | 5670982           | 762717,700975639  | 6651773,264320600 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | 227,580      |
| 31466_datum      | 4326_datum       | 2559552          | 5670982           | 6,851609683       | 51,172573940      | 6,850861772       | 51,170707759      | 7         | wrong    | wrong    | 0,001        | 0,000        |
| 31466_datum      | 4326             | 2559552          | 5670982           | 6,851609683       | 51,172573940      | 6,850861772       | 51,170707759      | 7         | wrong    | wrong    | 0,001        | 0,000        |
| 31466_datum      | 25832_datum      | 2559552          | 5670982           | 349815,725801640  | 5671210,038483250 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 58,340       | 205,970      |
| 31466_datum      | 25832            | 2559552          | 5670982           | 349813,826967806  | 5671145,065120890 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 56,450       | 141,000      |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |
| 31466            | 3857_datum       | 2559552          | 5670982           | 762717,700975639  | 6651773,264320600 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | 227,580      |
| 31466            | 3857             | 2559552          | 5670982           | 762717,700975639  | 6651773,264320600 | 762634,443931573  | 6651545,680265260 | 2         | wrong    | wrong    | 83,260       | 227,580      |
| 31466            | 4326_datum       | 2559552          | 5670982           | 6,851609683       | 51,171989598      | 6,850861772       | 51,170707759      | 7         | wrong    | wrong    | 0,001        | 0,000        |
| 31466            | 4326             | 2559552          | 5670982           | 6,851609683       | 51,171989598      | 6,850861772       | 51,170707759      | 7         | wrong    | wrong    | 0,001        | 0,000        |
| 31466            | 25832_datum      | 2559552          | 5670982           | 349813,826967806  | 5671145,065120890 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 56,450       | 141,000      |
| 31466            | 25832            | 2559552          | 5670982           | 349813,826967806  | 5671145,065120890 | 349757,381712518  | 5671004,065049540 | 2         | wrong    | wrong    | 56,450       | 141,000      |

 EPSG             | Proj4 Definition                                                                                                                     |
| ---------------- | ------------------------------------------------------------------------------------------------------------------------------------ |
| 31466_grid_datum | +proj=tmerc +lat_0=0 +lon_0=6 +k=1 +x_0=2500000 +y_0=0 +ellps=bessel +units=m +no_defs +type=crs +nadgrids=@BETA2007.gsb +datum=DHDN |
| 31466_grid       | +proj=tmerc +lat_0=0 +lon_0=6 +k=1 +x_0=2500000 +y_0=0 +ellps=bessel +units=m +no_defs +type=crs +nadgrids=@BETA2007.gsb             |
| 31466_datum      | +proj=tmerc +lat_0=0 +lon_0=6 +k=1 +x_0=2500000 +y_0=0 +ellps=bessel +units=m +no_defs +type=crs +datum=DHDN                         |
| 31466            | +proj=tmerc +lat_0=0 +lon_0=6 +k=1 +x_0=2500000 +y_0=0 +ellps=bessel +units=m +no_defs +type=crs                                     |
|                  |                                                                                                                                      |
| 4326_datum       | +proj=longlat +datum=WGS84 +no_defs +datum=WGS84                                                                                     |
| 4326             | +proj=longlat +datum=WGS84 +no_defs                                                                                                  |
|                  |                                                                                                                                      |
| 25832_datum      | +proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs +datum=ETRS89                                     |
| 25832            | +proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs                                                   |
|                  |                                                                                                                                      |
| 3857_datum       | +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +datum=WGS84                   |
| 3857             | +proj=merc +lon_0=0 +k=1 +x_0=0 +y_0=0 +a=6378137 +b=6378137 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs                                |

I assumed that if I always specify +nadgrids=BETA2007.gsb, the result should be the most accurate. 
Unfortunately, this is not always the case. 

My goal is to simply specify four Proj4 strings that will give me the correct result for each combination. 
However, according to the list, this is currently not possible. 
Therefore, I suspect there is a bug somewhere in the code. 
I suspect this is the same or similar behavior as #389

**Comment by CarstenL** [comment]
I have followed the instruction in the README file.
The grid file was read into an arraybuffer and passed into proj4.nadgrid.
Thats not the problem. In some cases it works as expected (31466_grid_datum to 25832_datum)
But in some cases, proj4js returns the wrong coordinates (31466_grid_datum to 3857_datum)

**Comment by ahocevar** [comment]
@CarstenL Can you please check if #424 fixes the problem?

**Comment by CarstenL** [comment]
In some cases, the reprojected coordinates are right.
But some results have become worse.

i added 2 columns at the end of the following table which indicates, if the reprojected results changed after your fix.

| Source EPSG      | Target EPSG      | Start X          | Start Y           | Reprojected X     | Reprojected Y     | Target X          | Target Y          | Precision | Result X | Result Y | Difference X | Difference Y | Changed X   | Changed Y   |
| ---------------- | ---------------- | ---------------- | ----------------- | ----------------- | ----------------- | ----------------- | ----------------- | --------- | -------- | -------- | ------------ | ------------ | ----------- | ----------- |
| 3857_datum       | 31466_grid_datum | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    | not changed | not changed |
| 3857_datum       | 31466_grid       | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    | not changed | not changed |
| 3857_datum       | 31466_datum      | 762634,443931574 | 6651545,680265270 | 2559260,529366960 | 5691626,640816280 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-291,470    | 20644,640    | not changed | not changed |
| 3857_datum       | 31466            | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    | not changed | not changed |
| 3857_datum       | 4326_datum       | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,3581671256307  | 6,85086177179725  | 51,1707077585789  | 7         | ok       | wrong    | 0,000        | 0,190        | not changed | not changed |
| 3857_datum       | 4326             | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,3581671256307  | 6,85086177179725  | 51,1707077585789  | 7         | ok       | wrong    | 0,000        | 0,190        | not changed | not changed |
| 3857_datum       | 25832_datum      | 762634,443931574 | 6651545,680265270 | 350367,542573823  | 5691848,031001680 | 349757,381710814  | 5671004,064991260 | 2         | wrong    | wrong    | 610,160      | 20843,970    | not changed | not changed |
| 3857_datum       | 25832            | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |             |             |
| 3857             | 31466_grid_datum | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    | **changed**     | **changed**    |
| 3857             | 31466_grid       | 762634,443931574 | 6651545,680265270 | 2559310,219095610 | 5691836,846135580 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-241,780    | 20854,850    | **changed**     | **changed**     |
| 3857             | 31466_datum      | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    | not changed | not changed |
| 3857             | 31466            | 762634,443931574 | 6651545,680265270 | 2559501,350034250 | 5670838,807633720 | 2559551,999999500 | 5670981,999939660 | 2         | wrong    | wrong    | \-50,650     | \-143,190    | not changed | not changed |
| 3857             | 4326_datum       | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,17070775857890 | 6,85086177179725  | 51,1707077585789  | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 3857             | 4326             | 762634,443931574 | 6651545,680265270 | 6,85086177179725  | 51,17070775857890 | 6,85086177179725  | 51,1707077585789  | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 3857             | 25832_datum      | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 3857             | 25832            | 762634,443931574 | 6651545,680265270 | 349757,381711052  | 5671004,064991200 | 349757,381710814  | 5671004,064991260 | 2         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |             |             |
| 31466_grid_datum | 3857_datum       | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  | not changed | not changed |
| 31466_grid_datum | 3857             | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  | **changed**     | **changed**     |
| 31466_grid_datum | 4326_datum       | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid_datum | 4326             | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid_datum | 25832_datum      | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid_datum | 25832            | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        | **changed**     | **changed**     |
|                  |                  |                  |                   |                   |                   |                   |                   |           |          |          |              |              |             |             |
| 31466_grid       | 3857_datum       | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  | not changed | not changed |
| 31466_grid       | 3857             | 2559552          | 5670982           | 762634,443933891  | 6618215,756408500 | 762634,443931573  | 6651545,680265260 | 2         | ok       | wrong    | 0,000        | \-33329,920  | **changed**     | **changed**    |
| 31466_grid       | 4326_datum       | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid       | 4326             | 2559552          | 5670982           | 6,850861772       | 51,170707761      | 6,850861772       | 51,170707759      | 7         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid       | 25832_datum      | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        | not changed | not changed |
| 31466_grid       | 25832            | 2559552          | 5670982           | 349757,381723482  | 5671004,065366560 | 349757,381712518  | 5671004,065049540 | 2         | ok       | ok       | 0,000        | 0,000        | **changed**     | **changed**     |

for example:
From 3857 to 31466_grid_datum = become more inaccurate
From 31466_grid_datum to 25832 = result ok now.

Now it seems, there is only a problem when i reproject from 3857 or to 3857.
31466_grid_datum to 3857 (with or without +datum parameter) = X correct, Y ca. 33000m away from expected result.

**Comment by ahocevar** [comment]
@CarstenL It would be great if you could provide the gsb file you're using for these experiments. Also, if you could try again without redefining `EPSG:3857`, because we have a built-in def for that:
```js
defs('EPSG:3857', "+title=WGS 84 / Pseudo-Mercator +proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +no_defs");
```

**Comment by CarstenL** [comment]
I tried EPSG:3857, EPSG:3785, EPSG:900913 and GOOGLE but i get the same result as in the second table (Source EPSG: 3857).

The file i use is the following: [BETA2007.zip](https://github.com/proj4js/proj4js/files/10389596/BETA2007.zip)

**Comment by ahocevar** [comment]
Thanks for your cooperation on this, @CarstenL. I was able to add tests and modify #424, so the issue should really be fixed now. Can you check again please?

**Comment by CarstenL** [comment]
I have extended my tests so that I check every combination.
The result looks great. I always get the expected result.
Good job and thanks for the quick help!
Could you merge your fix and create a release please?

**Comment by ahocevar** [comment]
Thanks for the feedback, I'm going to publish a release.

If you're a frequent user of proj4js, please consider sponsoring me through https://github.com/sponsors/ahocevar/, or encourage your employer to do so. Ideally through a recurring contribution. It helps me to set aside time for maintaining this library.
