### ISSUE TITLE
"author", "contributors" and "homepage" fields in package.json are empty

### ISSUE THREAD

**Issue by rhuitl** [proj4js/proj4js#426]
You  might want to put the author and the contributors into the respective fields of `package.json` so that software like https://github.com/pivotal/LicenseFinder can pick it up and include it in OSS-license related reports (see https://docs.npmjs.com/cli/v9/configuring-npm/package-json#people-fields-author-contributors).

When you install proj4js with NPM 6 or earlier, you used to get (sic!) `", Mike Adair, Richard Greenwood, Calvin Metcalf, Richard Marsden, T. Mittan, D. Steinwand, S. Nelson"` in the `package.json` file in `node_modules`. I don't know where NPM took this list from. Maybe the NPM registry.

With NPM7 and later, your `package.json` file is used unchanged, so the author and contributors are empty.
You might further want to put the `homepage` field in to point to, e.g. http://proj4js.org/.

**Comment by ahocevar** [comment]
@rhuitl Our `package.json` contains a `repository` entry, and a git repository allows you to get way better information about involved contributors, e.g. through GitHub's ["Insights"](https://github.com/proj4js/proj4js/graphs/contributors).

Thanks for the hint about the missing "homepage" field, which I just added in #427.
