### ISSUE TITLE
Incorrect LCC transformation (EPSG:27571)

### ISSUE THREAD

**Issue by janruo** [proj4js/proj4js#429]
Transforming to EPSG:27571 seems to produce inaccurate results. I tested the same coordinate with OSGeo PROJ, and that seems to be accurate according to epsg.io.

Input coordinate: https://epsg.io/map#srs=4326&x=2.294482&y=48.859045&z=17&layer=streets

OSGeo PROJ result: https://epsg.io/map#srs=27571&x=596916.561147926957&y=1128733.073948238511&z=17&layer=streets

proj4js result: https://epsg.io/map#srs=27571&x=596916.5179091952&y=1128386.7144043378&z=17&layer=streets

Runkit https://runkit.com/63f47a692a8ce500081dbf40/63f47a696efe340008433822

```js
const proj4 = require("proj4")

// $ projinfo -o proj epsg:4326
const epsg4326 = "+proj=longlat +datum=WGS84 +no_defs +type=crs";
// $ projinfo -o proj epsg:27571
const epsg27571 = "+proj=lcc +lat_1=49.5 +lat_0=49.5 +lon_0=0 +k_0=0.999877341 +x_0=600000 +y_0=1200000 +ellps=clrk80ign +pm=paris +towgs84=-168,-60,320,0,0,0,0 +units=m +no_defs +type=crs";

// Corner of the Eiffel Tower
const input = [2.294482, 48.859045];
// $ echo 2.294482 48.859045 | cs2cs -f %.12f +init=epsg:4326 +to +init=epsg:27571
const expected = [596916.561147926957, 1128733.073948238511];

const transform = proj4(epsg4326, epsg27571);
const actual = transform.forward([2.294482, 48.859045]);
const error = [expected[0] - actual[0], expected[1] - actual[1]];

console.log("Actual: " + actual);
console.log("Error: " + error);
```

```
Actual: 596916.5179091952,1128386.7144043378
Error: 0.04323873179964721,346.359543900704
```

proj4js version 2.8.1

**Comment by ahocevar** [comment]
@janruo Thanks for reporting this. The reason is that the `clrk80ign` ellipsoid is not defined in proj4js. If you use
```js
const epsg27571 = "+proj=lcc +lat_1=49.5 +lat_0=49.5 +lon_0=0 +k_0=0.999877341 +x_0=600000 +y_0=1200000 +ellps=clrk80 +pm=paris +towgs84=-168,-60,320,0,0,0,0 +units=m +no_defs +type=crs";
```
(i.e. `+ellps=clrk80` instead of `+ellps=clrk80ign`) you'll get
```js
[ 596916.5611686371, 1128733.0538483409 ]
```
which is close enough to the desired result. We could of course add the `clrk80ign` Ellipsoid. Do you have the parameters for that?

**Comment by janruo** [comment]
@ahocevar I think the parameters are here: https://epsg.org/ellipsoid_7011/Clarke-1880-IGN.html
