### ISSUE TITLE
EPSG:25832 uncought

### ISSUE THREAD

**Issue by FadiMoubayed** [proj4js/proj4js#443]
I add proj4js to my project using "https://cdnjs.cloudflare.com/ajax/libs/proj4js/2.9.0/proj4.js".
I would like to project coordinates from EPSG:25832 to WGS82. The code only works when I provide the wkt of the CRS. It does not work if I only provide the EPSG.

Working example:

```
    const sourceCRS = "+proj=utm +zone=32 +ellps=GRS80 +units=m +no_defs +type=crs";
    const targetCRS = '+proj=longlat +datum=WGS84 +no_defs';
    const point = proj4(sourceCRS, targetCRS, [x, y]);
```

Failing example:

`const point = proj4("EPSG:25832", "EPSG:4326", [x, y]);`

Error:
uncaught EPSG:25832

The issue seems to only be with the CRS EPSG:25832

**Comment by ahocevar** [comment]
This is expected. proj4 does not carry a database of projection definitions, and it does not perform lookups against an online database. It only includes a few very common projection definitions. See https://github.com/proj4js/proj4js/blob/master/lib/global.js.

**Comment by AskSkivdal** [comment]
You can set a definition so you don't have to specify it each time. To do this you can do
```js
proj4.defs("EPSG:25832","+proj=utm +zone=32 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs +type=crs");
```
