### ISSUE TITLE
Geocentric to topocentric conversion

### ISSUE THREAD

**Issue by swarmt** [proj4js/proj4js#447]
Is there a way to create a [geocentric to topocentric conversion](https://proj.org/en/9.2/operations/conversions/topocentric.html)?

**Comment by ahocevar** [comment]
For sure! Just find the correct SRS definitions in proj or WKT v1 format for the desired input (`fromProjection`) and output projection (`toProjection`), and then use `proj4(fromProjection, toProjection, coordinates)`.

**Comment by swarmt** [comment]
Thanks for getting back to me.
```typescript
const firstProjection = '+proj=geocent +datum=WGS84 +units=m +no_defs +type=crs';
const secondProjection = '+proj=topocentric +ellps=WGS84 +X_0=3652755.3058 +Y_0=319574.6799 +Z_0=5201547.3536';
proj4(firstProjection,secondProjection);
```
Throws an error, am I doing something silly?

**Comment by swarmt** [comment]
No worries! Thanks for the help.
