### ISSUE TITLE
transform.js:103 Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by michealroberts** [proj4js/proj4js#449]
I'm using proj4.js alongside OpenLayers, and I'm wanting to get some advise on the above error.

It's not easily obvious where the code has gone wrong, so reaching out. Please let me know if the following information is enough, I'm happy to supply as much of the code as possible to try and ascertain the issue.

Essentially, the code registering the following 3 projections as:

```ts
proj4.defs(
  'EPSG:3857',
  '+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs',
);
proj4.defs(
  'EPSG:3995',
  '+proj=stere +lat_0=90 +lat_ts=71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs',
);
proj4.defs(
  'EPSG:3031',
  '+proj=stere +lat_0=-90 +lat_ts=-71 +lon_0=0 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs +type=crs',
);

register(proj4);
```

When using these projections in combination with OpenLayers, we see the following stack trace error ...

<img width="415" alt="Screenshot 2023-10-03 at 10 15 48" src="https://github.com/proj4js/proj4js/assets/84131395/b5d4b652-ca34-41db-a7f1-5ec97916680c">

The OpenLayers setup is as follows:

```ts
import { get as getProjection, transform } from 'ol/proj';

const projection = getProjection(Map.Projection.toCode(this.mapSettings_.projection)); // e.g., "`'EPSG:3857' | null`"

if (!projection) return; // Just to be sure

// Code reaches this point ...

const view = new View({
      center: transform(
        this.mapSettings_.center,
        Map.Projection.toCode(Map.Projection.WGS84),
        Map.Projection.toCode(this.mapSettings_.projection),
      ), /// <- seems to error on this calculation :(
      zoom: this.mapSettings_.zoom,
      minZoom: this.mapSettings_.minZoom,
      maxZoom: this.mapSettings_.maxZoom,
      projection,
});

aMap.setView(view);
```

It seems to work for the `EPSG:3857` defined projection -> but not for `EPSG:3995` or `EPSG:3031`...

I'm not sure where to go with this other than reaching out for expert help to understand the issue ... (which is likely our issue).

Thank you in advanced! 🙏 

---

Versions:

```json
{
    "ol": "^7.5.2",
    "proj4": "^2.9.0",
}
```

**Comment by michealroberts** [comment]
Having done some more digging and research, I believe I need to also set an extent ... 😬 is this correct?

**Comment by ahocevar** [comment]
Yes, it looks like you’re using OpenLayers raster reprojection. An extent will avoid attempts to transform coordinates outside the validity extent of the projection.
