### ISSUE TITLE
Transforming coordinates may throw error when no z is set

### ISSUE THREAD

**Issue by MoonE** [proj4js/proj4js#450]
#335 broke transformation between some projections.

https://github.com/openlayers/openlayers/issues/15233
For example the  `forward` transform from `'EPSG:3857'` to `'EPSG:3414'` will return `null` for `[0, 0]` which throws here:
https://github.com/proj4js/proj4js/blob/d9faf9f93ebeccac4b79fa80f3e9ad8a7032828b/lib/transform.js#L102-L104

**Comment by MoonE** [comment]
Here's a test case for this:
```js
      it('should return null for transform of [0, 0] for EPSG:3413 -> EPSG:3857', function () {
        proj4.defs('EPSG:3413', '+proj=stere +lat_0=90 +lat_ts=70 +lon_0=-45 +k=1 +x_0=0 +y_0=0 +datum=WGS84 +units=m +no_defs');
        var point = proj4.transform(
          proj4.Proj('EPSG:3413'),
          proj4.Proj('EPSG:3857'),
          [0, 0]
        );
        assert.strictEqual(point, null);
      });
```

**Comment by ahocevar** [comment]
Thanks for the detailed bug report and test case. I created #451 to fix this.
