### ISSUE TITLE
missmatch between README.md of the repo & your website

### ISSUE THREAD

**Issue by moong23** [proj4js/proj4js#466]
website:

Using
The basic signature is:

```
proj4(fromProjection[, toProjection, coordinates])
```
Projections can be proj or wkt strings.

while your repo's readme is:

Using
The basic signature is:

```
proj4([fromProjection, ]toProjection[, coordinates])
```
Projections can be proj or wkt strings.

**Comment by ahocevar** [comment]
Thanks for reporting this, I just updated the website.
