### ISSUE TITLE
https://epsg.io/3168

### ISSUE THREAD

**Issue by synasir** [proj4js/proj4js#468]
https://epsg.io/3168
proj4.defs("EPSG:3168","+proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257905 +k=0.99984 +x_0=804670.24 +y_0=0 +no_uoff +gamma=323.1301023611111 +a=6377295.664 +b=6356094.667915204 +units=m +no_defs");

https://epsg.io/transform#s_srs=4326&t_srs=3168&x=101.7108894&y=10.0060703
Long: 101.7108895
Lat: 10.0060703

via EPSG.io
X: 414290.16
Y: 1106912.8

Converting via proj4js instead returns
X: 744896.0367651524
Y: 664384.3852478617

_Originally posted by @unknowdata in https://github.com/proj4js/proj4js/issues/375#issuecomment-764616797_

**Comment by synasir** [comment]
proj4.defs("EPSG:3168","+proj=omerc +lat_0=4 +lonc=102.25 +alpha=323.0257905 +k=0.99984 +x_0=804670.24 +y_0=0 +no_uoff +gamma=323.1301023611111 +a=6377295.664 +b=6356094.667915204 +units=m +no_defs");

https://epsg.io/transform#s_srs=4326&t_srs=3168&x=101.7108894&y=10.0060703
Long: 101.7108895
Lat: 10.0060703

Everything is the same as above but now EPSG.IO is giving these results:

X: 414452.3911424828
Y: 1106990.416398386

Python PYPROJ is also giving me the same result as the one above.

**Comment by ahocevar** [comment]
proj4js does not understand the `+gamma` Parameter in a proj4 def string. Please use WKT instead:
```js
var proj4 = require("proj4")
proj4('EPSG:4326', "+proj=omerc +no_uoff +lat_0=4 +lonc=102.25 +alpha=323.0257905 +gamma=323.130102361111 +k=0.99984 +x_0=804670.24 +y_0=0 +ellps=evrst69 +towgs84=-11,851,5,0,0,0,0 +units=m +no_defs +type=crs", [101.7108895, 10.0060703]);

// [414452.39724301395, 1106990.4188566748]

**Comment by synasir** [comment]
Thanks for the prompt reply.  Just noticed the missing towgs84 parameters. Everything works now. Thanks.
