### ISSUE TITLE
Cannot convert from EPSG:4978 using its WKT

### ISSUE THREAD

**Issue by anne-gropler** [proj4js/proj4js#470]
Using OGC WKT (not OGC WKT 2), the following throws an error:

```
try {
	const foo = proj4(
		// https://epsg.io/4978
		'GEOCCS["WGS84",DATUM["WGS_1984",SPHEROID["WGS84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["GeocentricX",OTHER],AXIS["GeocentricY",OTHER],AXIS["GeocentricZ",NORTH],AUTHORITY["EPSG","4978"]]',
		// https://epsg.io/25832
		'PROJCS["ETRS89/UTMzone32N",GEOGCS["ETRS89",DATUM["European_Terrestrial_Reference_System_1989",SPHEROID["GRS1980",6378137,298.257222101,AUTHORITY["EPSG","7019"]],TOWGS84[0,0,0,0,0,0,0],AUTHORITY["EPSG","6258"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4258"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",9],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","25832"]]',
	);
} catch (e) {
	console.error(e);
}
```

The logged error is just the WKT of 4978, so it's not helpful.

I debugged a bit and it seems that `parseCode()` returns a `json` without a `projName`. Looking at the WKT, there is no `PROJECTION`, so that seems expected. However, in `wkt-parser`, there is also code in `cleanWKT` that adds the `projName`:
```js
function cleanWKT(wkt) {
 if (wkt.type === 'GEOGCS') {
    wkt.projName = 'longlat';
  } else if (wkt.type === 'LOCAL_CS') {
    wkt.projName = 'identity';
    wkt.local = true;
  } else {
    if (typeof wkt.PROJECTION === 'object') {
      wkt.projName = Object.keys(wkt.PROJECTION)[0];
    } else {
      wkt.projName = wkt.PROJECTION;
    }
  }
...
```

If I add a case here for `GEOCCS`, adding `wkt.projName = 'identity'`, it seems to fix the issue, but I have not enough knowledge about EPSGs, WKTs and transformations to understand if that is a viable fix or just a hack working for my specific case, so I would appreciate some help or a proper fix in proj4js or wkt-parser.

**Comment by ahocevar** [comment]
wkt-parser does not support geocentric currently. There would be more to it than just the hack you mentioned. However, geocentric works fine with proj strings instead of WKT defs.

**Comment by anne-gropler** [comment]
I see. Would you mind documenting this, either in proj4js or in wkt-parser? Or maybe adding a check in the code so that a more helpful error message comes out of it?

**Comment by ahocevar** [comment]
Due to lack of funding, I'm maintaining this project in my free time. Sponsoring on https://github.com/sponsors/ahocevar would help a lot to set time aside for maintenance work like this.

**Comment by anne-gropler** [comment]
That's fair.

I created https://github.com/proj4js/proj4js/pull/471 and https://github.com/proj4js/wkt-parser/pull/27, which contain small documentation changes that will hopefully help other devs using proj4js and the wkt-parser.
