### ISSUE TITLE
Is there a way to query the units of a given ProjectionDefinition ?

### ISSUE THREAD

**Issue by sguimmara** [proj4js/proj4js#478]
When creating a `ProjectionDefinition` from a proj string that has the `+units` parameter defined, then `ProjectionDefinition.units` is defined.

However, when creating the same definition from the equivalent WKT string, this property remain undefined (and we have to parse the WKT definition inside the `ProjectionDefinition`.

Is there a simpler way to query the units in a format agnostic way ?

**Comment by ahocevar** [comment]
There is no way to get the units, but you can get the meters per unit from the `to_meter` property in a format agnostic way.

**Comment by sguimmara** [comment]
Thanks :)
