### ISSUE TITLE
add support for more unit types in projection definitions

### ISSUE THREAD

**Issue by tfrisvold** [proj4js/proj4js#480]
Currently Proj4 has these unit types supported:
$ cs2cs -lu
          mm 0.001                millimetre
          cm 0.01                 centimetre
           m 1                    metre
          ft 0.3048               foot
       us-ft 0.304800609601219    US survey foot
        fath 1.8288               fathom
         kmi 1852                 nautical mile
       us-ch 20.1168402336805     US survey chain
       us-mi 1609.34721869444     US survey mile
          km 1000                 kilometre
      ind-ft 0.30479841           Indian foot (1937)
      ind-yd 0.91439523           Indian yard (1937)
          mi 1609.344             Statute mile
          yd 0.9144               yard
          ch 20.1168              chain
        link 0.201168             link
          dm 0.01                 decimeter
          in 0.0254               inch
      ind-ch 20.11669506          Indian chain
       us-in 0.025400050800101    US survey inch
       us-yd 0.914401828803658    US survey yard

But Proj4JS only supports these:
meter, ft, and us-ft

Please add all the above to lib/constants/units.js:
export default {
  'mm': {to_meter: 0.001},
  'cm': {to_meter: 0.01},
  'ft': {to_meter: 0.3048},
  'us-ft': {to_meter: 0.304800609601219},
  'fath': {to_meter: 1.8288},
  'kmi': {to_meter: 1852},
  'us-ch': {to_meter: 20.1168402336805},
  'us-mi': {to_meter: 1609.34721869444},
  'km': {to_meter: 1000},
  'ind-ft': {to_meter: 0.30479841},
  'ind-yd': {to_meter: 0.91439523},
  'mi': {to_meter: 1609.344},
  'yd': {to_meter: 0.9144},
  'ch': {to_meter: 20.1168},
  'link': {to_meter: 0.201168},
  'dm': {to_meter: 0.01},
  'in': {to_meter: 0.0254},
  'ind-ch': {to_meter: 20.11669506},
  'us-in': {to_meter: 0.025400050800101},
  'us-yd': {to_meter: 0.914401828803658}
};

**Comment by ahocevar** [comment]
Pull request welcome.

**Comment by tfrisvold** [comment]
I have never done this before... but I think I did a pull request... let me know if I need to do anything more.
