### ISSUE TITLE
add support to Proj.4 nadgrids parameter (grid based datum adjustments)

### ISSUE THREAD

**Issue by exPangea** [proj4js/proj4js#62]
Proj.4 nadgrids parameter cannot be passed to proj4.js (at least when using it in client browser) 

This is necessary for grid based datum adjustments, as described in the official Proj.4 documentation: 
https://proj4.org/usage/transformation.html?highlight=nadgrids#grid-based-datum-adjustments

Example datum shift grids are available at https://proj4.org/resource_files.html#transformation-grids

If possible, it would be desirable to have the choice of loading grid files from server, client (local filesystem) and/or remote urls.

**Comment by andreasplesch** [comment]
Looking at earlier versions, I found this ticket which implemented support for nadgrids:

https://trac.osgeo.org/proj4js/ticket/81#no1

Was this not fully compatible with new proj4js or not functional ?

**Comment by calvinmetcalf** [comment]
@andreasplesch it was started but never finished so it was removed due to it not functioning

**Comment by andreasplesch** [comment]
Since it was a port from proj4, this looked like a good start. Oh well, perhaps the added accuracy is not worth the effort in most use cases.

**Comment by calvinmetcalf** [comment]
If somebody wanted to add the functionality that would be the place to
start

**Comment by andreasplesch** [comment]
ok.

**Comment by fakharkhalid** [comment]
Are there any plans in the proj4js roadmap to address this issue?

**Comment by ahocevar** [comment]
@fakharkhalid If anyone wants to contribute that feature, it would be a welcome pull request. The only thing to keep in mind is that grids should not be included in the build, because otherwise the library size would get too big for browser use.

**Comment by geoffsmith** [comment]
I've made a start on implementing this: [https://github.com/geoffsmith/proj4js/tree/nadgrids](https://github.com/geoffsmith/proj4js/tree/nadgrids)

That branch includes a rough working version, though it will only work for node right now. My plan over the next few days is to figure out how to get it working for the browser, clean it up, then make a pull request. I'm quite new to projections, so I had to rely heavily on the old implementation linked to above. I've cleaned it up a little and made a few changes to get it to work (that I think might have been typos). I've tested it against the UK Ordnance Survey nadgrid file, they handily  [provide a set of test points]( https://www.ordnancesurvey.co.uk/business-government/tools-support/os-net/for-developers) that I've used to verify the code works.

It would be great to have someone more knowledgeable have a look at the points where I've integrated the nadgrids corrections with the usual transformation code just to make sure I've not mis-understood something.

**Comment by geoffsmith** [comment]
@ahocevar I've created a [pull request](https://github.com/proj4js/proj4js/pull/363) for this feature. Is it worth me pinging someone to take a look at it?

**Comment by agiudiceandrea** [comment]
@ahocevar shouldn't this feature request be closed since https://github.com/proj4js/proj4js/pull/363 was merged?

**Comment by ahocevar** [comment]
You're absolutely right @agiudiceandrea. Thanks for the pointer! Fixed with #363.
