### ISSUE TITLE
x0 and y0 defaults

### ISSUE THREAD

**Issue by djhoese** [proj4js/proj4js#99]
I might be defining my projection incorrectly but I never considered `+x_0` and `+y_0` required parameters. If these are not defined they stay as undefined in the code. In my case I was going from `WGS84` lon/lat to a `lcc` projection that didn't have these defined. When it got [here](https://github.com/proj4js/proj4js/blob/master/lib/projections/lcc.js#L90) it set the output `x` and `y` to NaN. Not sure why, but this didn't happen on the inverse operation.

Not sure, but this may only be a problem with `lcc`. I'm also not sure where the "proper" place for a fix would be otherwise I'd do it myself. Specifying the parameters in the projection definition fixes the problem.

**Comment by benjimin** [comment]
Using the orthographic projection `+proj=ortho` fails if not explicitly setting `+x_0=0 +y_0=0` despite that the [proj docs](https://proj.org/en/stable/operations/projections/ortho.html) state both should already default to `0.0`.

This seems like a bug, that the defaults are not getting applied, contrary to docs.

This is undesirable for usability, as the user cannot anticipate which parameters they are required to set (except by trial and error, or searching for usage examples from elsewhere to compare).

**Comment by ahocevar** [comment]
Fixed with #541
